SUBROUTINE TOTO_OPENACC (A, KLON)
  
!$acc routine( TOTO_OPENACC ) seq
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  INTEGER :: KIDIA
  INTEGER :: KFDIA
  INTEGER, INTENT(IN) :: KLON
  REAL, INTENT(INOUT) :: A(KLON)
  REAL :: TOTO(KLON)
  INTEGER :: JLON
  JLON=KIDIA
  
  TOTO(JLON) = 0.0
  A(JLON) = 2.0
  
END SUBROUTINE TOTO_OPENACC

