INTERFACE
  SUBROUTINE ACNEBXRS_OPENACC (YDPHY, YDPHY0, KIDIA, KFDIA, KLON, KTDIA, KLEV, PQ, PQC, PQSAT, PNEB, YDSTACK)
!$acc routine( ACNEBXRS_OPENACC )
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    USE YOMPHY, ONLY: TPHY
    USE YOMPHY0, ONLY: TPHY0
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(TPHY), INTENT(IN) :: YDPHY
    TYPE(TPHY0), INTENT(IN) :: YDPHY0
    INTEGER(KIND=JPIM), INTENT(IN) :: KLON
    INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
    INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
    REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PQC(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PQSAT(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(INOUT) :: PNEB(KLON, KLEV)
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE ACNEBXRS_OPENACC
END INTERFACE
