SUBROUTINE ACPLUIS_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRSF, PDELP, PNEBS, PQ, PQLIS, PQW, PR, PT,  &
& PFCSQL, PFCSQN, PFPLSL, PFPLSN, PFPEVPL, PFPEVPN, PFPFPL, PFPFPN, YDSTACK)
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  ! - OUTPUT 2D .
  
  !**** *ACPLUIS * - CALCUL DES FLUX DE PRECIPITATIONS STRATIFORMES.
  
  !     Sujet.
  !     ------
  !     - ROUTINE DE CALCUL ACTIF .
  !       CALCUL DES FLUX DE PRECIPITATIONS STRATIFORMES (LIQUIDE ET
  !         NEIGE) SELON UN SCHEMA STATISTIQUE DE PRECIPITATIONS.
  !     - COMPUTATION OF STRATIFORM PRECIPITATION FLUXES (WATER AND
  !         SNOW) ACCORDING TO A PRECIPITATIONS STATISTIC SCHEME.
  
  !**   Interface.
  !     ----------
  !        *CALL* *ACPLUIS*
  
  !-----------------------------------------------------------------------
  ! WARNING: THE ENGLISH VERSION OF VARIABLES' NAMES IS TO BE READ IN THE
  !          "APLPAR" CODE.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS D'ENTREE.
  !     -------------------
  
  ! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.
  
  ! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
  ! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
  ! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
  ! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
  ! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 2D (1:KLEV) .
  
  ! PAPRSF     : PRESSION AUX NIVEAUX DES COUCHES.
  ! PDELP      : EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PNEBS      : NEBULOSITE STRATIFORME (SCHEMA DE RICARD).
  ! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
  ! PQLIS      : QUANTITE D'EAU LIQUIDE (SCHEMA DE RICARD).
  ! PQW        : HUMIDITE SPECIFIQUE DU THERMOMETRE MOUILLE.
  ! PR         : CONSTANTE DES GAZ POUR L'AIR.
  ! PT         : TEMPERATURE.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS DE SORTIE.
  !     --------------------
  
  ! - 2D (0:KLEV) .
  
  ! PFPEVPL    : EVAPORATION DES PRECIPITATIONS LIQUIDES.
  ! PFPEVPN    : EVAPORATION DES PRECIPITATIONS NEIGEUSES.
  ! PFPFPL     : GENERATION DES PRECIPITATIONS LIQUIDES.
  ! PFPFPN     : GENERATION DES PRECIPITATIONS NEIGEUSES.
  ! PFPLSL     : PRECIPITATIONS STRATIFORMES SOUS FORME LIQUIDE.
  ! PFPLSN     : PRECIPITATIONS STRATIFORMES SOUS FORME NEIGE.
  ! PFCSQL     : STRATIFORM CONDENSATION (LIQUID)
  ! PFCSQN     : STRATIFORM CONDENSATION (SOLID)
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS IMPLICITES.
  !     ---------------------
  
  !-----------------------------------------------------------------------
  
  !     Externes.
  !     ---------
  
  !     Methode.
  !     --------
  !        A SCHEME FOR PREDICTING LAYER CLOUDS AND THEIR WATER CONTENT
  !        IN A GENERAL CIRCULATION MODEL BY SMITH (1990).
  !        IF THE SPECIFIC HUMIDITY IS TOO WEAK (PQ<QSMIN) A MODIFIED
  !        KESSLER'S SCHEME IS USED.
  !     Auteurs.
  !     -------
  !        92-01-17, CHRISTIAN CASTEJON ET ELISABETH GERARD.
  
  !     Modifications.
  !     --------------
  !        02-10, Flux d'vaporation des precip LCONDWT - J.F. Gueremy
  !        M.Hamrud      01-Oct-2003 CY28 Cleaning
  !        04-01, ZINEBGY, ZIWTNEBGY - J.F. Gueremy/P. Marquet
  !        04-03, retour ariere sur la modif - J.F. Gueremy/P. Marquet
  !               du 00-10 (proportion solide des precipitations...)
  !        04-10, Flux de fonte/gel des precip LCONDWT - J.F. Gueremy
  !        05-03, Sommes des flux de fonte/gel et d'vap strat et conv
  !               effectues dans aplpar - J.F. Gueremy
  !        05-03, Change due to Lopez microphysics - F. Bouyssel
  !        06-07, Mise en conformite des flux pour la nouv interface
  !               PFPEVP (evap) et PFPFP(generation)
  !        K. Yessad (Jul 2009): remove CDLOCK + some cleanings
  !        2011-06: M. Jerczynski - some cleaning to meet norms
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( ACPLUIS_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
  REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PNEBS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQLIS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQW(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PR(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PT(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPEVPL(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPEVPN(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPFPL(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPFPN(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPLSL(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFPLSN(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCSQL(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCSQN(KLON, 0:KLEV)
  
  !-----------------------------------------------------------------------
  
  REAL(KIND=JPRB) :: ZNEIGE
  REAL(KIND=JPRB) :: ZPLH
  REAL(KIND=JPRB) :: ZRME
  temp (REAL (KIND=JPRB), ZFONTE, (KLON, KLEV))
  
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPRB) :: ZCLTEND
  REAL(KIND=JPRB) :: ZDELTAQ
  REAL(KIND=JPRB) :: ZEPS
  REAL(KIND=JPRB) :: ZEPS1
  REAL(KIND=JPRB) :: ZEPS2
  REAL(KIND=JPRB) :: ZEVA
  REAL(KIND=JPRB) :: ZFON
  REAL(KIND=JPRB) :: ZFONS
  REAL(KIND=JPRB) :: ZFONT
  REAL(KIND=JPRB) :: ZGENE
  REAL(KIND=JPRB) :: ZGENN
  REAL(KIND=JPRB) :: ZH
  REAL(KIND=JPRB) :: ZHE
  REAL(KIND=JPRB) :: ZIFNSAT
  REAL(KIND=JPRB) :: ZIFSAT
  REAL(KIND=JPRB) :: ZINDQ
  REAL(KIND=JPRB) :: ZNEBS
  REAL(KIND=JPRB) :: ZNUTEND
  REAL(KIND=JPRB) :: ZPLB
  REAL(KIND=JPRB) :: ZPLBK
  REAL(KIND=JPRB) :: ZPLBS
  REAL(KIND=JPRB) :: ZPLC
  REAL(KIND=JPRB) :: ZPLS
  REAL(KIND=JPRB) :: ZQL
  REAL(KIND=JPRB) :: ZQLL
  REAL(KIND=JPRB) :: ZQLI
  REAL(KIND=JPRB) :: ZRPTB
  REAL(KIND=JPRB) :: ZRPTH
  REAL(KIND=JPRB) :: ZTENDCL
  REAL(KIND=JPRB) :: ZTENDI
  REAL(KIND=JPRB) :: ZTENDL
  REAL(KIND=JPRB) :: ZTENDNU
  REAL(KIND=JPRB) :: ZTENDT
  REAL(KIND=JPRB) :: ZTVF
  REAL(KIND=JPRB) :: ZZA
  REAL(KIND=JPRB) :: ZZB
  REAL(KIND=JPRB) :: ZZC
  REAL(KIND=JPRB) :: ZINEBGY
  REAL(KIND=JPRB) :: ZIWTNEBGY
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  !-----------------------------------------------------------------------
  
#include "fctdoi.func.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  IF (KIND (ZFONTE) == 8) THEN
    alloc8 (ZFONTE)
  ELSE
    IF (KIND (ZFONTE) == 4) THEN
      alloc4 (ZFONTE)
    ELSE
      STOP 1
    END IF
  END IF
  JLON = KIDIA
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  
  !*
  !     ------------------------------------------------------------------
  !     I - CONSTANTES DE SECURITE.
  
  !         SECURITY CONSTANTS.
  
  ZEPS = 1.E-5_JPRB
  ZEPS1 = 1.E-10_JPRB
  ZEPS2 = 1.E-5_JPRB
  
  IF (YDML_PHY_MF%YRPHY%LNEBGY) THEN
    ZINEBGY = 1.0_JPRB
  ELSE
    ZINEBGY = 0.0_JPRB
  END IF
  
  IF (YDML_PHY_MF%YRPHY%LCONDWT .and. YDML_PHY_MF%YRPHY%LNEBGY) THEN
    ZIWTNEBGY = 1.0_JPRB
  ELSE
    ZIWTNEBGY = 0.0_JPRB
  END IF
  
  !*
  !     ------------------------------------------------------------------
  !     II - DEBUT DES BOUCLES VERTICALE ET HORIZONTALE OU L'INFORMATION
  !     SE TRANSMET DE COUCHE EN COUCHE, DU HAUT VERS LE BAS.
  !     MISES A ZERO DU FLUX DE PRECIPITATIONS ET DE LA PROPORTION DE
  !     NEIGE AU SOMMET.
  
  !          BEGINNING OF THE VERTICAL AND HORIZONTAL LOOPS WHERE THE
  !     INFORMATION IS PASSED FROM LAYER TO LAYER DOWNWARDS.
  !     INITIALISATION OF THE PRECIPITATION FLUX AND THE SNOW PROPORTION
  !     AT THE TOP.
  
  ! - TEMPORAIRES 1D .
  
  ! ZNEIGE    : PROPORTION DU FLUX DE PRECIPITATIONS SOUS FORME NEIGE.
  !            : SNOW-TYPE PROPORTION OF THE PRECIPITATION FLUX.
  ! ZPLH      : FLUX TOTAL DE PRECIPITATIONS AU SOMMET DE LA COUCHE.
  !            : TOTAL PRECIPITATION FLUX AT THE TOP OF THE LAYER.
  ! ZRME      : MEME TYPE DE VARIABLE QUE ZNEIGE; INTEGRE EN PLUS UNE
  !              TRANSITION DE PHASE CONTINUE.
  !            : SAME TYPE OF VARIABLE AS ZNEIGE; ON TOP OF THAT IT
  !              INTEGRATES A CONTINUOUS TRANSITION BETWEEN ICE AND
  !              LIQUID WATER.
  
  DO JLEV=KTDIA,KLEV
    !DEC$ IVDEP
    
    IF (JLEV == KTDIA) THEN
      ZPLH = 0.0_JPRB
      ZNEIGE = 0.0_JPRB
      ZRME = 0.0_JPRB
    END IF
    
    IF (YDML_PHY_MF%YRPHY%LNEIGE) THEN
      ZH = MAX(0.0_JPRB, SIGN(1.0_JPRB, YDCST%RTT - PT(JLON, JLEV)))
    ELSE
      ZH = 0.0_JPRB
    END IF
    !*
    !     ------------------------------------------------------------------
    !     III - TRAITEMENT DE LA PARTIE NON SATUREE DE LA MAILLE -
    !     PROCESSUS D'EVAPORATION.
    
    !           PROCESSING OF THE NON SATURATED PART OF THE GRID -
    !     EVAPORATION PROCESS.
    
    ZNEBS = MAX(0.0_JPRB, SIGN(1.0_JPRB, 1.0_JPRB - PNEBS(JLON, JLEV) - ZEPS))
    ZIFNSAT = ZNEBS*(1.0_JPRB - PNEBS(JLON, JLEV)) + (1.0_JPRB - ZNEBS)*ZEPS
    ZIFNSAT = 1.0_JPRB / ZIFNSAT
    ZDELTAQ = PQW(JLON, JLEV) - PQ(JLON, JLEV)
    ZEVA = YDML_PHY_MF%YRPHY0%EVAP*(1.0_JPRB - ZRME*(1.0_JPRB - YDML_PHY_MF%YRPHY0%REVGSL))
    ZPLC = SQRT(ZPLH) - ZEVA*MAX(ZDELTAQ, 0.0_JPRB)*PDELP(JLON, JLEV) / PAPRSF(JLON, JLEV)**2
    ZPLC = MAX(ZPLC, 0.0_JPRB)
    ZPLC = ZPLC**2
    ZCLTEND = (ZPLC - ZPLH)*YDCST%RG / PDELP(JLON, JLEV)
    ZTENDCL = ZCLTEND*(1.0_JPRB - PNEBS(JLON, JLEV))
    ZTENDCL = -MIN(ABS(ZDELTAQ / YDML_PHY_MF%YRPHY2%TSPHY), -ZTENDCL)
    PFPEVPL(JLON, JLEV) = ZTENDCL*PDELP(JLON, JLEV) / YDCST%RG
    PFPEVPN(JLON, JLEV) = ZIWTNEBGY*(PFPEVPN(JLON, JLEV - 1) + ZH*PFPEVPL(JLON, JLEV))
    PFPEVPL(JLON, JLEV) = ZIWTNEBGY*(PFPEVPL(JLON, JLEV - 1) + (1.0_JPRB - ZH)*PFPEVPL(JLON, JLEV))
    ZCLTEND = ZTENDCL*ZIFNSAT
    ZPLC = MAX(0.0_JPRB, ZCLTEND*PDELP(JLON, JLEV) / YDCST%RG + ZPLH)
    
    !*
    !     ------------------------------------------------------------------
    !     IV - TRAITEMENT DE LA PARTIE SATUREE DE LA MAILLE -
    !     PROCESSUS DE CONDENSATION.
    
    !          PROCESSING OF THE SATURATED PART OF THE GRID -
    !     CONDENSATION PROCESS.
    
    !   PHASE LIQUIDE.
    !   LIQUID PHASE.
    
    ZIFSAT = 1.0_JPRB / PNEBS(JLON, JLEV)
    ZNEBS = MAX(0.0_JPRB, SIGN(1.0_JPRB, PNEBS(JLON, JLEV) - ZEPS))
    ZQL = ZNEBS*PQLIS(JLON, JLEV)*ZIFSAT
    ZQLL = ZQL*(1.0_JPRB - ZH)
    ZZA =  &
    & YDML_PHY_MF%YRPHY0%TCT*MAX(0.0_JPRB, 1.0_JPRB - EXP(-ZQLL**2 / YDML_PHY_MF%YRPHY0%TCW**2)) + YDML_PHY_MF%YRPHY0%TCA*ZPLH
    ZTENDL = ZZA*ZQLL / (1.0_JPRB + YDML_PHY_MF%YRPHY2%TSPHY*ZZA)
    
    !   PHASE GLACE.
    !   ICE PHASE.
    
    IF (YDML_PHY_MF%YRPHY%LNEIGE) THEN
      ZQLI = ZQL*ZH
      ZTVF = YDML_PHY_MF%YRPHY0%TVF*(ZINEBGY*(ZQLI*1000._JPRB)**0.2_JPRB + (1.0_JPRB - ZINEBGY))
      ZZB = YDCST%RG / PDELP(JLON, JLEV)*ZPLH
      ZZC = YDCST%RG / PDELP(JLON, JLEV)*PAPRSF(JLON, JLEV)*ZTVF / PR(JLON, JLEV) / PT(JLON, JLEV)
      ZTENDI = -MIN(0.0_JPRB, ZZB - ZZC*ZQLI) / (1.0_JPRB + YDML_PHY_MF%YRPHY2%TSPHY*ZZC)
    ELSE
      ZTENDI = 0.0_JPRB
    END IF
    
    ! - TENDANCE D'HUMIDITE DUE A LA CONDENSATION.
    
    ZNUTEND = ZTENDI + ZTENDL
    ZTENDNU = ZNUTEND*PNEBS(JLON, JLEV)
    ZTENDNU =  &
    & ZINEBGY*ZTENDNU + (1.0_JPRB - ZINEBGY)*MAX(0.0_JPRB, MIN(ZTENDNU, PQ(JLON, JLEV) / (2.0_JPRB*YDML_PHY_MF%YRPHY2%TSPHY)))
    ZNUTEND = ZTENDNU*ZIFSAT
    ZPLS = ZNUTEND*PDELP(JLON, JLEV) / YDCST%RG + ZPLH
    
    !*
    !     ------------------------------------------------------------------
    !     V - CALCUL DU FLUX TOTAL DE PRECIPITATIONS A LA BASE DE LA COUCHE.
    
    !         COMPUTATION OF THE TOTAL PRECIPITATION FLUX AT THE BOTTOM OF
    !     THE LAYER.
    
    ! - SMITH'S SCHEME IF PQ(JLON,JLEV)>QSMIN.
    
    ZPLBS = PNEBS(JLON, JLEV)*ZPLS + (1.0_JPRB - PNEBS(JLON, JLEV))*ZPLC
    
    ! - KESSLER'S SCHEME IF PQ(JLON,JLEV)<QSMIN.
    
    ZDELTAQ = PQW(JLON, JLEV) - PQ(JLON, JLEV)
    ZPLBK = MAX(0.0_JPRB, ZPLH - ZDELTAQ*PDELP(JLON, JLEV) / (YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY))
    ZRPTH = SQRT(MAX(ZPLH, ZPLBK))
    ZRPTB = MAX(0.0_JPRB, ZRPTH - ZEVA*MAX(0.0_JPRB, ZDELTAQ)*PDELP(JLON, JLEV) / PAPRSF(JLON, JLEV)**2)
    ZPLBK = MAX(ZPLBK, ZRPTB**2)
    
    ! - FLUX TOTAL DE PRECIPITATIONS A LA BASE DE LA COUCHE.
    
    ZINDQ = MAX(0.0_JPRB, SIGN(1.0_JPRB, PQ(JLON, JLEV) - YDML_PHY_MF%YRPHY0%QSMIN))
    !    ZPLB = ZPLBS*ZINDQ + ZPLBK*(_ONE_-ZINDQ)
    ZPLB = ZPLBS
    
    !*
    !     ------------------------------------------------------------------
    !     VI - CALCULS DE CHANGEMENT DE LA PROPORTION NEIGEUSE (NOUVELLES
    !     PRECIPITATIONS GENEREES ET FONTE OU GEL) DANS L'OPTION "NEIGE".
    
    !          COMPUTATIONS OF THE CHANGE IN THE SNOW PROPORTION (NEWLY
    !     GENERATED PRECIPITATIONS AND MELTING OR FREEZING IN THE SNOW".
    !     OPTION "NEIGE").
    
    IF (YDML_PHY_MF%YRPHY%LNEIGE) THEN
      ZGENN = (ZNEIGE*ZPLH + ZH*ZTENDNU*PDELP(JLON, JLEV) / YDCST%RG) / MAX(ZEPS1, (ZPLH + ZTENDNU*PDELP(JLON, JLEV) / YDCST%RG))
      ZHE = FONICE(PT(JLON, JLEV), YDML_PHY_MF%YRPHY0%RDTFAC)
      ZGENE = (ZRME*ZPLH + ZHE*ZTENDNU*PDELP(JLON, JLEV) / YDCST%RG) / MAX(ZEPS1, (ZPLH + ZTENDNU*PDELP(JLON, JLEV) / YDCST%RG))
      ZFONT = YDML_PHY_MF%YRPHY0%FONT*(1.0_JPRB - ZRME*(1.0_JPRB - YDML_PHY_MF%YRPHY0%REVGSL))
      ZFON = -2.0_JPRB*ZFONT*(PT(JLON, JLEV) - YDCST%RTT)*PDELP(JLON, JLEV) / PAPRSF(JLON, JLEV)**2 / MAX(ZEPS2, SQRT(ZPLB) +  &
      & SQRT(ZPLH))
      ZFONS = MAX(0.0_JPRB, MIN(1.0_JPRB, PNEBS(JLON, JLEV)*ZGENN + (1.0_JPRB - PNEBS(JLON, JLEV))*ZNEIGE))
      ZNEIGE = MAX(0.0_JPRB, MIN(1.0_JPRB, PNEBS(JLON, JLEV)*ZGENN + (1.0_JPRB - PNEBS(JLON, JLEV))*ZNEIGE + ZFON))
      ZFONS = ZNEIGE - ZFONS
      ZRME = MAX(0.0_JPRB, MIN(1.0_JPRB, PNEBS(JLON, JLEV)*ZGENE + (1.0_JPRB - PNEBS(JLON, JLEV))*ZRME + ZFON))
    ELSE
      ZNEIGE = 0.0_JPRB
      ZRME = 0.0_JPRB
      ZFONS = 0.0_JPRB
    END IF
    
    !*
    !     ------------------------------------------------------------------
    !     VII - CALCUL DES FLUX DE PRECIPITATIONS A CHAQUE NIVEAU, SOUS
    !     FORME LIQUIDE OU NEIGEUSE.
    
    !           COMPUTATION OF THE PRECIPITATION FLUXES AT EACH LEVEL
    !     (WATER AND SNOW).
    
    ZTENDT = ZTENDNU + ZTENDCL
    ZPLH = MAX(0.0_JPRB, ZPLH + ZTENDT*PDELP(JLON, JLEV) / YDCST%RG)
    PFPLSL(JLON, JLEV) = (1.0_JPRB - ZNEIGE)*ZPLH
    PFPLSN(JLON, JLEV) = ZNEIGE*ZPLH
    PFPFPL(JLON, JLEV) = PFPLSL(JLON, JLEV) - PFPEVPL(JLON, JLEV)
    PFPFPN(JLON, JLEV) = PFPLSN(JLON, JLEV) - PFPEVPN(JLON, JLEV)
    PFCSQL(JLON, JLEV) = PFPLSL(JLON, JLEV)
    PFCSQN(JLON, JLEV) = PFPLSN(JLON, JLEV)
    !     Flux de fonte
    ZFONTE(JLON, JLEV) = ZIWTNEBGY*ZFONS*ZPLH
    
  END DO
  
  !!!   le flux d'evaporation comprend le flux de fonte
  !!!   changement de signe des flux PFPEVPL/N (temporaire)
  DO JLEV=KTDIA,KLEV
    PFPEVPL(JLON, JLEV) = -(PFPEVPL(JLON, JLEV) - ZFONTE(JLON, JLEV))
    PFPEVPN(JLON, JLEV) = -(PFPEVPN(JLON, JLEV) + ZFONTE(JLON, JLEV))
  END DO
  
  !-----------------------------------------------------------------------
END SUBROUTINE ACPLUIS_OPENACC
