SUBROUTINE MF_PHYS_PRECIPS_OPENACC (YDCPG_BNDS, YDCPG_OPTS, PPRC_DPRECIPS, PPRC_DPRECIPS2, PGSD_XP_PPRECIP, PGSD_XP2_PPRECIP2,  &
& YDMODEL, YDSTACK)
  
!$acc routine( MF_PHYS_PRECIPS_OPENACC ) seq
  
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE PARKIND1, ONLY: JPIM, JPRB
  
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  REAL(KIND=JPRB), INTENT(IN) :: PPRC_DPRECIPS(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
  REAL(KIND=JPRB), INTENT(IN) :: PPRC_DPRECIPS2(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
  REAL(KIND=JPRB), INTENT(OUT) :: PGSD_XP_PPRECIP(YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XPD%NLEVS)
  REAL(KIND=JPRB), INTENT(OUT) :: PGSD_XP2_PPRECIP2(YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XP2D%NLEVS)
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = YDCPG_BNDS%KIDIA
  
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
    PGSD_XP_PPRECIP(JLON, YDCPG_OPTS%NDTPRECCUR) = PPRC_DPRECIPS(JLON, YDCPG_OPTS%NDTPRECCUR)
  END IF
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
    PGSD_XP2_PPRECIP2(JLON, YDCPG_OPTS%NDTPRECCUR2) = PPRC_DPRECIPS2(JLON, YDCPG_OPTS%NDTPRECCUR2)
  END IF
  
  
END SUBROUTINE MF_PHYS_PRECIPS_OPENACC
