SUBROUTINE ACUPTQ_OPENACC (YDCST, KLON, KIDIA, KFDIA, KFLEV, KNBTRA, LDPTQ, PFRSO, PFRTH, PDIFCQ, PDIFCS, PDIFTQ, PDIFTS,  &
& PFCCQL, PFCCQN, PFPLCL, PFPLCN, PFECL, PFECN, PFACL, PFACN, PRDELP, PT, PQ, PTS, PTENDH, PTENDQ, PDIFTTRA, PTENTRA_STR, YDSTACK &
& )
  
  !     ------------------------------------------------------------------
  !     EVOLUTION DE (T,Qv) APRES TURBULENCE ET CONVECTION
  !     ------------------------------------------------------------------
  
  !     ARGUMENTS D ENTREE
  !     ------------------
  ! KLON       : DIMENSION HORIZONTALE
  ! KIDIA      : DEBUT DE LA BOUCLE HORIZONTALE
  ! KFDIA      : BORNE HORIZONTALE DES CALCULS
  ! KFLEV      : DIMENSION ET BORNE VERTICALE
  ! KNBTRA     : NOMBRE DE TRACEURS (SCALAIRES PASSIFS, AEROSOL, ESPECES CHIMIQUES)
  
  ! --- INPUT 2D (0:KLEV).
  !     -----------------.
  ! PFRSO      : SOLAR FLUX
  ! PFRTH      : THERMAL FLUX
  ! PDIFCQ     : FLUX CONVECTIF D'HUMIDITE SPECIFIQUE (HORS COND. ET RR).
  ! PDIFCS     : FLUX CONVECTIF D'ENTHALPIE .
  ! PDIFTQ     : FLUX TURBULENT (ET Q NEGATIF) D'HUMIDITE SPECIFIQUE.
  ! PDIFTS     : FLUX TURBULENT D'ENTHALPIE (OU D'ENERGIE STATIQUE SECHE).
  ! PDIFTTRA   : FLUX TURBULENT DES TRACEURS (SCALAIRES PASSIFS, AEROSOL, ESPECES CHIMIQUES).
  ! PFCCQL     : FLUX DE CONDENSATION LIE AUX RR CONVECTIVES LIQUIDES.
  ! PFCCQN     : FLUX DE CONDENSATION LIE AUX RR CONVECTIVES NEIGEUSES.
  ! PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
  ! PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.
  ! PFECL      : FLUX DE PRECIPITATIONS DU A L'EVAPORATION CONVECTIVE.
  ! PFECN      : FLUX DE PRECIPITATIONS DU A LA SUBLIMATION CONVECTIVE.
  ! PFACL      : FLUX DE PRECIPITATION CONVECTIVE: TERME DE GENERATION/FORMATION.
  ! PFACN      : FLUX DE PRECIPITATION CONVECTIVE: TERME DE GENERATION/FORMATION.
  
  ! --- INPUT 2D (1:KLEV).
  !     -----------------.
  ! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PT         : TEMPERATURE.
  ! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
  
  ! - 1D.
  !   --.
  ! PTS        : TEMPERATURE DE SURFACE.
  
  ! --- SORTIES 2D (1:KFLEV).
  !     --------------------.
  ! PTENDH     : TENDANCE DE L'ENTHALPIE.
  ! PTENDQ     : TENDANCE DE L'HUMIDITE.
  
  ! --- SORTIES 3D (KPROMA,1:KFLEV,KNBTRA).
  !     ---------------------------------.
  ! PTENTRA_STR : TENDANCES DES TRACEURS, tendances calculees avec sorties de acdifv2, donc dans le cas
  !              de convection Tiedtke les tendances sont calculées à partir de flux turbulents uniquement. PTENTRA_STR INOUT de CUCALLN_MF
  
  ! --- AUTEUR.
  !     ------.
  !     25/10/10 F.BOUYSSEL.
  
  ! --- MODIFICATION.
  !     ------------.
  !     10/07/19 Y.BOUTELOUP : Add PFRSO and PFRTH for Tiedtke/Bechtold scheme
  !     M. Michou & M. Cussac : Add tracers tendency calculation before convection
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( ACUPTQ_OPENACC ) seq
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KNBTRA
  LOGICAL, INTENT(IN) :: LDPTQ
  REAL(KIND=JPRB), INTENT(IN) :: PFRSO(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRTH(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCS(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTS(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCCQL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCCQN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLCL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLCN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFECL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFECN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFACL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFACN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PRDELP(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PT(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PTS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDH(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQ(KLON, KFLEV)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PDIFTTRA(KLON, 0:KFLEV, KNBTRA)
  REAL(KIND=JPRB), OPTIONAL, INTENT(OUT) :: PTENTRA_STR(KLON, KFLEV, KNBTRA)
  !-----------------------------------------------------------------------
  
  temp (REAL (KIND=JPRB), ZGSDP, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZJTOT, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZTI, (KLON, 0:KFLEV))
  
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JTRA
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KIDIA
  YLSTACK = YDSTACK
  IF (KIND (ZGSDP) == 8) THEN
    alloc8 (ZGSDP)
  ELSE
    IF (KIND (ZGSDP) == 4) THEN
      alloc4 (ZGSDP)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZJTOT) == 8) THEN
    alloc8 (ZJTOT)
  ELSE
    IF (KIND (ZJTOT) == 4) THEN
      alloc4 (ZJTOT)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZTI) == 8) THEN
    alloc8 (ZTI)
  ELSE
    IF (KIND (ZTI) == 4) THEN
      alloc4 (ZTI)
    ELSE
      STOP 1
    END IF
  END IF
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  
  ! Calculation of temperatures on half levels
  
  ZTI(JLON, 0) = PT(JLON, 1)
  ZTI(JLON, KFLEV) = PTS(JLON)
  
  DO JLEV=1,KFLEV - 1
    ZTI(JLON, JLEV) = (PT(JLON, JLEV) + PT(JLON, JLEV + 1))*0.5_JPRB
  END DO
  
  ! Computation of the total enthalpy flux J_tot
  
  DO JLEV=0,KFLEV
    IF (LDPTQ) THEN
      ZJTOT(JLON, JLEV) = PFRSO(JLON, JLEV) + PFRTH(JLON, JLEV) + PDIFTS(JLON, JLEV) + PDIFCS(JLON, JLEV) + (YDCST%RCW -  &
      & YDCST%RCPD)*PFPLCL(JLON, JLEV)*ZTI(JLON, JLEV) + (YDCST%RCS - YDCST%RCPD)*PFPLCN(JLON, JLEV)*ZTI(JLON, JLEV) -  &
      & YDCST%RLVZER*(PFCCQL(JLON, JLEV) - PFECL(JLON, JLEV)) - YDCST%RLSZER*(PFCCQN(JLON, JLEV) - PFECN(JLON, JLEV))
    ELSE
      ZJTOT(JLON, JLEV) = PFRSO(JLON, JLEV) + PFRTH(JLON, JLEV) + PDIFTS(JLON, JLEV)
    END IF
  END DO
  
  !CDIR UNROLL=8
  DO JLEV=1,KFLEV
    
    ZGSDP(JLON, JLEV) = YDCST%RG*PRDELP(JLON, JLEV)
    
    IF (LDPTQ) THEN
      PTENDQ(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQ(JLON, JLEV - 1) - PDIFTQ(JLON, JLEV)) + (PDIFCQ(JLON, JLEV - 1) -  &
      & PDIFCQ(JLON, JLEV)) + (PFCCQL(JLON, JLEV - 1) - PFCCQL(JLON, JLEV)) + (PFCCQN(JLON, JLEV - 1) - PFCCQN(JLON, JLEV)) -  &
      & (PFECL(JLON, JLEV - 1) - PFECL(JLON, JLEV)) - (PFECN(JLON, JLEV - 1) - PFECN(JLON, JLEV)))
      PTENDH(JLON, JLEV) = ZGSDP(JLON, JLEV)*(ZJTOT(JLON, JLEV - 1) - ZJTOT(JLON, JLEV))
    ELSE
      PTENDQ(JLON, JLEV) = MAX(0._JPRB, ZGSDP(JLON, JLEV)*(PDIFTQ(JLON, JLEV - 1) - PDIFTQ(JLON, JLEV)))
      PTENDH(JLON, JLEV) = MAX(0._JPRB, ZGSDP(JLON, JLEV)*(ZJTOT(JLON, JLEV - 1) - ZJTOT(JLON, JLEV)))
    END IF
    
  END DO
  
  IF (KNBTRA > 0) THEN
    IF (.not.LDPTQ) THEN
      ! LDPTQ case specific to PNT not used in climate
      DO JLEV=1,KFLEV
        ZGSDP(JLON, JLEV) = YDCST%RG*PRDELP(JLON, JLEV)
        DO JTRA=1,KNBTRA
          PTENTRA_STR(JLON, JLEV, JTRA) = ZGSDP(JLON, JLEV)*(PDIFTTRA(JLON, JLEV - 1, JTRA) - PDIFTTRA(JLON, JLEV, JTRA))
        END DO
      END DO
    END IF
  END IF
  
  !-----------------------------------------------------------------------
END SUBROUTINE ACUPTQ_OPENACC
