SUBROUTINE MEANWIND_XFU_OPENACC (KLON, KIDIA, KFDIA, KMEANSTEPS, PXFU, PXFV, PXU, PXV, PMWINDCALC, ZUM, ZVM, YDSTACK)
  
!$acc routine( MEANWIND_XFU_OPENACC )
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: DR_HOOK, LHOOK, JPHOOK
  
  ! The algorithm is the same as the one used to compute observed mean wind
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KMEANSTEPS
  REAL(KIND=JPRB), INTENT(IN) :: PXFU(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PXFV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PXU(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PXV(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PMWINDCALC(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: ZUM(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: ZVM(KLON)
  
  REAL(KIND=JPRB) :: ZMEANMODULE
  REAL(KIND=JPRB) :: ZMEANANGLE
  REAL(KIND=JPRB) :: ZANGLE
  REAL(KIND=JPRB) :: ZMEANCANGLE
  REAL(KIND=JPRB) :: ZMEANSANGLE
  REAL(KIND=JPRB), PARAMETER :: ZEPS = 1.E-12_JPRB
  
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KIDIA
  
  
  IF (KMEANSTEPS == 1) THEN
    ZUM(JLON) = PXU(JLON)
    ZVM(JLON) = PXV(JLON)
    PMWINDCALC(JLON) = 1.0_JPRB
  ELSE
    ! Module of mean wind is the mean of the modules
    ZMEANMODULE = SQRT(PXFU(JLON)**2 + PXFV(JLON)**2)
    ! Module of mean wind is the mean of the modules
    ZMEANMODULE = ZMEANMODULE*REAL(KMEANSTEPS - 1, kind=JPRB) + SQRT(PXU(JLON)**2 + PXV(JLON)**2)
    ! We compute mean of COS and mean of SIN
    ! Direction of mean wind is the direction of vector [mean COS, mean SIN]
    IF (ABS(PXFV(JLON)) < ZEPS .and. ABS(PXFU(JLON)) < ZEPS) THEN
      ZMEANANGLE = 0.0_JPRB
    ELSE
      ZMEANANGLE = ATAN2(PXFV(JLON), PXFU(JLON))
    END IF
    IF (ABS(PXV(JLON)) < ZEPS .and. ABS(PXU(JLON)) < ZEPS) THEN
      ZANGLE = 0.0_JPRB
    ELSE
      ZANGLE = ATAN2(PXV(JLON), PXU(JLON))
    END IF
    ZMEANCANGLE = (COS(ZMEANANGLE)*REAL(KMEANSTEPS - 1, kind=JPRB)*PMWINDCALC(JLON) + COS(ZANGLE)) / REAL(KMEANSTEPS, kind=JPRB)
    ZMEANSANGLE = (SIN(ZMEANANGLE)*REAL(KMEANSTEPS - 1, kind=JPRB)*PMWINDCALC(JLON) + SIN(ZANGLE)) / REAL(KMEANSTEPS, kind=JPRB)
    PMWINDCALC(JLON) = SQRT(ZMEANCANGLE**2 + ZMEANSANGLE**2)
    IF (ABS(ZMEANSANGLE) < ZEPS .and. ABS(ZMEANCANGLE) < ZEPS) THEN
      ZMEANANGLE = 0.0_JPRB
    ELSE
      ZMEANANGLE = ATAN2(ZMEANSANGLE, ZMEANCANGLE)
    END IF
    ZUM(JLON) = ZMEANMODULE*COS(ZMEANANGLE) / REAL(KMEANSTEPS, kind=JPRB)
    ZVM(JLON) = ZMEANMODULE*SIN(ZMEANANGLE) / REAL(KMEANSTEPS, kind=JPRB)
  END IF
  
  
END SUBROUTINE MEANWIND_XFU_OPENACC
