INTERFACE
  SUBROUTINE GPGRGEO_EXPL_OPENACC (YDGEOMETRY, KPROMA, KST, KEND, KFLEV, PRT, PRTL, PRTM, PLNPR, PALPH, POROGL, POROGM, PHIFL,  &
  & PHIFM, PHIHL, PHIHM, LDNHEE, PRNHPPI, PQCHAL, PQCHAM, PNH1L, PNH1M, PLNPRL_DER, PLNPRM_DER, PALPHL_DER, PALPHM_DER, YDSTACK)
!$acc routine( GPGRGEO_EXPL_OPENACC )
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, JPHOOK, DR_HOOK
    
    USE GEOMETRY_MOD, ONLY: GEOMETRY
    
    
    
    !     ------------------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
    INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
    INTEGER(KIND=JPIM), INTENT(IN) :: KST
    INTEGER(KIND=JPIM), INTENT(IN) :: KEND
    INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
    REAL(KIND=JPRB), INTENT(IN) :: PRT(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PRTL(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PRTM(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PLNPR(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PALPH(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: POROGL(KPROMA)
    REAL(KIND=JPRB), INTENT(IN) :: POROGM(KPROMA)
    REAL(KIND=JPRB), INTENT(OUT) :: PHIFL(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PHIFM(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PHIHL(KPROMA, 0:KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PHIHM(KPROMA, 0:KFLEV)
    LOGICAL, OPTIONAL, INTENT(IN) :: LDNHEE
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PRNHPPI(KPROMA, KFLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PQCHAL(KPROMA, KFLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PQCHAM(KPROMA, KFLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(OUT) :: PNH1L(KPROMA, KFLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(OUT) :: PNH1M(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PLNPRL_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PLNPRM_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PALPHL_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PALPHM_DER(KPROMA, KFLEV)
    
    !     ------------------------------------------------------------------
    
    
    
    !     ------------------------------------------------------------------
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE GPGRGEO_EXPL_OPENACC
END INTERFACE
