SUBROUTINE GPINISLB_PART1_EXPL_OPENACC (YDGEOMETRY, YGFL, YDDYN, YDDYNA, KST, KEND, PTE, PUT9, PVT9, PTT9, PSPDT9, PSVDT9,  &
& PNHX9, PSPT9, PB2U1, PB2V1, PB2T1, PB2PD1, PB2VD1, PGMVNHX1, PB2SP1, PQICE, PQLI, PQRAIN, PQSNOW, PQGRAUPEL, PL0, PL9, PI0,  &
& PI9, PR0, PR9, PS0, PS9, PG0, PG9, YDSTACK)
  
  !**** *GPINISLB_PART1_EXPL*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-11-2022
  
!$acc routine( GPINISLB_PART1_EXPL_OPENACC )
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: DR_HOOK, LHOOK, JPHOOK
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  USE YOM_YGFL, ONLY: TYPE_GFLD
  USE YOMDYN, ONLY: TDYN
  USE YOMDYNA, ONLY: TDYNA
  
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(TYPE_GFLD), INTENT(IN) :: YGFL
  TYPE(TDYN), INTENT(IN) :: YDDYN
  TYPE(TDYNA), INTENT(IN) :: YDDYNA
  INTEGER(KIND=JPIM), INTENT(IN) :: KST
  INTEGER(KIND=JPIM), INTENT(IN) :: KEND
  REAL(KIND=JPRB), INTENT(IN) :: PTE
  REAL(KIND=JPRB), INTENT(IN) :: PUT9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PVT9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PTT9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PSPDT9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PSVDT9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PNHX9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PSPT9(YDGEOMETRY%YRDIM%NPROMA)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2U1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2V1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2T1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2PD1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2VD1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PGMVNHX1(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PB2SP1(YDGEOMETRY%YRDIM%NPROMA)
  REAL(KIND=JPRB), INTENT(OUT) :: PQICE(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PQLI(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PQRAIN(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PQSNOW(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(OUT) :: PQGRAUPEL(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PL0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PL9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PI0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PI9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PR0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PR9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PS0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PS9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PG0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PG9(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KST
  
  
  !*          1.     PB2[X]1 for prognostic variables.
  !                  ---------------------------------
  
  !*          1.1    PB2[X]1 for GMV variables (U,V,T,NH variables).
  
  IF (YDDYNA%LSLAG) THEN
    PB2U1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
    PB2V1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
    PB2T1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
    IF (YDDYNA%LNHDYN) THEN
      PB2PD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      PB2VD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      IF (YDDYNA%LNHX) PGMVNHX1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
    END IF
  ELSE
    !Eulerian
    IF (YDDYN%NCURRENT_ITER == 0) THEN
      PB2U1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PUT9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
      PB2V1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PVT9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
      PB2T1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PTT9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
      IF (YDDYNA%LNHDYN) THEN
        PB2PD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PSPDT9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
        PB2VD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PSVDT9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
        IF (YDDYNA%LNHX) PGMVNHX1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PNHX9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)*PTE
      END IF
    ELSE
      PB2U1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      PB2V1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      PB2T1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      IF (YDDYNA%LNHDYN) THEN
        PB2PD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
        PB2VD1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
        IF (YDDYNA%LNHX) PGMVNHX1(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
      END IF
    END IF
  END IF
  
  !*          1.2    PB2[X]1 for GFL variables, and also PQLI, PQICE.
  
  ! input for MF_PHYS and CPG_DIA (useless if NCURRENT_ITER>0).
  IF (YGFL%YL%LACTIVE) THEN
    IF (YDDYNA%LSLAG .and. YDDYNA%LTWOTL) THEN
      PQLI(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PL0(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    ELSE
      PQLI(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PL9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    END IF
  ELSE
    PQLI(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
  END IF
  IF (YGFL%YI%LACTIVE) THEN
    IF (YDDYNA%LSLAG .and. YDDYNA%LTWOTL) THEN
      PQICE(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PI0(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    ELSE
      PQICE(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PI9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    END IF
  ELSE
    PQICE(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
  END IF
  IF (YGFL%YR%LACTIVE) THEN
    IF (YDDYNA%LSLAG .and. YDDYNA%LTWOTL) THEN
      PQRAIN(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PR0(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    ELSE
      PQRAIN(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PR9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    END IF
  ELSE
    PQRAIN(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
  END IF
  IF (YGFL%YS%LACTIVE) THEN
    IF (YDDYNA%LSLAG .and. YDDYNA%LTWOTL) THEN
      PQSNOW(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PS0(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    ELSE
      PQSNOW(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PS9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    END IF
  ELSE
    PQSNOW(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
  END IF
  IF (YGFL%YG%LACTIVE) THEN
    IF (YDDYNA%LSLAG .and. YDDYNA%LTWOTL) THEN
      PQGRAUPEL(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PG0(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    ELSE
      PQGRAUPEL(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = PG9(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
    END IF
  ELSE
    PQGRAUPEL(JLON, 1:YDGEOMETRY%YRDIMV%NFLEVG) = 0.0_JPRB
  END IF
  
  
  !*          1.3    PB2[X]1 for continuity equation (GMVS).
  
  IF (YDDYNA%LSLAG) THEN
    PB2SP1(JLON) = 0.0_JPRB
  ELSE
    IF (YDDYN%NCURRENT_ITER == 0) THEN
      PB2SP1(JLON) = PSPT9(JLON)*PTE
    ELSE
      PB2SP1(JLON) = 0.0_JPRB
    END IF
  END IF
  
  
END SUBROUTINE GPINISLB_PART1_EXPL_OPENACC
