SUBROUTINE GPINISLB_PART3_EXPL_OPENACC (YDGEOMETRY, YDDYNA, KST, KEND, PVVEL0, PZPRE0F, PB2VVEL, PB2GWF, PB2GDW, PB2GWS, PGWFT0,  &
& PGDW0, PGWS0, YDSTACK)
  
  !**** *GPINISLB_PART3_EXPL*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-11-2022
  
!$acc routine( GPINISLB_PART3_EXPL_OPENACC )
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: DR_HOOK, LHOOK, JPHOOK
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  USE YOMDYNA, ONLY: TDYNA
  
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(TDYNA), INTENT(IN) :: YDDYNA
  INTEGER(KIND=JPIM), INTENT(IN) :: KST
  INTEGER(KIND=JPIM), INTENT(IN) :: KEND
  REAL(KIND=JPRB), INTENT(IN) :: PVVEL0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(IN) :: PZPRE0F(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(INOUT) :: PB2VVEL(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(INOUT) :: PB2GWF(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(INOUT) :: PB2GDW(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), INTENT(INOUT) :: PB2GWS(YDGEOMETRY%YRDIM%NPROMA)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGWFT0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGDW0(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGWS0(YDGEOMETRY%YRDIM%NPROMA)
  
#include "abor1.intfb.h"
  
  INTEGER(KIND=JPIM) :: JLEV
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KST
  
  
  !*          2.     PB2[X] for other purposes.
  !                  --------------------------
  
  !*          2.1    PB2VVEL.
  
  !cf this do loop is furiously non linear, but useless in tl model
  ! Non linear: TL code is in CPG_GP_TL.
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    PB2VVEL(JLON, JLEV) = PVVEL0(JLON, JLEV)*PZPRE0F(JLON, JLEV)
  END DO
  
  !*          2.2    (gw), (g w_surf) and (g dw).
  
  IF (YDDYNA%LNHDYN .and. YDDYNA%LGWADV .and. YDGEOMETRY%YRVERT_GEOM%YRCVER%LVERTFE .and. YDGEOMETRY%YRVERT_GEOM%YRCVER%LVFE_GW &
  & ) THEN
    ! Not yet coded in the TL code.
    ! Makes sence only for LTWOTL=T and LSLAG=T
    IF (.not.(PRESENT(PGWFT0) .and. PRESENT(PGDW0) .and. PRESENT(PGWS0))) CALL ABOR1_ACC(' GPINISLB 2a: missing optional input  &
    & arguments!')
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      PB2GWF(JLON, JLEV) = PGWFT0(JLON, JLEV)
      PB2GDW(JLON, JLEV) = PGDW0(JLON, JLEV)
    END DO
    PB2GWS(JLON) = PGWS0(JLON)
  END IF
  
  
END SUBROUTINE GPINISLB_PART3_EXPL_OPENACC
