SUBROUTINE GPMPFC_EXPL_PART1_OPENACC (YDML_GCONF, YDDYN, YDDYNA, KPROMA, KFLEV, KST, KEND, PGM, P0U, P0V, P0DIV, P0TL, P0TM,  &
& P9U, P9V, P0UL, P0VL, P0VOR, P0SPDL, P0SPDM, P0SVDL, P0SVDM, P0NHXL, P0NHXM, P9DIV, P9TL, P9TM, P9SPDL, P9SPDM, P9SVDL,  &
& P9SVDM, P0SPL, P0SPM, P9SPL, P9SPM, YDSTACK)
  
  !**** *GPMPFC_EXPL_PART1 *
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-11-2022
  
!$acc routine( GPMPFC_EXPL_PART1_OPENACC )
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: DR_HOOK, LHOOK, JPHOOK
  
  USE MODEL_GENERAL_CONF_MOD, ONLY: MODEL_GENERAL_CONF_TYPE
  USE YOMDYN, ONLY: TDYN
  USE YOMDYNA, ONLY: TDYNA
  
  
  
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(MODEL_GENERAL_CONF_TYPE), INTENT(IN) :: YDML_GCONF
  TYPE(TDYN), INTENT(IN) :: YDDYN
  TYPE(TDYNA), INTENT(IN) :: YDDYNA
  INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KST
  INTEGER(KIND=JPIM), INTENT(IN) :: KEND
  REAL(KIND=JPRB), INTENT(IN) :: PGM(KPROMA)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0U(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0V(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0DIV(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0TL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0TM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9U(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9V(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0UL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0VL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0VOR(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SPDL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SPDM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SVDL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SVDM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0NHXL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0NHXM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9DIV(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9TL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9TM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SPDL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SPDM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SVDL(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SVDM(KPROMA, KFLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SPL(KPROMA)
  REAL(KIND=JPRB), INTENT(INOUT) :: P0SPM(KPROMA)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SPL(KPROMA)
  REAL(KIND=JPRB), INTENT(INOUT) :: P9SPM(KPROMA)
  
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JROF
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KST
  
  
  ! * GMV (unconditional t0 and t9 merged):
  
  DO JLEV=1,KFLEV
    ! mapping of gmv t0
    P0U(JLON, JLEV) = P0U(JLON, JLEV)*PGM(JLON)
    P0V(JLON, JLEV) = P0V(JLON, JLEV)*PGM(JLON)
    P0DIV(JLON, JLEV) = P0DIV(JLON, JLEV)*PGM(JLON)*PGM(JLON)
    P0TL(JLON, JLEV) = P0TL(JLON, JLEV)*PGM(JLON)
    P0TM(JLON, JLEV) = P0TM(JLON, JLEV)*PGM(JLON)
    
    ! mapping of gmv t9
    P9U(JLON, JLEV) = P9U(JLON, JLEV)*PGM(JLON)
    P9V(JLON, JLEV) = P9V(JLON, JLEV)*PGM(JLON)
    
    IF (YDML_GCONF%YRDIMF%LUVDER) THEN
      P0UL(JLON, JLEV) = P0UL(JLON, JLEV)*PGM(JLON)*PGM(JLON)
      P0VL(JLON, JLEV) = P0VL(JLON, JLEV)*PGM(JLON)*PGM(JLON)
    END IF
    
    IF (YDML_GCONF%YRDIMF%LVOR) THEN
      P0VOR(JLON, JLEV) = P0VOR(JLON, JLEV)*PGM(JLON)*PGM(JLON)
    END IF
    
    IF (YDDYNA%LNHDYN) THEN
      P0SPDL(JLON, JLEV) = P0SPDL(JLON, JLEV)*PGM(JLON)
      P0SPDM(JLON, JLEV) = P0SPDM(JLON, JLEV)*PGM(JLON)
      P0SVDL(JLON, JLEV) = P0SVDL(JLON, JLEV)*PGM(JLON)
      P0SVDM(JLON, JLEV) = P0SVDM(JLON, JLEV)*PGM(JLON)
      
      IF (YDDYNA%LNHXDER) THEN
        P0NHXL(JLON, JLEV) = P0NHXL(JLON, JLEV)*PGM(JLON)
        P0NHXM(JLON, JLEV) = P0NHXM(JLON, JLEV)*PGM(JLON)
      END IF
    END IF
  END DO
  
  IF (.not.YDDYNA%LTWOTL) THEN
    DO JLEV=1,KFLEV
      P9DIV(JLON, JLEV) = P9DIV(JLON, JLEV)*PGM(JLON)*PGM(JLON)
      P9TL(JLON, JLEV) = P9TL(JLON, JLEV)*PGM(JLON)
      P9TM(JLON, JLEV) = P9TM(JLON, JLEV)*PGM(JLON)
      
      IF (YDDYNA%LNHDYN) THEN
        P9SPDL(JLON, JLEV) = P9SPDL(JLON, JLEV)*PGM(JLON)
        P9SPDM(JLON, JLEV) = P9SPDM(JLON, JLEV)*PGM(JLON)
        P9SVDL(JLON, JLEV) = P9SVDL(JLON, JLEV)*PGM(JLON)
        P9SVDM(JLON, JLEV) = P9SVDM(JLON, JLEV)*PGM(JLON)
      END IF
    END DO
  END IF
  
  ! * GMVS:
  
  P0SPL(JLON) = P0SPL(JLON)*PGM(JLON)
  P0SPM(JLON) = P0SPM(JLON)*PGM(JLON)
  
  IF (.not.YDDYNA%LTWOTL .or. YDDYN%NCURRENT_ITER > 0 .and. YDDYNA%LPC_FULL) THEN
    P9SPL(JLON) = P9SPL(JLON)*PGM(JLON)
    P9SPM(JLON) = P9SPM(JLON)*PGM(JLON)
  END IF
  
  
END SUBROUTINE GPMPFC_EXPL_PART1_OPENACC
