SUBROUTINE CUBASMCN_OPENACC (YDCST, YDECUMF, KIDIA, KFDIA, KLON, KLEV, KK, PTEN, PQEN, PQSEN, PVERVEL, PGEO, PGEOH, LDCUM,  &
& KTYPE, KLAB, KCBOT, PMFU, PMFUB, PLRAIN, PTU, PQU, PLU, PMFUS, PMFUQ, PMFUL, PDMFUP, YDSTACK)
  
  !          M.TIEDTKE         E.C.M.W.F.     12/89
  
  !          PURPOSE.
  !          --------
  !          THIS ROUTINE CALCULATES CLOUD BASE VALUES
  !          FOR MIDLEVEL CONVECTION
  
  !          INTERFACE
  !          ---------
  
  !          THIS ROUTINE IS CALLED FROM *CUASC*.
  !          INPUT ARE ENVIRONMENTAL VALUES T,Q ETC
  !          IT RETURNS CLOUDBASE VALUES FOR MIDLEVEL CONVECTION
  
  !          METHOD.
  !          --------
  !          S. TIEDTKE (1989)
  
  !     PARAMETER     DESCRIPTION                                   UNITS
  !     ---------     -----------                                   -----
  !     INPUT PARAMETERS (INTEGER):
  
  !    *KIDIA*        START POINT
  !    *KFDIA*        END POINT
  !    *KLON*         NUMBER OF GRID POINTS PER PACKET
  !    *KLEV*         NUMBER OF LEVELS
  !    *KK*           ACTUAL LEVEL
  
  !    INPUT PARAMETERS (REAL):
  
  !    *PTEN*         PROVISIONAL ENVIRONMENT TEMPERATURE (T+1)       K
  !    *PQEN*         PROVISIONAL ENVIRONMENT SPEC. HUMIDITY (T+1)  KG/KG
  !    *PQSEN*        ENVIRONMENT SPEC. SATURATION HUMIDITY (T+1)   KG/KG
  !    *PVERVEL*      VERTICAL VELOCITY                             PA/S
  !    *PGEO*         GEOPOTENTIAL                                  M2/S2
  !    *PGEOH*        GEOPOTENTIAL ON HALF LEVELS                   M2/S2
  !    *PLRAIN*       RAIN WATER CONTENT IN UPDRAFTS                KG/KG
  
  !    INPUT PARAMETERS (LOGICAL):
  
  !    *LDCUM*        FLAG: .TRUE. FOR CONVECTIVE POINTS
  
  !    UPDATED PARAMETERS (INTEGER):
  
  !    *KTYPE*        TYPE OF CONVECTION
  !                       1 = PENETRATIVE CONVECTION
  !                       2 = SHALLOW CONVECTION
  !                       3 = MIDLEVEL CONVECTION
  !    *KLAB*         FLAG KLAB=1 FOR SUBCLOUD LEVELS
  !                        KLAB=2 FOR CLOUD LEVELS
  !    *KCBOT*        CLOUD BASE LEVEL
  
  !    OUTPUT PARAMETERS (REAL):
  
  !    *PMFU*         MASSFLUX IN UPDRAFTS                          KG/(M2*S)
  !    *PMFUB*        MASSFLUX IN UPDRAFTS AT CLOUD BASE            KG/(M2*S)
  !    *PTU*          TEMPERATURE IN UPDRAFTS                         K
  !    *PQU*          SPEC. HUMIDITY IN UPDRAFTS                    KG/KG
  !    *PLU*          LIQUID WATER CONTENT IN UPDRAFTS              KG/KG
  !    *PMFUS*        FLUX OF DRY STATIC ENERGY IN UPDRAFTS          J/(M2*S)
  !    *PMFUQ*        FLUX OF SPEC. HUMIDITY IN UPDRAFTS            KG/(M2*S)
  !    *PMFUL*        FLUX OF LIQUID WATER IN UPDRAFTS              KG/(M2*S)
  !    *PDMFUP*       FLUX DIFFERENCE OF PRECIP. IN UPDRAFTS        KG/(M2*S)
  
  !          EXTERNALS
  !          ---------
  !          NONE
  
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !     R. El Khatib 06-Sep-2023 vectorization
  !----------------------------------------------------------------------
  
!$acc routine( CUBASMCN_OPENACC ) seq
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  USE YOECUMF, ONLY: TECUMF
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(TECUMF), INTENT(IN) :: YDECUMF
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KK
  REAL(KIND=JPRB), INTENT(IN) :: PTEN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQEN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQSEN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PVERVEL(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PGEO(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PGEOH(KLON, KLEV + 1)
  LOGICAL, INTENT(IN) :: LDCUM(KLON)
  INTEGER(KIND=JPIM), INTENT(OUT) :: KTYPE(KLON)
  INTEGER(KIND=JPIM), INTENT(INOUT) :: KLAB(KLON, KLEV)
  INTEGER(KIND=JPIM), INTENT(OUT) :: KCBOT(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFUB(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PLRAIN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PQU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PLU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFUS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFUQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFUL(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PDMFUP(KLON, KLEV)
  INTEGER(KIND=JPIM) :: JL
  
  REAL(KIND=JPRB) :: ZZZMB
  REAL(KIND=JPRB) :: ZRG
  REAL(KIND=JPRB) :: ZORCPD
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KIDIA
  YLSTACK = YDSTACK
  
  !----------------------------------------------------------------------
  
  
  !*    1.           CALCULATE ENTRAINMENT AND DETRAINMENT RATES
  !                  -------------------------------------------
  
  
  ZRG = 1.0_JPRB / YDCST%RG
  ZORCPD = 1.0_JPRB / YDCST%RCPD
  !DIR$ IVDEP
  !OCL NOVREC
  IF (.not.LDCUM(JLON) .and. KLAB(JLON, KK + 1) == 0) THEN
    IF (YDECUMF%LMFMID .and. KK > YDECUMF%NJKT7 .and. PQEN(JLON, KK) > 0.80_JPRB*PQSEN(JLON, KK)) THEN
      PTU(JLON, KK + 1) = (YDCST%RCPD*PTEN(JLON, KK) + PGEO(JLON, KK) - PGEOH(JLON, KK + 1))*ZORCPD
      PQU(JLON, KK + 1) = PQEN(JLON, KK)
      PLU(JLON, KK + 1) = 0.0_JPRB
      ! ZZZMB=MAX(RMFCMIN,-PVERVEL(JL,KK)/RG)
      ZZZMB = MAX(1.E-6_JPRB, -PVERVEL(JLON, KK)*ZRG)
      ZZZMB = MIN(ZZZMB, YDECUMF%RMFLIA)
      PMFUB(JLON) = ZZZMB
      PMFU(JLON, KK + 1) = PMFUB(JLON)
      PMFUS(JLON, KK + 1) = PMFUB(JLON)*(YDCST%RCPD*PTU(JLON, KK + 1) + PGEOH(JLON, KK + 1))
      PMFUQ(JLON, KK + 1) = PMFUB(JLON)*PQU(JLON, KK + 1)
      PMFUL(JLON, KK + 1) = 0.0_JPRB
      PDMFUP(JLON, KK + 1) = 0.0_JPRB
      PLRAIN(JLON, KK + 1) = 0.0_JPRB
      KCBOT(JLON) = KK
      KLAB(JLON, KK + 1) = 1
      KTYPE(JLON) = 3
    END IF
  END IF
  
END SUBROUTINE CUBASMCN_OPENACC
