SUBROUTINE ACDRAG_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV,  &
& PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, YDSTACK)
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  ! - INPUT  1D .
  ! - OUTPUT 2D .
  
  !**** *ACDRAG * - EFFET DES ONDES DE GRAVITE OROGRAPHIQUES.
  
  !     Sujet.
  !     ------
  !     - ROUTINE DE CALCUL ACTIF .
  !       CALCUL DES EFFETS SUR LA QUANTITE DE MOUVEMENT DU DEFERLEMENT
  !       DES ONDES DE GRAVITE D'ORIGINE OROGRAPHIQUE .
  !     - COMPUTATION OF OROGRAPHIC GRAVITY-WAVES' BREAKING EFFECTS ON
  !       MOMENTUM .
  
  !**   Interface.
  !     ----------
  !        *CALL* *ACDRAG*
  
  !-----------------------------------------------------------------------
  ! WARNING: THE ENGLISH VERSION OF VARIABLES' NAMES IS TO BE READ IN THE
  !          "APLPAR" CODE.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS D'ENTREE.
  !     -------------------
  
  ! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.
  
  ! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
  ! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
  ! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
  ! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
  ! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 2D (0:KLEV) .
  
  ! PAPRS      : PRESSION AUX DEMI-NIVEAUX.
  ! PNBVNO     : CARRE DE FR. BRUNT-VAISALA DIVISEE PAR G FOIS LA DENSITE.
  
  ! - 2D (1:KLEV) .
  
  ! PAPRSF     : PRESSION AUX NIVEAUX DES COUCHES.
  ! PDELP      : EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PU         : COMPOSANTE EN X DU VENT.
  ! PV         : COMPOSANTE EN Y DU VENT.
  
  ! - 1D (GEOGRAPHIQUE) .
  
  ! PRCORI     : FACTEUR DE CORIOLIS.
  ! PGETRL     : ECART TYPE DE L'OROGRAPHIE (EN J/KG).
  ! PVRLAN     : ANISOTROPIE DU RELIEF SOUS MAILLE (1 = ISOTROPE).
  ! PVRLDI     : ANGLE DU GRADIENT MAXIMUM DU RELIEF AVEC L'AXE DES X.
  
  ! - 1D (DIAGNOSTIQUE) .
  
  ! PGWDCS     : DENSITE EN SURFACE POUR LE DRAG OROGRAPHIQUE.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS DE SORTIE.
  !     --------------------
  
  ! - 2D (0:KLEV) .
  
  ! PSTRDU     : FLUX "GRAVITY WAVE DRAG" "U".
  ! PSTRDV     : FLUX "GRAVITY WAVE DRAG" "V".
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS IMPLICITES.
  !     ---------------------
  
  !-----------------------------------------------------------------------
  
  !     Externes.
  !     ---------
  
  !     Methode.
  !     --------
  
  !     Auteur.
  !     -------
  !      89-12, J.F. Geleyn.
  
  !     Modifications.
  !     --------------
  !      04-03, New options LGLT, LNEWD, GWDPROF, GWDVALI - J.F.Geleyn F.Bouyssel
  !      M.Hamrud      01-Oct-2003 CY28 Cleaning
  !      2006-03-03 R.Brozkova - improved form drag along the slopes when LNEWD=.TRUE.
  !      K. Yessad (Jul 2009): remove CDLOCK + some cleanings
  !      O.Riviere 0ct 09 - Save ZRAPP for simpl phys under LGWDSPNL
  !      R. El Khatib 20-Oct-2014 Fix a broken vectorization + workaround against Intel bug
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( ACDRAG_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB, JPRD
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
  REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PNBVNO(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PRDELP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PV(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PRCORI(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PGETRL(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PGWDCS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PVRLAN(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PVRLDI(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSTRDU(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PSTRDV(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PRAPTRAJ(KLON, 0:KLEV)
  
  
  !-----------------------------------------------------------------------
  
  temp (REAL (KIND=JPRB), ZIPOI, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZNFNO, (KLON, 0:KLEV))
  temp (REAL (KIND=JPRB), ZPOID, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZRAPP, (KLON, 0:KLEV))
  temp (REAL (KIND=JPRB), ZU, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZV, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZWGHT, (KLON, 0:KLEV))
  REAL(KIND=JPRB) :: ZDS1
  REAL(KIND=JPRB) :: ZDS2
  REAL(KIND=JPRB) :: ZFACS
  REAL(KIND=JPRB) :: ZOBST
  REAL(KIND=JPRB) :: ZPR1
  REAL(KIND=JPRB) :: ZPR2
  REAL(KIND=JPRB) :: ZREF
  REAL(KIND=JPRB) :: ZSTM
  REAL(KIND=JPRB) :: ZSTS
  REAL(KIND=JPRB) :: ZSTUS
  REAL(KIND=JPRB) :: ZSTVS
  REAL(KIND=JPRB) :: ZSUM
  REAL(KIND=JPRB) :: ZSUMD
  REAL(KIND=JPRB) :: ZSUMF
  REAL(KIND=JPRB) :: ZSUMU
  REAL(KIND=JPRB) :: ZSUMV
  REAL(KIND=JPRB) :: ZSUSR
  REAL(KIND=JPRB) :: ZTST1
  REAL(KIND=JPRB) :: ZTST2
  REAL(KIND=JPRB) :: ZUSR
  REAL(KIND=JPRB) :: ZUSUR
  REAL(KIND=JPRB) :: ZVSUR
  REAL(KIND=JPRB) :: ZWGHTK
  REAL(KIND=JPRB) :: ZZAA
  REAL(KIND=JPRB) :: ZZBB
  REAL(KIND=JPRB) :: ZZCR
  REAL(KIND=JPRB) :: ZZCU
  REAL(KIND=JPRB) :: ZZCV
  
  INTEGER(KIND=JPIM) :: ITOP
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPRB) :: ZA
  REAL(KIND=JPRB) :: ZALP1
  REAL(KIND=JPRB) :: ZALP2
  REAL(KIND=JPRB) :: ZALPHA
  REAL(KIND=JPRB) :: ZALTI
  REAL(KIND=JPRB) :: ZARGLI
  REAL(KIND=JPRB) :: ZAUSR
  REAL(KIND=JPRB) :: ZBETA
  REAL(KIND=JPRB) :: ZD
  REAL(KIND=JPRB) :: ZDEL1
  REAL(KIND=JPRB) :: ZDEL2
  REAL(KIND=JPRB) :: ZDIFSR
  REAL(KIND=JPRB) :: ZDIFSU
  REAL(KIND=JPRB) :: ZDIFSV
  REAL(KIND=JPRB) :: ZDU
  REAL(KIND=JPRB) :: ZDV
  REAL(KIND=JPRB) :: ZDX
  REAL(KIND=JPRB) :: ZEPS1
  REAL(KIND=JPRB) :: ZEPS2
  REAL(KIND=JPRB) :: ZEPS3
  REAL(KIND=JPRB) :: ZEPS4
  REAL(KIND=JPRB) :: ZEPS5
  REAL(KIND=JPRB) :: ZEPS6
  REAL(KIND=JPRB) :: ZFORCA
  REAL(KIND=JPRB) :: ZFORCB
  REAL(KIND=JPRB) :: ZFORCL
  REAL(KIND=JPRB) :: ZGDT
  REAL(KIND=JPRB) :: ZGDTI
  REAL(KIND=JPRB) :: ZLIFT
  REAL(KIND=JPRB) :: ZLIFTG
  REAL(KIND=JPRB) :: ZPBL
  REAL(KIND=JPRB) :: ZPBLF
  REAL(KIND=JPRB) :: ZPRRAP
  REAL(KIND=JPRB) :: ZRZ
  REAL(KIND=JPRB) :: ZTEMPF
  REAL(KIND=JPRB) :: ZTEST
  REAL(KIND=JPRB) :: ZTUNE
  REAL(KIND=JPRB) :: ZUSTAR
  REAL(KIND=JPRB) :: ZVSTAR
  REAL(KIND=JPRB) :: ZX
  REAL(KIND=JPRB) :: ZZPR
  REAL(KIND=JPRB) :: ZRZR
  REAL(KIND=JPRB) :: ZCOS
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KIDIA
  YLSTACK = YDSTACK
  IF (KIND (ZIPOI) == 8) THEN
    alloc8 (ZIPOI)
  ELSE
    IF (KIND (ZIPOI) == 4) THEN
      alloc4 (ZIPOI)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZNFNO) == 8) THEN
    alloc8 (ZNFNO)
  ELSE
    IF (KIND (ZNFNO) == 4) THEN
      alloc4 (ZNFNO)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZPOID) == 8) THEN
    alloc8 (ZPOID)
  ELSE
    IF (KIND (ZPOID) == 4) THEN
      alloc4 (ZPOID)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZRAPP) == 8) THEN
    alloc8 (ZRAPP)
  ELSE
    IF (KIND (ZRAPP) == 4) THEN
      alloc4 (ZRAPP)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZU) == 8) THEN
    alloc8 (ZU)
  ELSE
    IF (KIND (ZU) == 4) THEN
      alloc4 (ZU)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZV) == 8) THEN
    alloc8 (ZV)
  ELSE
    IF (KIND (ZV) == 4) THEN
      alloc4 (ZV)
    ELSE
      STOP 1
    END IF
  END IF
  IF (KIND (ZWGHT) == 8) THEN
    alloc8 (ZWGHT)
  ELSE
    IF (KIND (ZWGHT) == 4) THEN
      alloc4 (ZWGHT)
    ELSE
      STOP 1
    END IF
  END IF
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  
  
  PRAPTRAJ(JLON, :) = 0.0
  !*
  !     ------------------------------------------------------------------
  !     I - CALCUL DES PARAMETRES DERIVES, CONSTANTES DE SECURITE (POUR LE
  !     FACTEUR D'ANISOTROPIE, LE CARRE DU MODULE DU VENT, LA STABILITE
  !     STATIQUE NORMALISEE, UN SEUIL DE PRECISION SUR DES PRESSIONS
  !     RECALCULEES, LE MODULE DE VENT ET UN NOMBRE SANS DIMENSION) AINSI
  !     QU'UN ARGUMENT LIMITE POUR LA FONCTION SINUS.
  
  !         COMPUTATION OF DERIVED PARAMETERS, SECURITY CONSTANTS (FOR THE
  !     ANISOTROPY FACTOR, THE SQUARE OF THE WIND SPEED, THE NORMALISED
  !     STATIC STABILITY A PRECISION THRESHOLD FOR RECOMPUTED PRESSURES,
  !     THE WIND SPEED AND AN ADIMENSIONALISED PARAMETER) AS WELL AS A LIMIT
  !     ARGUMENT FOR THE SINE FUNCTION.
  
  ZGDT = YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
  ZGDTI = 1.0_JPRB / ZGDT
  
  !     LES CONSTANTES 'ALP' ET 'DEL' POUR LE CALCUL ANISOTROPE RESULTENT
  !     D'APPROXIMATIONS ANALYTIQUES D'INTEGRALES ELLIPTIQUES.
  !     THE 'ALP' AND 'DEL' VALUES ARE RESULTING FROM ANALYTICAL FITS OF
  !     ELLIPTIC INTEGRALS FOR THE ANISOTROPIC CASE.
  
  IF (YDML_PHY_MF%YRPHY0%GWDPROF == 0.0_JPRB) THEN
    ZZPR = 0.5_JPRB
  ELSE
    ZZPR = ((1.0_JPRB + YDML_PHY_MF%YRPHY0%GWDPROF)*LOG(1.0_JPRB + YDML_PHY_MF%YRPHY0%GWDPROF) - YDML_PHY_MF%YRPHY0%GWDPROF) /  &
    & YDML_PHY_MF%YRPHY0%GWDPROF**2
  END IF
  
  ZLIFT = YDML_PHY_MF%YRPHY0%GWDLT*YDML_PHY_MF%YRPHY2%TSPHY / (YDML_PHY_MF%YRPHY0%HOBST*ZZPR)
  ZLIFTG = YDML_PHY_MF%YRPHY0%GWDLT / (YDML_PHY_MF%YRPHY0%HOBST*ZZPR)
  
  IF (.not.YDML_PHY_MF%YRPHY%LGLT) THEN
    ZLIFTG = 0.0_JPRB
  END IF
  
  ZALP1 = 0.75_JPRB + 0.25_JPRB*LOG(16._JPRB)
  ZALP2 = 3.5_JPRB*YDCST%RPI - LOG(16._JPRB) - 8._JPRB
  ZDEL1 = 2.75_JPRB - 0.75_JPRB*LOG(16._JPRB)
  ZDEL2 = -0.25_JPRB*YDCST%RPI - LOG(16._JPRB) + 4._JPRB
  
  ZEPS1 = 1.E-06_JPRB
  ZEPS2 = 1.E-04_JPRB
  ZEPS3 = 1.E-09_JPRB
  ZEPS4 = 1.E-05_JPRB
  ZEPS5 = 1.E-02_JPRB
  
  IF (JPRB == JPRD) THEN
    ZEPS6 = 1.E-12_JPRB
  ELSE
    ZEPS6 = 1.E-6_JPRB
  END IF
  
  ZARGLI = 1.E+06_JPRB
  
  ZBETA = MIN(YDML_PHY_MF%YRPHY0%GWDVALI, 1.0_JPRB - ZEPS6)
  
  !*
  !     ------------------------------------------------------------------
  !     II - CALCULS PRELIMINAIRES DE L'EPAISSEUR EN PRESSION DES COUCHES
  !     DIVISEE PAR G*DT ET DE SON INVERSE POUR CHAQUE NIVEAU AINSI QUE
  !     MISE A ZERO DES POIDS POUR L'INTEGRATION SUR L'EPAISSEUR DE
  !     L'OBSTACLE OROGRAPHIQUE.
  
  !          PRELIMINARY COMPUTATIONS FOR THE LAYER'S PRESSURE THICKNESS
  !     DIVIDED BY G*DT AND ITS INVERSE FOR ALL LEVELS AS WELL AS SETTING
  !     TO ZERO THE WEIGHTS FOR THE INTEGRAL OVER THE DEPTH OF THE
  !     OROGRAPHIC OBSTACLE.
  
  ! - TEMPORAIRE(S) 2D (1:KLEV) .
  
  ! ZPOID     : DP/(RG*DT) POUR UNE COUCHE ET UN PAS DE TEMPS DONNES.
  !            : DP/(RG*DT) FOR A GIVEN LEVEL AND A GIVEN TIME STEP.
  ! ZIPOI     : INVERSE DE ZPOID.
  !            : INVERSE OF ZPOID.
  ! ZWGHT     : POIDS POUR L'INTEGRALE SUR LA HAUTEUR DE L'OBSTACLE.
  !            : WEIGHTS FOR THE INTEGRAL OVER THE DEPTH OF THE OBSTACLE.
  
  DO JLEV=KTDIA,KLEV
    ZPOID(JLON, JLEV) = PDELP(JLON, JLEV)*ZGDTI
    ZIPOI(JLON, JLEV) = PRDELP(JLON, JLEV)*ZGDT
    ZWGHT(JLON, JLEV) = 0.0_JPRB
  END DO
  
  !*
  !     ------------------------------------------------------------------
  !     III - CALCULS EN SURFACE ET INITIALISATION POUR LA BOUCLE
  !     ASCENDANTE.
  
  !           SURFACE COMPUTATIONS AND INITIALIZATION FOR THE ASCENDING
  !     LOOP.
  
  ! - TEMPORAIRE(S) 2D (0:KLEV) .
  
  ! ZNFNO     : FREQUENCE DE BRUNT-VAISALA EFFECTIVE ET NORMEE (N/RHO/G).
  !            : NORMALISED EFECTIVE BRUNT-VAISALA FREQUENCY (N/RHO/G).
  ! ZRAPP     : RAPPORT DU FLUX EN ALTITUDE A CELUI AU SOL.
  !            : RATIO OF THE UPPER AIR FLUX TO THE SURFACE ONE.
  ! ZU        : COMPOSANTE EN X DU VENT EFFECTIF.
  !            : X COMPONENT OF THE EFFECTIVE WIND.
  ! ZV        : COMPOSANTE EN Y DU VENT EFFECTIF.
  !            : Y COMPONENT OF THE EFFECTIVE WIND.
  
  !     MOYENNES VERTICALES SUR L'EPAISSEUR DE L'OBSTACLE OROGRAPHIQUE ET
  !     CALCUL DES CARACTERISTIQUES (VENT ET STABILITE) EFFECTIVES PAR
  !     COMBINAISON LINEAIRE ENTRE CES MOYENNES (CHOISIES EN SURFACE) ET
  !     LES CARACTERISTIQUES INITIALES (RETROUVEES A LA HAUTEUR EFFECTIVE
  !     DE L'OBSTACLE).
  !     VERTICAL AVERAGING OVER THE THICKNESS OF THE OROGRAPHIC OBSTACLE
  !     AND CALCULATION OF THE EFFECTIVE VALUES (WIND AND STABILITY)
  !     THROUGH LINEAR COMBINATIONS BETWEEN THE AVERAGES (CHOSEN AT THE
  !     SURFACE) AND THE ORIGINAL VALUES (OBTAINED AGAIN AT THE EFFECTIVE
  !     HEIGHT OF THE OBSTACLE).
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZOBST     : HAUTEUR EFFECTIVE DE L'OBSTACLE EN COORDONNEE PRESSION.
  !            : EFFECTIVE HEIGHT OF THE OBSTACLE IN PRESSURE COORDINATE.
  ! ZSUMF     : MOYENNE PONDEREE POUR "N/RHO/G" AU CARRE (<0 ADMIS).
  !            : AVERAGED VALUE FOR A SQUARED "N/RHO/G" (<0 ACCEPTED).
  ! ZSUMU     : MOYENNE PONDEREE POUR LE VENT "U".
  !            : AVERAGED VALUE FOR THE "U" WIND.
  ! ZSUMV     : MOYENNE PONDEREE POUR LE VENT "V".
  !            : AVERAGED VALUE FOR THE "V" WIND.
  
  !     SOMMATION PONDEREE.
  !     WEIGHTED SUMMATION.
  
  ZOBST = MIN(PAPRS(JLON, KLEV) - PAPRSF(JLON, KTDIA), MAX(PAPRS(JLON, KLEV) - PAPRSF(JLON, KLEV),  &
  & YDML_PHY_MF%YRPHY0%HOBST*PGETRL(JLON)*PGWDCS(JLON)))
  ZWGHT(JLON, KLEV) = (PAPRS(JLON, KLEV) - PAPRSF(JLON, KLEV)) / ZOBST
  ZWGHT(JLON, KLEV) = ZWGHT(JLON, KLEV)*(1.0_JPRB - ZBETA)
  ZWGHTK = ZWGHT(JLON, KLEV)
  ZSUMU = ZWGHT(JLON, KLEV)*PU(JLON, KLEV)
  ZSUMV = ZWGHT(JLON, KLEV)*PV(JLON, KLEV)
  ZSUMF = ZWGHT(JLON, KLEV)*PNBVNO(JLON, KLEV)
  
  !     ZTEST ET ITOP POUR EVITER DES CALCULS INUTILES.
  !     ZTEST AND ITOP TO AVOID UNNECESSARY COMPUTATIONS.
  
  ZTEST = 1.0_JPRB
  ITOP = KLEV
  
  DO JLEV=KLEV - 1,KTDIA,-1
    
    IF (ZTEST /= 0.0_JPRB) THEN
      ITOP = JLEV
      
      ZWGHT(JLON, JLEV) = MAX(0.0_JPRB, (PAPRSF(JLON, JLEV + 1) - MAX(PAPRSF(JLON, JLEV), PAPRS(JLON, KLEV) - ZOBST)) / ZOBST)
      ZALTI = MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRS(JLON, JLEV)) / ZOBST)
      ZWGHT(JLON, JLEV) =  &
      & ZWGHT(JLON, JLEV)*(1.0_JPRB - ZBETA*((1.0_JPRB - ZALTI) / (1.0_JPRB + YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
      ZWGHTK = ZWGHTK + ZWGHT(JLON, JLEV)
      ZSUMU = ZSUMU + 0.5_JPRB*ZWGHT(JLON, JLEV)*(PU(JLON, JLEV) + PU(JLON, JLEV + 1))
      ZSUMV = ZSUMV + 0.5_JPRB*ZWGHT(JLON, JLEV)*(PV(JLON, JLEV) + PV(JLON, JLEV + 1))
      ZSUMF = ZSUMF + ZWGHT(JLON, JLEV)*PNBVNO(JLON, JLEV)
    END IF
    
    ZTEST = 0.0_JPRB
    ZTEST = ZTEST + ZWGHT(JLON, JLEV)
    
  END DO
  
  DO JLEV=KTDIA,KLEV
    ZWGHT(JLON, JLEV) = ZWGHT(JLON, JLEV)*(1.0_JPRB / ZWGHTK)
  END DO
  
  ZSUMU = ZSUMU*(1.0_JPRB / ZWGHTK)
  ZSUMV = ZSUMV*(1.0_JPRB / ZWGHTK)
  ZSUMF = ZSUMF*(1.0_JPRB / ZWGHTK)
  
  IF (YDML_PHY_MF%YRPHY%NPHYREP /= 0 .and. YDML_PHY_MF%YRPHY%NPHYREP /= -2) ITOP = KTDIA
  
  !     COMBINAISON LINEAIRE.
  !     LINEAR COMBINATION.
  
  ZNFNO(JLON, KLEV) = SQRT(MAX(0.0_JPRB, ZSUMF))
  ZPBLF = 1.0_JPRB - MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRSF(JLON, KLEV)) / ZOBST)
  ZU(JLON, KLEV) = PU(JLON, KLEV) + ZPBLF*(ZSUMU - PU(JLON, KLEV))
  ZV(JLON, KLEV) = PV(JLON, KLEV) + ZPBLF*(ZSUMV - PV(JLON, KLEV))
  
  DO JLEV=KLEV - 1,KTDIA,-1
    ZPBL = 1.0_JPRB - MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRS(JLON, JLEV)) / ZOBST)
    ZNFNO(JLON, JLEV) = SQRT(MAX(0.0_JPRB, PNBVNO(JLON, JLEV) + ZPBL*(ZSUMF - PNBVNO(JLON, JLEV))))
    ZPBLF = 1.0_JPRB - MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRSF(JLON, JLEV)) / ZOBST)
    ZU(JLON, JLEV) = PU(JLON, JLEV) + ZPBLF*(ZSUMU - PU(JLON, JLEV))
    ZV(JLON, JLEV) = PV(JLON, JLEV) + ZPBLF*(ZSUMV - PV(JLON, JLEV))
  END DO
  
  
  !     CALCUL D'UN VENT FICTIF CORRESPONDANT DANS LE CAS ISOTROPE AU
  !     DRAG ANISOTROPE.
  !     COMPUTATION OF A FICTITIOUS WIND THAT WOULD CORRESPOND, IN THE
  !     ISOTROPIC CASE, TO THE ANISOTROPIC DRAG.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZUSUR     : COMPOSANTE X DU VENT FICTIF EN SURFACE.
  !            : X COMPONENT OF THE FICTITIOUS SURFACE WIND.
  ! ZVSUR     : COMPOSANTE Y DU VENT FICTIF EN SURFACE.
  !            : Y COMPONENT OF THE FICTITIOUS SURFACE WIND.
  
  ! Compiler bug
  ZUSTAR = ZSUMU*COS(2.0_JPRB*PVRLDI(JLON)) + ZSUMV*SIN(2.0_JPRB*PVRLDI(JLON))
  ZVSTAR = ZSUMU*SIN(2.0_JPRB*PVRLDI(JLON)) - ZSUMV*COS(2.0_JPRB*PVRLDI(JLON))
  ZA = PVRLAN(JLON)**2 + 0.5_JPRB*(4._JPRB*(1.0_JPRB - PVRLAN(JLON))*(1.0_JPRB + ZALP1*PVRLAN(JLON)) + PVRLAN(JLON)*LOG(1.0_JPRB  &
  & / MAX(ZEPS1, PVRLAN(JLON)))*(1.0_JPRB + ZALP2*PVRLAN(JLON))) / YDCST%RPI
  ZD = 0.5_JPRB*(4._JPRB*(1.0_JPRB - PVRLAN(JLON))*(1.0_JPRB + ZDEL1*PVRLAN(JLON)) - 3._JPRB*PVRLAN(JLON)*LOG(1.0_JPRB /  &
  & MAX(ZEPS1, PVRLAN(JLON)))*(1.0_JPRB + ZDEL2*PVRLAN(JLON))) / YDCST%RPI
  ZUSUR = ZA*ZSUMU + ZD*ZUSTAR
  ZVSUR = ZA*ZSUMV + ZD*ZVSTAR
  
  !     PARTIE "LINEAIRE" DU CALCUL.
  !     "LINEAR" PART OF THE COMPUTATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZUSR      : MODULE DU VENT FICTIF EN SURFACE.
  !            : SPEED OF FICTITIOUS SURFACE WIND.
  ! ZFACS     : FACTEUR AU SOL POUR LE CALCUL DE ZRAPP.
  !            : SURFACE FACTOR FOR THE COMPUTATION OF ZRAPP.
  ! ZSTUS     : VALEUR "LINEAIRE" DU FLUX EN "U" AU SOL.
  !            : "LINEAR" VALUE OF THE "U" SURFACE FLUX.
  ! ZSTVS     : VALEUR "LINEAIRE" DU FLUX EN "V" AU SOL.
  !            : "LINEAR" VALUE OF THE "V" SURFACE FLUX.
  ! ZSUSR     : PRODUIT SCALAIRE VENT EFFECTIF PAR VENT FICTIF EN SURF..
  !            : SURF. SCALAR PRODUCT OF EFFECTIVE AND FICITIOUS WINDS.
  
  ZSUSR = MAX(ZEPS2, ZSUMU*ZUSUR + ZSUMV*ZVSUR)
  ZUSR = SQRT(ZUSUR**2 + ZVSUR**2)
  ZFACS = ZNFNO(JLON, KLEV) / ZSUSR**3
  ZRAPP(JLON, KLEV) = 1.0_JPRB
  ZSTUS = YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS(JLON)**2*ZNFNO(JLON, KLEV)*PGETRL(JLON)*ZUSUR
  ZSTVS = YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS(JLON)**2*ZNFNO(JLON, KLEV)*PGETRL(JLON)*ZVSUR
  
  
  !     PARTIE "AMPLIFICATION RESONANTE" DU CALCUL.
  !     "RESONNANT AMPLIFICATION" PART OF THE COMPUTATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZTST1     : VALEUR BINAIRE DE TEST POUR LA PREMIERE DEPOSITION.
  !            : BINARY TEST VALUE FOR THE FIRST DEPOSITION.
  ! ZPR1      : PRESSION DU NIVEAU DE PREMIERE DEPOSITION.
  !            : PRESSURE AT THE LEVEL OF FIRST DEPOSITION.
  ! ZSUM      : INTEGRALE POUR LE CALCUL DE LA PHASE DE L'ONDE.
  !            : INTEGRAL FOR THE CALCULATION OF THE WAVE'S PHASE.
  
  ZTST1 = 1.0_JPRB
  ZPR1 = PAPRSF(JLON, KLEV)
  ZSUM = (PAPRS(JLON, KLEV) - PAPRSF(JLON, KLEV))*ZNFNO(JLON, KLEV)*ZUSR / ZSUSR
  
  !     PARTIE "REFLEXION ET DISSIPATION AVAL" DU CALCUL.
  !     "REFLEXION AND DOWNSTREAM DISSIPATION" PART OF THE COMPUTATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZTST2     : VALEUR BINAIRE DE TEST POUR LA PREMIERE REFLEXION.
  !            : BINARY TEST VALUE FOR THE FIRST REFLEXION.
  ! ZPR2      : PRESSION DU NIVEAU DE PREMIERE REFLEXION.
  !            : PRESSURE AT THE LEVEL OF FIRST REFLEXION.
  ! ZREF      : VALEUR RELATIVE DES FLUX A LA PREMIERE REFLEXION.
  !            : RELATIVE FLUX VALUE AT FIRST DEPOSITION.
  
  ZTST2 = 1.0_JPRB
  ZPR2 = PAPRSF(JLON, KLEV)
  ZREF = 1.0_JPRB
  ZTUNE = YDML_PHY_MF%YRPHY0%GWDBC*(ZUSR**2 / ZSUSR)**2
  ZTEMPF = ZUSR / MAX(ZEPS5, ZTUNE*YDML_PHY_MF%YRPHY0%HOBST*PGETRL(JLON)*PGWDCS(JLON)*ZNFNO(JLON, KLEV))
  ZZBB = MAX(0.0_JPRB, 1.0_JPRB - MAX(ZTEMPF, ZEPS6))
  ZZAA = YDML_PHY_MF%YRPHY0%GWDCD*ZZBB*ZTUNE*(1.0_JPRB - ZZBB)
  
  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
    ZSTUS = ZSTUS*(1.0_JPRB - ZZBB) / MAX(1.0_JPRB, ZTEMPF)
    ZSTVS = ZSTVS*(1.0_JPRB - ZZBB) / MAX(1.0_JPRB, ZTEMPF)
    ZZAA = YDML_PHY_MF%YRPHY0%GWDCD*ZZBB
  END IF
  
  
  DO JLEV=0,KLEV
    !DEC$ IVDEP
    PRAPTRAJ(JLON, JLEV) = YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS(JLON)**2*ZNFNO(JLON, KLEV)*PGETRL(JLON)
    IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
      PRAPTRAJ(JLON, JLEV) = PRAPTRAJ(JLON, JLEV)*(1.0_JPRB - ZZBB) / MAX(1.0_JPRB, ZTEMPF)
    END IF
  END DO
  
  !*
  !     ------------------------------------------------------------------
  !     IV - CALCULS ASCENDANTS DE L'ESTIMATION LINEAIRE DU FLUX RELATIF
  !     ET DU REPERAGE DES PREMIERS NIVEAUX DE DEPOSITION ET DE REFLEXION
  !     (SI CE DERNIER EXISTE).
  
  !          ASCENDING COMPUTATIONS OF THE LINEAR ESTIMATE OF THE RELATIVE
  !     FLUX AND CHECKING OF THE FIRST LEVELS OF DEPOSITION AND OF
  !     REFLEXION (IF THE LATTER EXISTS).
  
  !     CALCULS DANS LA BOUCLE VERTICALE.
  !     COMPUTATIONS IN THE VERTICAL LOOP.
  
  DO JLEV=KLEV - 1,KTDIA,-1
    
    !     PARTIE "LINEAIRE" DU CALCUL.
    !     "LINEAR" PART OF THE COMPUTATION.
    
    ZAUSR = 0.5_JPRB*((ZU(JLON, JLEV) + ZU(JLON, JLEV + 1))*ZUSUR + (ZV(JLON, JLEV) + ZV(JLON, JLEV + 1))*ZVSUR)
    ZPRRAP = ZFACS*ZAUSR**3 / MAX(ZEPS3, ZNFNO(JLON, JLEV))
    ZRAPP(JLON, JLEV) = MAX(0.0_JPRB, MIN(ZRAPP(JLON, JLEV + 1), ZPRRAP))
    
    !     PARTIE "AMPLIFICATION RESONANTE" DU CALCUL.
    !     "RESONNANT AMPLIFICATION" PART OF THE COMPUTATION.
    
    ZTST1 = ZTST1*MAX(0.0_JPRB, SIGN(1.0_JPRB, ZPRRAP - 1.0_JPRB))
    ZPR1 = ZPR1 + ZTST1*(PAPRSF(JLON, JLEV) - ZPR1)
    ZSUM = ZSUM + ZTST1*(PAPRSF(JLON, JLEV + 1) - PAPRSF(JLON, JLEV))*ZNFNO(JLON, JLEV)*ZUSR / MAX(ZEPS2, ZAUSR)
    
    !     PARTIE "REFLEXION ET DISSIPATION AVAL" DU CALCUL.
    !     "REFLEXION AND DOWNSTREAM DISSIPATION" PART OF THE COMPUTATION.
    
    ZTST2 = ZTST2*(1.0_JPRB - MAX(0.0_JPRB, SIGN(1.0_JPRB, 0.0_JPRB - ZNFNO(JLON, JLEV))))
    ZPR2 = ZPR2 + ZTST2*(PAPRSF(JLON, JLEV) - ZPR2)
    ZREF = ZREF + ZTST2*(ZRAPP(JLON, JLEV) - ZREF)
  END DO
  
  !     CONDITION A LA LIMITE SUPERIEURE ET PREPARATION DE LA BOUCLE
  !     DESCENDANTE.
  !     UPPER BOUNDARY CONDITION AND PREPARATION OF THE DESCENDING LOOP.
  
  !DEC$ IVDEP
  
  !     PARTIE "LINEAIRE" DU CALCUL.
  !     "LINEAR" PART OF THE COMPUTATION.
  
  PSTRDU(JLON, KTDIA - 1) = 0.0_JPRB
  PSTRDV(JLON, KTDIA - 1) = 0.0_JPRB
  ZRAPP(JLON, KTDIA - 1) = 0.0_JPRB
  PRAPTRAJ(JLON, KTDIA - 1) = 0.0_JPRB
  
  !     PARTIE "AMPLIFICATION RESONANTE" DU CALCUL.
  !     "RESONNANT AMPLIFICATION" PART OF THE COMPUTATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZSTM      : VALEUR MAXIMALE RELATIVE DU FLUX.
  !            : MAXIMUM RELATIVE VALUE OF THE FLUX.
  ! ZDS1      : DERIVEE EN PRESSION POUR LA PARTIE "PIEGEE".
  !            : PRESSURE DERIVATIVE FOR THE "TRAPPED" PART.
  
  ZSTM = 1.0_JPRB / SQRT(1.0_JPRB + MAX(0.0_JPRB, SIGN(1.0_JPRB, ZPR1 - ZPR2 - ZEPS4)) &
  & *YDML_PHY_MF%YRPHY0%GWDAMP*(2.0_JPRB*SIN(MIN(ZARGLI, ZSUM)) + YDML_PHY_MF%YRPHY0%GWDAMP))
  
  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
    ZSTM = ZSTM / (1.0_JPRB - ZZBB)
    ZREF = ZREF / (1.0_JPRB - ZZBB)
  END IF
  
  ZDS1 = MAX(0.0_JPRB, ZSTM - 1.0_JPRB) / (PAPRS(JLON, KLEV) - ZPR1)
  
  !     PARTIE "REFLEXION ET DISSIPATION AVAL" DU CALCUL.
  !     "REFLEXION AND DOWNSTREAM DISSIPATION" PART OF THE COMPUTATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZSTS      : VALEUR RELATIVE DU FLUX A LA REFLEXION (SI ELLE A LIEU).
  !            : RELATIVE VALUE OF THE FLUX AT REFLEXION (IF ANY).
  ! ZDS2      : DERIVEE EN PRESSION POUR LA PARTIE "AVAL".
  !            : PRESSURE DERIVATIVE FOR THE "DOWNSTREAM" PART.
  
  ZSTS = MIN(ZREF*(1.0_JPRB - ZTST2), ZSTM)
  ZDS2 = ZSTS / (PAPRS(JLON, KLEV) - ZPR2)
  
  !*
  !     ------------------------------------------------------------------
  !     V - BOUCLE DESCENDANTE POUR LA COMBINAISON DES EFFETS ET LES
  !     SECURITES NUMERIQUES CONDUISANT AU CALCUL DEFINITIF DES FLUX.
  
  !         DESCENDING LOOP FOR THE COMBINATION OF EFFECTS AND THE
  !     NUMERICAL SECURITIES LEADING TO THE FINAL FLUX CALCULATION.
  
  !     FLUX PROVISOIRES PRENANT EN COMPTE LES TROIS EFFETS.
  !     PROVISIONAL FLUXES TAKING INTO ACOUNT ALL THREE EFFECTS.
  
  ZZCR = ZRAPP(JLON, KLEV)*ZSTM
  
  DO JLEV=KTDIA,KLEV
    ZRAPP(JLON, JLEV) = ZDS2*MAX(0.0_JPRB, PAPRS(JLON, JLEV) - ZPR2) + MAX(0.0_JPRB, MIN(ZSTM, ZRAPP(JLON, JLEV) +  &
    & ZDS1*MAX(0.0_JPRB, PAPRS(JLON, JLEV) - ZPR1)) - ZSTS)
    ZRZ = (PAPRS(JLON, KLEV) - PAPRS(JLON, JLEV)) / MAX(ZEPS4, ZZBB*YDML_PHY_MF%YRPHY0%HOBST*PGETRL(JLON)*PGWDCS(JLON))
    
    IF (.not.YDML_PHY_MF%YRPHY%LNEWD) THEN
      ZZCR = ZRAPP(JLON, JLEV)
      ZRZR = 1.0_JPRB
      ZRZ = MIN(1.0_JPRB, ZRZ)
    ELSE
      ZRZR = SQRT(ZZBB / (1.0_JPRB + ZRZ**2*ZZBB*(1.0_JPRB - ZZBB)))
    END IF
    
    ZRAPP(JLON, JLEV) = ZRAPP(JLON, JLEV) + ZZCR*(ZZAA*SQRT(MAX(0.0_JPRB, (1.0_JPRB - ZRZ*ZRZR)**3 / (1.0_JPRB +  &
    & ZRZ*YDML_PHY_MF%YRPHY0%GWDPROF*ZZBB))))
  END DO
  
  ZZCR = ZRAPP(JLON, KTDIA - 1)
  
  DO JLEV=KTDIA,KLEV
    !DEC$ IVDEP
    ZDIFSR = ZRAPP(JLON, JLEV) - ZZCR
    ZZCR = ZRAPP(JLON, JLEV)
    ZALTI = MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRSF(JLON, JLEV)) / ZOBST)
    ZRAPP(JLON, JLEV) = ZRAPP(JLON, JLEV - 1) + ZDIFSR*(1.0_JPRB + ZLIFTG*(1.0_JPRB - ZALTI) / (1.0_JPRB +  &
    & ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF))*(1.0_JPRB - ZBETA*((1.0_JPRB - ZALTI) / (1.0_JPRB + YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
    PSTRDU(JLON, JLEV) = ZRAPP(JLON, JLEV)*ZSTUS
    PSTRDV(JLON, JLEV) = ZRAPP(JLON, JLEV)*ZSTVS
    PRAPTRAJ(JLON, JLEV) = PRAPTRAJ(JLON, JLEV)*ZRAPP(JLON, JLEV)
  END DO
  
  !     MISE EN PSEUDO-IMPLICITE PAR RAPPORT AU VENT DE SURFACE EFFECTIF
  !     PROJETE SUR LA DIRECTION DU STRESS.
  !     PSEUDO-IMPLICIT ALGORITHM WITH RESPECT TO THE EFFECTIVE SURFACE
  !     WIND PROJECTED ON THE STRESS DIRECTION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZSUMD     : MOYENNE DES TENDANCES DU VENT PROJETE SUR LE STRESS.
  !            : AVERAGED WIND TENDENCIES PROJECTED ON THE STRESS' DIREC..
  
  !     SOMMATION POUR UNE MOYENNE DE TENDANCES PROVISOIREMENT NORMEE.
  !     SUMMATION FOR A TEMPORARY NORMALISED AVERAGE OF TENDENCIES.
  
  ZSUMD = 0.5_JPRB*ZWGHT(JLON, ITOP)*ZIPOI(JLON, ITOP)*(ZRAPP(JLON, ITOP) - ZRAPP(JLON, ITOP - 1))
  
  DO JLEV=ITOP + 1,KLEV
    ZSUMD =  &
    & ZSUMD + 0.5_JPRB*(ZWGHT(JLON, JLEV) + ZWGHT(JLON, JLEV - 1))*ZIPOI(JLON, JLEV)*(ZRAPP(JLON, JLEV) - ZRAPP(JLON, JLEV - 1))
  END DO
  
  ZSUMD = ZSUMD + 0.5_JPRB*ZWGHT(JLON, KLEV)*ZIPOI(JLON, KLEV)*(ZRAPP(JLON, KLEV) - ZRAPP(JLON, KLEV - 1))
  
  !     VALEUR FINALE DE LA MOYENNE, FACTEUR DE REDUCTION LINEAIRE ET SON
  !     APPLICATION.
  !     FINAL AVERAGED VALUE, LINEAR REDUCTION FACTOR AND ITS USE.
  
  ZSUMD = ZSUMD*SQRT(ZSTUS**2 + ZSTVS**2)
  ZRAPP(JLON, KLEV) = 1.0_JPRB / (1.0_JPRB + ZSUMD*ZUSR / ZSUSR)
  
  DO JLEV=KTDIA,KLEV
    PSTRDU(JLON, JLEV) = PSTRDU(JLON, JLEV)*ZRAPP(JLON, KLEV)
    PSTRDV(JLON, JLEV) = PSTRDV(JLON, JLEV)*ZRAPP(JLON, KLEV)
    PRAPTRAJ(JLON, JLEV) = PRAPTRAJ(JLON, JLEV)*ZRAPP(JLON, KLEV)
  END DO
  
  !     SECURITE NUMERIQUE (UTILISATION D'UN ALGORITHME INSPIRE DE CELUI
  !     DES ROUTINES DE CONVECTION PROFONDE A FLUX DE MASSE).
  !     NUMERICAL SECURITY (USE OF AN ALGORITHM INSPIRED BY THE ONE OF THE
  !     MASS-FLUX TYPE DEEP CONVECTION ROUTINES).
  
  DO JLEV=KTDIA,KLEV
    ZDU = ZIPOI(JLON, JLEV)*(PSTRDU(JLON, JLEV - 1) - PSTRDU(JLON, JLEV))
    ZDV = ZIPOI(JLON, JLEV)*(PSTRDV(JLON, JLEV - 1) - PSTRDV(JLON, JLEV))
    ZDX = ZIPOI(JLON, JLEV)*(ZUSUR*PSTRDU(JLON, JLEV) + ZVSUR*PSTRDV(JLON, JLEV))
    ZX = ZUSUR*PU(JLON, JLEV) + ZVSUR*PV(JLON, JLEV)
    ZALPHA = 1.0_JPRB / (1.0_JPRB + ZDX / MAX(ZEPS2, ZX))
    PSTRDU(JLON, JLEV) = PSTRDU(JLON, JLEV - 1) - ZPOID(JLON, JLEV)*ZALPHA*ZDU
    PSTRDV(JLON, JLEV) = PSTRDV(JLON, JLEV - 1) - ZPOID(JLON, JLEV)*ZALPHA*ZDV
  END DO
  
  ZZCU = PSTRDU(JLON, KTDIA - 1)
  ZZCV = PSTRDV(JLON, KTDIA - 1)
  
  DO JLEV=KTDIA,KLEV
    !DEC$ IVDEP
    ZDIFSU = PSTRDU(JLON, JLEV) - ZZCU
    ZDIFSV = PSTRDV(JLON, JLEV) - ZZCV
    ZZCU = PSTRDU(JLON, JLEV)
    ZZCV = PSTRDV(JLON, JLEV)
    ZALTI = MIN(1.0_JPRB, (PAPRS(JLON, KLEV) - PAPRSF(JLON, JLEV)) / ZOBST)
    ZFORCL = ZLIFT*PRCORI(JLON)*(1.0_JPRB - ZALTI) / (1.0_JPRB + ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF)
    ZFORCA = ZFORCL / (1.0_JPRB + 0.25_JPRB*ZFORCL**2)
    ZFORCB = 0.5_JPRB*ZFORCL*ZFORCA
    PSTRDU(JLON, JLEV) = PSTRDU(JLON, JLEV - 1) + ZDIFSU + ZPOID(JLON, JLEV)*(ZFORCB*PU(JLON, JLEV) - ZFORCA*PV(JLON, JLEV))
    PSTRDV(JLON, JLEV) = PSTRDV(JLON, JLEV - 1) + ZDIFSV + ZPOID(JLON, JLEV)*(ZFORCB*PV(JLON, JLEV) + ZFORCA*PU(JLON, JLEV))
  END DO
  
  !-----------------------------------------------------------------------
END SUBROUTINE ACDRAG_OPENACC
