SUBROUTINE ACNPART_CLOUD_COVER_WMO_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PDECRDRED, PWMXOV, PDECRD,  &
& PNEB, PAPHI, PAPRSF, PCLCH, PCLCM, PCLCL, YDSTACK)
  
!$acc routine( ACNPART_CLOUD_COVER_WMO_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE STACK_MOD
#include "stack.h"
  
  USE YOMCST, ONLY: TCST
  
  ! Interface:
  ! ----------
  ! INPUT:
  !   PNEB   - cloud cover on levels
  !   PAPHI  - half level geopotential
  !   PAPRSF - full level pressure
  
  ! OUTPUT:
  !   PCLCH  - high cloud cover
  !   PCLCM  - medium cloud cover
  !   PCLCL  - low cloud cover
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  REAL(KIND=JPRB), INTENT(IN) :: PDECRDRED
  REAL(KIND=JPRB), INTENT(IN) :: PWMXOV
  
  REAL(KIND=JPRB), INTENT(IN) :: PDECRD(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PNEB(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PCLCH(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PCLCM(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PCLCL(KLON)
  
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JLEV
  
  REAL(KIND=JPRB) :: ZCLOV
  REAL(KIND=JPRB) :: ZH
  REAL(KIND=JPRB) :: ZL
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  REAL(KIND=JPRB) :: ZOVLP
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KIDIA
  YLSTACK = YDSTACK
  
  
  ! initialize high cloud cover or its complement
  IF (YDML_PHY_MF%YRPHY%LRNUMX .and. YDML_PHY_MF%YRPHY%LACPANMX) THEN
    PCLCH(JLON) = 1._JPRB - PNEB(JLON, KTDIA)
  ELSE
    PCLCH(JLON) = PNEB(JLON, KTDIA)
  END IF
  
  ! compute cloud cover using actual overlap hypothesis
  DO JLEV=KTDIA + 1,KLEV - 1
    IF (YDML_PHY_MF%YRPHY%LRNUMX .and. YDML_PHY_MF%YRPHY%LACPANMX) THEN
      
      ! nearly maximum-random overlap
      ZOVLP = MIN(1.0_JPRB - PNEB(JLON, JLEV), 1.0_JPRB - PWMXOV*PNEB(JLON, JLEV - 1)) / (1.0_JPRB - PWMXOV*PNEB(JLON, JLEV - 1))
      
    ELSE IF (YDML_PHY_MF%YRPHY%LRNUMX .and. YDML_PHY_MF%YRPHY%LRNUEXP) THEN
      
      ! exponential-random overlap
      ZCLOV = EXP((PAPRSF(JLON, JLEV - 1) - PAPRSF(JLON, JLEV)) / (PDECRDRED*PDECRD(JLON)))
      ZOVLP = (1._JPRB - ZCLOV)*PNEB(JLON, JLEV)*PNEB(JLON, JLEV - 1) + ZCLOV*MIN(PNEB(JLON, JLEV), PNEB(JLON, JLEV - 1))
      
    ELSE IF (YDML_PHY_MF%YRPHY%LRNUMX) THEN
      
      ! maximum-random overlap
      ZOVLP = MIN(PNEB(JLON, JLEV), PNEB(JLON, JLEV - 1))
      
    ELSE
      
      ! random overlap
      ZOVLP = PNEB(JLON, JLEV)*PNEB(JLON, JLEV - 1)
      
    END IF
    
    ! update cloud cover
    IF (YDML_PHY_MF%YRPHY%LRNUMX .and. YDML_PHY_MF%YRPHY%LACPANMX) THEN
      ZL = (PAPHI(JLON, JLEV - 1) - PAPHI(JLON, KLEV)) / YDCST%RG
      ZH = (PAPHI(JLON, JLEV - 2) - PAPHI(JLON, KLEV)) / YDCST%RG
      IF (ZL >= YDML_PHY_MF%YRPHY2%HWMOHIGH) THEN
        PCLCH(JLON) = PCLCH(JLON)*ZOVLP
      ELSE IF (ZH >= YDML_PHY_MF%YRPHY2%HWMOHIGH) THEN
        PCLCM(JLON) = 1._JPRB - PNEB(JLON, JLEV)          ! complement of medium cloud cover
      ELSE IF (ZL >= YDML_PHY_MF%YRPHY2%HWMOLOW) THEN
        PCLCM(JLON) = PCLCM(JLON)*ZOVLP
      ELSE IF (ZH >= YDML_PHY_MF%YRPHY2%HWMOLOW) THEN
        PCLCL(JLON) = 1._JPRB - PNEB(JLON, JLEV)          ! complement of low cloud cover
      ELSE
        PCLCL(JLON) = PCLCL(JLON)*ZOVLP
      END IF
    ELSE
      ZL = (PAPHI(JLON, JLEV - 1) - PAPHI(JLON, KLEV)) / YDCST%RG
      ZH = (PAPHI(JLON, JLEV - 2) - PAPHI(JLON, KLEV)) / YDCST%RG
      IF (ZL >= YDML_PHY_MF%YRPHY2%HWMOHIGH) THEN
        PCLCH(JLON) = PCLCH(JLON) + (PNEB(JLON, JLEV) - ZOVLP)*(1._JPRB - PCLCH(JLON)) / (1._JPRB - PNEB(JLON, JLEV - 1))
      ELSE IF (ZH >= YDML_PHY_MF%YRPHY2%HWMOHIGH) THEN
        PCLCM(JLON) = PNEB(JLON, JLEV)          ! initialize medium cloud cover
      ELSE IF (ZL >= YDML_PHY_MF%YRPHY2%HWMOLOW) THEN
        PCLCM(JLON) = PCLCM(JLON) + (PNEB(JLON, JLEV) - ZOVLP)*(1._JPRB - PCLCM(JLON)) / (1._JPRB - PNEB(JLON, JLEV - 1))
      ELSE IF (ZH >= YDML_PHY_MF%YRPHY2%HWMOLOW) THEN
        PCLCL(JLON) = PNEB(JLON, JLEV)          ! initialize low cloud cover
      ELSE
        PCLCL(JLON) = PCLCL(JLON) + (PNEB(JLON, JLEV) - ZOVLP)*(1._JPRB - PCLCL(JLON)) / (1._JPRB - PNEB(JLON, JLEV - 1))
      END IF
    END IF
    
  END DO
  
  ! convert complement of cloud cover to cloud cover
  IF (YDML_PHY_MF%YRPHY%LRNUMX .and. YDML_PHY_MF%YRPHY%LACPANMX) THEN
    PCLCH(JLON) = 1._JPRB - PCLCH(JLON)
    PCLCM(JLON) = 1._JPRB - PCLCM(JLON)
    PCLCL(JLON) = 1._JPRB - PCLCL(JLON)
  END IF
  
  
END SUBROUTINE ACNPART_CLOUD_COVER_WMO_OPENACC
