# (C) Copyright 2023- ECMWF.
# (C) Copyright 2023- Meteo-France.

true_symbols=['YDMODEL%YRML_DYN%YRDYN%LADVF', 'YDMODEL%YRML_DYN%YRDYNA%LTWOTL', 'YDGEOMETRY%YRCVER%LVERTFE', 'YDGEOMETRY%YRVERT_GEOM%YRCVER%LVERTFE', 'YDMODEL%YRML_DYN%YRDYNA%LSPRT', 'YDMODEL%YRML_DYN%YRDYNA%LSLAG']
false_symbols=['YDMODEL%YRML_DYN%YRDYN%LRHS_CURV', 'YDMODEL%YRML_DYN%YRDYN%LSPLTHOIGFL', 'YDMODEL%YRML_DYN%YRDYNA%LSLDIA', 'YDMODEL%YRML_DYN%YRDYNA%LNHDYN', 'YDMODEL%YRML_DYN%YRDYNA%LGWADV', 'YDMODEL%YRML_DYN%YRDYNA%LPC_FULL', 'YDMODEL%YRML_DYN%YRDYNA%LPC_CHEAP', 'YDMODEL%YRML_DYN%YRDYNA%LMIXETTLS', 'YDMODEL%YRML_DYN%YRDYNA%LCOMAD', 'YDMODEL%YRML_DYN%YRDYNA%LSLHD', 'YDMODEL%YRML_PHY_SLIN%YRPHLC%LSPHLC', 'YDMODEL%YRML_DYN%YRDYNA%LNHEE', 'YDMODEL%YRML_DYN%YRDYNA%LNHQE', 'YDMODEL%YRML_DYN%YRDYNA%LELTRA', 'YDMODEL%YRML_DYN%YRDYNA%LSVTSM' 'YDMODEL%YRML_DYN%YRDYNA%LSLINL', 'YDMODEL%YRML_DYN%YRDYNA%LSACC', 'LLCT', 'LLCTC', 'YDMODEL%YRML_PHY_EC%YREPHY%LSLPHY', 'YDCPG_OPTS%LSFORC', 'LGWDIAGS_ON', 'YDMODEL%YRML_DYN%YRSPNG%LNSPONGE', 'YDCPG_OPTS%LNUDG', 'YDMODEL%YRML_LBC%LTENC', 'YDMODEL%YRML_DIAG%YRLDDH%LRSLDDH', 'YDMODEL%YRML_DIAG%YRLDDH%LSDDH', 'YDCPG_OPTS%LSLPHY', 'YDMODEL%YRML_PHY_EC%YRECUCONVCA%LCUCONV_CA', 'YDMODEL%YRML_PHY_MF%YRSIMPHL%LTRAJPS', 'LTRAJSAVE']

false_symbols2=['LMUSCLFA', 'YDLDDH%LFLEXDIA', 'YDMODEL%YRML_DIAG%YRLDDH%LFLEXDIA', 'YDSPP_CONFIG%LSPP', 'LMCAPEA', 'OCH1CONV']
