INTERFACE
  SUBROUTINE ACCLPH_OPENACC (YDCST, YDPHY0, YDPHY2, KIDIA, KFDIA, KLON, KTDIA, KLEV, PTHETAV, PAPHI, PAPHIF, PU, PV, PTHETAVS,  &
  & KCLPH, PCLPH, PVEIN, PUGST, PVGST, YDSTACK)
!$acc routine( ACCLPH_OPENACC )
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    USE YOMCST, ONLY: TCST
    USE YOMPHY0, ONLY: TPHY0
    USE YOMPHY2, ONLY: TPHY2
    
    !-----------------------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(TCST), INTENT(IN) :: YDCST
    TYPE(TPHY0), INTENT(IN) :: YDPHY0
    TYPE(TPHY2), INTENT(IN) :: YDPHY2
    INTEGER(KIND=JPIM), INTENT(IN) :: KLON
    INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
    INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
    REAL(KIND=JPRB), INTENT(IN) :: PTHETAV(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON, 0:KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PU(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PV(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PTHETAVS(KLON)
    INTEGER(KIND=JPIM), INTENT(OUT) :: KCLPH(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PCLPH(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PVEIN(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PUGST(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PVGST(KLON)
    
    !-----------------------------------------------------------------------
    
    
    ! ZCLPU :: VENT "U" AU SOMMET DE LA CLP
    ! ZCLPV :: VENT "V" AU SOMMET DE LA CLP
    
    ! ZVITM   :: VITESSE DU VENT MOYEN VERTICAL DANS LA CLP
    
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE ACCLPH_OPENACC
END INTERFACE
