INTERFACE
  SUBROUTINE ACNPART_CLOUD_COVER_WMO_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PDECRDRED, PWMXOV, PDECRD,  &
  & PNEB, PAPHI, PAPRSF, PCLCH, PCLCM, PCLCL, YDSTACK)
!$acc routine( ACNPART_CLOUD_COVER_WMO_OPENACC )
    
    USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    USE STACK_MOD
    
    USE YOMCST, ONLY: TCST
    
    ! Interface:
    ! ----------
    ! INPUT:
    !   PNEB   - cloud cover on levels
    !   PAPHI  - half level geopotential
    !   PAPRSF - full level pressure
    
    ! OUTPUT:
    !   PCLCH  - high cloud cover
    !   PCLCM  - medium cloud cover
    !   PCLCL  - low cloud cover
    
    TYPE(TCST), INTENT(IN) :: YDCST
    TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
    INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KLON
    INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
    REAL(KIND=JPRB), INTENT(IN) :: PDECRDRED
    REAL(KIND=JPRB), INTENT(IN) :: PWMXOV
    
    REAL(KIND=JPRB), INTENT(IN) :: PDECRD(KLON)
    REAL(KIND=JPRB), INTENT(IN) :: PNEB(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON, 0:KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PCLCH(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PCLCM(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PCLCL(KLON)
    
    
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE ACNPART_CLOUD_COVER_WMO_OPENACC
END INTERFACE
