INTERFACE
  SUBROUTINE CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP, LD_LCUMASK, PA, PB, PR, PU, YDSTACK)
!$acc routine( CUBIDIAG_OPENACC )
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    !     DUMMY INTEGER
    INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KLON
    INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
    INTEGER(KIND=JPIM), INTENT(IN) :: KCTOP(KLON)
    LOGICAL, INTENT(IN) :: LD_LCUMASK(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PA(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PB(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PR(KLON, KLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PU(KLON, KLEV)
    !     DUMMY REALS
    !     DUMMY LOGICALS
    !     LOCALS
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE CUBIDIAG_OPENACC
END INTERFACE
