SUBROUTINE ACNPART_CONV_BASE_TOP_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PNEBC, PAPRSF, PAPHIF, PTOPC,  &
& YDSTACK)
  
!$acc routine( ACNPART_CONV_BASE_TOP_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE YOMCST, ONLY: TCST
  
  ! TOP  of convective cloud
  ! If BASE is needed, add PBASEC in the arguments of this subroutine.
  
  ! Interface:
  ! ----------
  ! INPUT:
  !   PNEBC     - convective cloud cover on levels (protected from 0 and 1,
  !               missing in AROME)
  !   PAPRSF    - full level pressure
  ! OUTPUT :
  !!   PBASEC    - BASE of convective cloud [Pa]
  !   PTOPC     - TOP of convective cloud  [Pa]
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  
  REAL(KIND=JPRB), INTENT(IN) :: PNEBC(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON, KLEV)
  !REAL(KIND=JPRB)  ,INTENT(OUT)   :: PBASEC(KLON) ! Base desactivated
  REAL(KIND=JPRB), INTENT(OUT) :: PTOPC
  
  REAL(KIND=JPRB) :: ZNCCRIT
  REAL(KIND=JPRB) :: ZALPHA
  REAL(KIND=JPRB) :: ZBETA
  REAL(KIND=JPRB) :: ZABINV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JCTOP
  INTEGER(KIND=JPIM) :: JCBASE
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  USE STACK_MOD
#include "stack.h"
  
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KIDIA
  
  
  ZNCCRIT = 0.1_JPRB
  JCTOP = KLEV
  JCBASE = KLEV
  ! Recherche de la base et du sommet
  DO JLEV=KLEV - 1,1,-1
    !On renverse la coordonnees verticale (KLEV-JLEV),
    JCTOP = KLEV - MAX((KLEV - JLEV)*INT(SIGN(1._JPRB, PNEBC(JLON, JLEV) - ZNCCRIT)), (KLEV - JCTOP))
    JCBASE = KLEV - MAX((KLEV - JLEV)*SIGN(1_JPIM, JCTOP - KLEV), KLEV - JCBASE)
  END DO
  ! Critere epaisseur
  !If NEBUL < 10%, JCBASE=1 et JCTOP=KLEV
  JCTOP = KLEV - MAX((KLEV - JCTOP)*INT(SIGN(1._JPRB, ((PAPHIF(JLON, JCTOP) - PAPHIF(JLON, JCBASE)) / YDCST%RG) -  &
  & YDML_PHY_MF%YRPHY0%GTOPDEPTH)), 0_JPIM)
  
  !Mise à KLEV si pas de base convective
  !JCBASE(JLON)=MAX(SIGN(1_JPIM,JCBASE(JLON)-2_JPIM),0_JPIM)*JCBASE(JLON)&
  !          & +MAX(SIGN(1_JPIM,1_JPIM-JCBASE(JLON)),0_JPIM)*KLEV
  
  ! Interpolation lineaire sur Z de la base
  !ZALPHA(JLON)=ABS(PNEBC(JLON,JCBASE(JLON)-1_JPIM)-ZNCCRIT) !danger
  !ZBETA(JLON)= ABS(ZNCCRIT-PNEBC(JLON,JCBASE(JLON)))
  !ZABINV(JLON)=1._JPRB/(ZALPHA(JLON)+ZBETA(JLON))
  !PBASEC(JLON)=PAPRSF(JLON,JCBASE(JLON))*ZALPHA(JLON)*ZABINV(JLON) &
  !     & + PAPRSF(JLON,JCBASE(JLON)-1_JPIM)*ZBETA(JLON)*ZABINV(JLON)
  
  ! Interpolation lineaire sur P du sommet
  ZALPHA = ABS(PNEBC(JLON, JCTOP) - ZNCCRIT)
  ZBETA = ABS(ZNCCRIT - PNEBC(JLON, JCTOP - 1_JPIM))
  ZABINV = 1._JPRB / (ZALPHA + ZBETA)
  PTOPC = PAPRSF(JLON, JCTOP)*ZBETA*ZABINV + PAPRSF(JLON, JCTOP - 1_JPIM)*ZALPHA*ZABINV
  
  PTOPC = PAPRSF(JLON, KLEV)*FLOAT(MAX(0_JPIM, SIGN(1_JPIM, JCTOP - KLEV))) + PTOPC*FLOAT(MAX(0_JPIM, SIGN(1_JPIM, KLEV - JCTOP - &
  &  1_JPIM)))
  
  
  
END SUBROUTINE ACNPART_CONV_BASE_TOP_OPENACC
