SUBROUTINE ACSOL_OPENACC (YDCLI, YDCST, YDPHY, YDPHY1, KIDIA, KFDIA, KLON, PARG, PD2, PGZ0F, PGZ0HF, PGZ0RLF, PLSM, PIVEG, PLAI,  &
& PALBNS, PRHONS, PSAB, PSNS, PTS, PVEG0, PWP, PWPI, PWS, PWSI, LDHMT, PC1, PC2, PC3, PCG, PCN, PCT, PNEIJG, PNEIJV, PWFC,  &
& PWPMX, PWSEQ, PWSMX, PWWILT, YDSTACK)
  !-----------------------------------------------------------------------
  ! - INPUT  1D
  ! - INPUT  LOGIQUE
  ! - OUTPUT 1D .
  
  !**** *ACSOL  * - DETERMINATION DES CARACTERISTIQUES DE SURFACE.
  
  !     Sujet.
  !     ------
  
  !     - ROUTINE DE CALCUL ACTIF .
  !       DETERMINATION DES CARACTERISTIQUES DE SURFACE CONCERNANT LES
  !       COEFFICIENTS THERMO-HYDRIQUES, LES TENEURS EN EAU MAXIMALES
  !       DES RESERVOIRS PROFOND ET SUPERFICIEL AINSI QUE LA TENEUR EN
  !       EAU A L'EQUILIBRE DU RESERVOIR SUPERFICIEL.
  !       CAS DE L EAU: ON POSE C1=C2=1.
  
  !**   Interface.
  !     ----------
  !        *CALL* *ACSOL*
  
  !-----------------------------------------------------------------------
  ! WARNING: THE ENGLISH VERSION OF VARIABLES' NAMES IS TO BE READ IN THE
  !          "APLPAR" CODE.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS D'ENTREE.
  !     -------------------
  
  ! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.
  
  ! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
  ! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
  ! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
  
  ! - NOM DES CLES LOGIQUES
  
  ! LDHMT      : ETAPE DANS LE CALCUL DES CHAMPS AUX HAUTEURS METEO
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 1D (PROGNOSTIQUE) .
  
  ! PRHONS     : DENSITE DE LA NEIGE.
  ! PSNS       : MASSE DE NEIGE PAR UNITE DE SURFACE.
  ! PTS        : TEMPERATURE DE SURFACE.
  ! PWP        : CONTENU EN EAU DU RESERVOIR PROFOND.
  ! PWPI       : CONTENU EN EAU GELEE DU RESERVOIR PROFOND.
  ! PWS        : CONTENU EN EAU DU RESERVOIR DE SURFACE.
  ! PWSI       : CONTENU EN EAU GELEE DU RESERVOIR DE SURFACE.
  
  ! - 1D (GEOGRAPHIQUE) .
  
  ! PARG       : POURCENTAGE D'ARGILE DANS LA MAILLE.
  ! PD2        : EPAISSEUR DU RESERVOIR PROFOND.
  ! PGZ0F      : GRAVITE * LONGUEUR DE RUGOSITE.
  ! PGZ0HF     : GRAVITE * LONGUEUR DE RUGOSITE THERMIQUE.
  ! PGZ0RLF    : GRAVITE * LONGUEUR DE RUGOSITE DUE AU RELIEF.
  ! PLSM       : INDICE TERRE/MER.
  ! PIVEG      : TYPE DE SURFACE (MER, BANQUISE OU GLACIER, TERRE).
  ! PLAI       : INDICE FOLIAIRE.
  ! PALBNS     : ALBEDO DE LA NEIGE.
  ! PSAB       : POURCENTAGE DE SABLE DANS LA MAILLE.
  ! PVEG0      : PROPORTION DE SOL COUVERT PAR LA VEGETATION.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS DE SORTIE.
  !     --------------------
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 1D (DIAGNOSTIQUE) .
  
  ! PC1        : COEFFICIENT HYDRIQUE REPRESENTANT L'INTENSITE AVEC LAQUEL
  !              LES FLUX DE SURFACE PARTICIPENT A L'EVOLUTION DE WS.
  ! PC2        : COEFFICIENT HYDRIQUE TRADUISANT LA RAPIDITE DES TRANSFERT
  !              D'EAU ENTRE LES RESERVOIRS PROFOND ET DE SURFACE.
  ! PC3        : COEFFICIENT UTILE POUR LE CALCUL DU DRAINAGE
  ! PCG        : COEFFICIENT THERMIQUE DU SOL NU.
  ! PCN        : COEFFICIENT THERMIQUE DE LA NEIGE.
  ! PCT        : COEFFICIENT THERMIQUE DU MILIEU SOL-VEGETATION.
  ! PNEIJG     : FRACTION DE NEIGE RECOUVRANT LE SOL.
  ! PNEIJV     : FRACTION DE NEIGE RECOUVRANT LA VEGETATION.
  ! PWFC       : TENEUR EN EAU A LA CAPACITE AUX CHAMPS.
  ! PWPMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR PROFOND.
  ! PWSEQ      : TENEUR EN EAU A L'EQUILIBRE POUR LE RESERVOIR DE SURFACE.
  !              (EQUILIBRE ENTRE FORCES DE GRAVITE ET CAPILLARITE).
  ! PWSMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR DE SURFACE.
  ! PWWILT     : TENEUR EN EAU CORRESPONDANT AU POINT DE FLETRISSEMENT.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS IMPLICITES.
  !     ---------------------
  
  !-----------------------------------------------------------------------
  
  !     Externes :  ACSOLW
  !     ---------
  
  !     Methode.
  !     --------
  
  !     Auteur.
  !     -------
  !      91-12, J. Noilhan.
  
  !     Modifications.
  !     --------------
  !      R. El Khatib : 01-08-07 Pruning options
  !      M.Hamrud      01-Oct-2003 CY28 Cleaning
  !      K. Yessad (Jul 2009): remove CDLOCK + some cleanings
  !      2011-06: M. Jerczynski - some cleaning to meet norms
  !      2012-12: E. Bazile and E. Brun - change of soil inertia for ice Cap.
  !      2018-09, J. Masek: Calculation of snow fractions for LVGSN=T moved
  !        here from APLPAR. Coding of ALARO-1 fixes for LZ0HSREL=T.
  !     P. Marguinaud June 2022 refactor YOMCLI to a structure YDCLI
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( ACSOL_OPENACC ) seq
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMPHY1, ONLY: TPHY1
  USE YOMPHY, ONLY: TPHY
  USE YOMCST, ONLY: TCST
  USE YOMCLI, ONLY: TCLI
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCLI), INTENT(IN) :: YDCLI
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(TPHY), INTENT(IN) :: YDPHY
  TYPE(TPHY1), INTENT(IN) :: YDPHY1
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  REAL(KIND=JPRB), INTENT(IN) :: PARG
  REAL(KIND=JPRB), INTENT(IN) :: PD2
  REAL(KIND=JPRB), INTENT(IN) :: PGZ0F
  REAL(KIND=JPRB), INTENT(IN) :: PGZ0HF
  REAL(KIND=JPRB), INTENT(IN) :: PGZ0RLF
  REAL(KIND=JPRB), INTENT(IN) :: PLSM
  REAL(KIND=JPRB), INTENT(IN) :: PIVEG
  REAL(KIND=JPRB), INTENT(IN) :: PLAI
  REAL(KIND=JPRB), INTENT(IN) :: PALBNS
  REAL(KIND=JPRB), INTENT(IN) :: PRHONS
  REAL(KIND=JPRB), INTENT(IN) :: PSAB
  REAL(KIND=JPRB), INTENT(INOUT) :: PSNS
  REAL(KIND=JPRB), INTENT(IN) :: PTS
  REAL(KIND=JPRB), INTENT(IN) :: PVEG0
  REAL(KIND=JPRB), INTENT(IN) :: PWP
  REAL(KIND=JPRB), INTENT(IN) :: PWPI
  REAL(KIND=JPRB), INTENT(IN) :: PWS
  REAL(KIND=JPRB), INTENT(IN) :: PWSI
  LOGICAL, INTENT(IN) :: LDHMT
  REAL(KIND=JPRB), INTENT(INOUT) :: PC1
  REAL(KIND=JPRB), INTENT(OUT) :: PC2
  REAL(KIND=JPRB), INTENT(OUT) :: PC3
  REAL(KIND=JPRB), INTENT(INOUT) :: PCG
  REAL(KIND=JPRB), INTENT(OUT) :: PCN
  REAL(KIND=JPRB), INTENT(OUT) :: PCT
  REAL(KIND=JPRB), INTENT(OUT) :: PNEIJG
  REAL(KIND=JPRB), INTENT(INOUT) :: PNEIJV
  REAL(KIND=JPRB), INTENT(INOUT) :: PWFC
  REAL(KIND=JPRB), INTENT(OUT) :: PWPMX
  REAL(KIND=JPRB), INTENT(OUT) :: PWSEQ
  REAL(KIND=JPRB), INTENT(INOUT) :: PWSMX
  REAL(KIND=JPRB), INTENT(INOUT) :: PWWILT
  REAL(KIND=JPRB) :: ZWSAT
  
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPRB) :: Z1
  REAL(KIND=JPRB) :: Z2
  REAL(KIND=JPRB) :: ZA
  REAL(KIND=JPRB) :: ZARG
  REAL(KIND=JPRB) :: ZB
  REAL(KIND=JPRB) :: ZBWA
  REAL(KIND=JPRB) :: ZBWB
  REAL(KIND=JPRB) :: ZC1MAX
  REAL(KIND=JPRB) :: ZC1SAT
  REAL(KIND=JPRB) :: ZC1X2
  REAL(KIND=JPRB) :: ZC1Y2
  REAL(KIND=JPRB) :: ZC2REF
  REAL(KIND=JPRB) :: ZC3REF
  REAL(KIND=JPRB) :: ZCGSAT
  REAL(KIND=JPRB) :: ZCRIN
  REAL(KIND=JPRB) :: ZD1
  REAL(KIND=JPRB) :: ZD2
  REAL(KIND=JPRB) :: ZDELTA
  REAL(KIND=JPRB) :: ZEPS
  REAL(KIND=JPRB) :: ZEPS1
  REAL(KIND=JPRB) :: ZEPW
  REAL(KIND=JPRB) :: ZLYMY1
  REAL(KIND=JPRB) :: ZNEIJC
  REAL(KIND=JPRB) :: ZNEIJV
  REAL(KIND=JPRB) :: ZP
  REAL(KIND=JPRB) :: ZSAB
  REAL(KIND=JPRB) :: ZTS
  REAL(KIND=JPRB) :: ZTSVAR
  REAL(KIND=JPRB) :: ZWP
  REAL(KIND=JPRB) :: ZWPI
  REAL(KIND=JPRB) :: ZWPSWS
  REAL(KIND=JPRB) :: ZWS
  REAL(KIND=JPRB) :: ZWSSWS
  REAL(KIND=JPRB) :: ZZ0V
  REAL(KIND=JPRB) :: ZZA
  REAL(KIND=JPRB) :: ZZB
  REAL(KIND=JPRB) :: ZZC
  REAL(KIND=JPRB) :: ZCOEF
  REAL(KIND=JPRB) :: ZCFN
  REAL(KIND=JPRB) :: ZCK
  REAL(KIND=JPRB) :: Z0CR
  REAL(KIND=JPRB) :: ZUZ0CN
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  !-----------------------------------------------------------------------
  
#include "acsolw.intfb.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KIDIA
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  ZEPS = 1.E-1_JPRB
  ZEPS1 = 1.E-5_JPRB
  ZEPW = 1.E-2_JPRB
  ZTSVAR = MAX(0.0_JPRB, SIGN(1.0_JPRB, YDPHY1%GTSVAP))
  ZD1 = YDPHY1%RD1*YDPHY1%GCONV
  
  ! GOING TO GEOPOTENTIAL FOR CONSTANTS RELATED TO ROUGHNESS LENGTH OF SNOW
  Z0CR = YDCST%RG*YDPHY1%ALRCN1
  ZUZ0CN = 1.0_JPRB / (YDCST%RG*YDPHY1%ALRCN2)
  
  !     ------------------------------------------------------------------
  !     I - CALCULS DES TENEURS EN EAU DU SOL CARACTERISTIQUES
  !         --------------------------------------------------
  !         COMPUTING CHARACTERISTIC SOIL MOISTURES
  !         ---------------------------------------
  
  CALL ACSOLW_OPENACC(YDPHY1, KIDIA, KFDIA, KLON, PARG, PD2, PLSM, PIVEG, PSAB, LDHMT, PWFC, PWPMX, ZWSAT, PWSMX, PWWILT,  &
  & YDSTACK=YLSTACK)
  
  IF (.not.LDHMT) THEN
    
    !     ------------------------------------------------------------------
    !     II - CALCUL DES AUTRES CHAMPS
    !          ------------------------
    !          COMPUTING OTHER FIELDS
    !          ----------------------
    
    
    ! ** INTERMEDIAIRES NE DEPENDANT QUE DE LA TEXTURE **
    
    ZSAB = MAX(ZEPS, PSAB)
    ZARG = MAX(ZEPS, PARG)
    
    ZA = YDPHY1%GA*(ZARG**YDPHY1%EA)
    ZB = YDPHY1%G1B*ZARG + YDPHY1%G2B
    ZP = YDPHY1%G1P*ZARG + YDPHY1%G2P
    ZC1SAT = (YDPHY1%G1C1SAT*ZARG + YDPHY1%G2C1SAT)*YDPHY1%GC2
    ZCGSAT = YDPHY1%G1CGSAT*ZSAB + YDPHY1%G2CGSAT*ZARG + YDPHY1%G3CGSAT
    ZC2REF = YDPHY1%GC2REF*(ZARG**YDPHY1%EC2REF)
    ZC3REF = YDPHY1%GC31*(ZARG**YDPHY1%GC32)
    
    ! ** WSEQ **
    
    ZD2 = PD2*YDPHY1%GCONV
    
    ZWP = PWP / ZD2
    IF (YDPHY%LFGEL) THEN
      ZWPSWS = MAX(ZEPW, ZWP / MAX(ZEPW, ZWSAT - PWPI / ZD2))
    ELSE
      ZWPSWS = MAX(ZEPW, ZWP / ZWSAT)
    END IF
    IF (NINT(PIVEG) == YDPHY1%NTVGLA) ZWPSWS = 1.0_JPRB
    PWSEQ = (ZWPSWS - ZA*(ZWPSWS**ZP)*(1.0_JPRB - (ZWPSWS**(YDPHY1%GC3*ZP))))*PWSMX
    
    ! ** CAS DE LA MER - SEA **
    
    IF (NINT(PIVEG) == YDPHY1%NTVMER) THEN
      PSNS = 0.0_JPRB
      PNEIJG = 0.0_JPRB
      PNEIJV = 0.0_JPRB
      PCN = YDPHY1%RCTGLA
      PCG = ZCGSAT
      PCT = PCG
      PC1 = 100._JPRB*YDPHY1%RD1
      PC2 = 1.0_JPRB
      PC3 = 1.0_JPRB
      
    ELSE
      
      ! ** EXTENSION DE LA COUVERTURE NEIGEUSE - SNOW COVER **
      
      IF (YDPHY%LSNV) THEN
        PSNS = MAX(0.0_JPRB, PSNS)
        PNEIJG = PSNS / (PSNS + YDPHY1%WCRIN*(1.0_JPRB + PGZ0RLF*YDPHY1%XCRINR))
        ZZ0V = SQRT(MAX(0.0_JPRB, PGZ0F**2 - PGZ0RLF**2)) / YDCST%RG
        ZCRIN = MAX(YDPHY1%WCRING, PRHONS*YDPHY1%XCRINV*ZZ0V)
        PNEIJV = PNEIJG*(PSNS + YDPHY1%WCRING) / (PSNS + ZCRIN)
      ELSE IF (YDPHY%LVGSN) THEN
        IF (YDPHY%LZ0HSREL .and. YDPHY%LCOEFKSURF) THEN
          PNEIJG = PLSM*PSNS / (PSNS + YDPHY1%WCRIN*(1.0_JPRB + ZUZ0CN*PGZ0HF / YDCLI%STHER))
        ELSE
          PNEIJG = PLSM*PSNS / (PSNS + YDPHY1%WCRIN)
        END IF
        ZCFN = (1.0_JPRB - MAX(0.0_JPRB, MIN(1.0_JPRB, PLAI / YDPHY1%RLAIMX)))*MAX(0.0_JPRB, SIGN(1.0_JPRB, PLAI - YDPHY1%RLAI))  &
        & + (1.0_JPRB - MAX(0.0_JPRB, SIGN(1.0_JPRB, PLAI - YDPHY1%RLAI)))
        ZCK = MAX(0.0_JPRB, (YDPHY1%ALB1 - MAX(YDPHY1%ALB2, PALBNS))) / (YDPHY1%ALB1 - YDPHY1%ALB2)
        ZCOEF = ZCFN*ZCK + (1.0_JPRB - ZCK)
        PNEIJV = PNEIJG*ZCOEF
      END IF
      
      IF (NINT(PIVEG) /= YDPHY1%NTVGLA) THEN
        
        ! ** COEFFICIENTS THERMIQUES
        !    DU SOL NU CG, DE LA NEIGE CN ET DU MILIEU SOL-NEIGE-VEGETATION CT **
        ! ** THERMICAL COEFFICIENTS
        !    OF BARE SOIL CG, OF SNOW CN AND OF SOIL-SNOW-VEGETATION SYSTEM CT **
        
        ZBWB = YDPHY1%GC1*ZB / LOG(YDPHY1%GC2)
        IF (YDPHY1%LIMW) ZWPSWS = MAX(ZEPW, PWWILT / ZWSAT, ZWPSWS)
        PCG = ZCGSAT / (ZWPSWS**ZBWB)
        IF (YDPHY%LFGEL) THEN
          ZWPI = PWPI / MAX(PWP + PWPI, ZEPS1)
          PCG = 1.0_JPRB / ((1 - ZWPI) / PCG + ZWPI / YDPHY1%RCTGLA)
        END IF
        IF (YDPHY1%LIMC) PCG = MIN(YDPHY1%RCGMAX, PCG)
        IF (YDPHY%LSNV) THEN
          ZNEIJC = MIN(1.0_JPRB, PSNS / YDPHY1%WCRINC)
          ZNEIJV = MIN(ZNEIJC, PNEIJV)
          PCN = 2.0_JPRB*SQRT(YDPHY1%GSNC1 / (PRHONS**YDPHY1%GSNC2))
          PCT = 1.0_JPRB / ((1.0_JPRB - PVEG0)*(1.0_JPRB - ZNEIJC) / PCG + (1.0_JPRB - PVEG0)*ZNEIJC / PCN + PVEG0*ZNEIJV / PCN + &
          &  PVEG0*(1.0_JPRB - ZNEIJV) / YDPHY1%RCTVEG(NINT(PIVEG)))
        ELSE
          PCT = 1.0_JPRB / ((1.0_JPRB - PVEG0) / PCG + PVEG0 / YDPHY1%RCTVEG(NINT(PIVEG)))
        END IF
        
        ! ** COEFFICIENT HYDRAULIQUE C1 - HYDRAULIC COEFFICIENT C1 **
        
        ZBWA = YDPHY1%GC1*ZB + 1.0_JPRB
        IF (YDPHY%LFGEL) THEN
          ZWS = PWS + PWSI
        ELSE
          ZWS = PWS
        END IF
        ZWSSWS = MAX(ZEPW, ZWS / PWSMX)
        IF (YDPHY1%LIMW .and. .not.YDPHY1%LC1VAP) ZWSSWS = MAX(ZEPW, PWWILT / ZWSAT, ZWSSWS)
        PC1 = ZC1SAT*YDPHY1%RD1 / (ZWSSWS**ZBWA)
        IF (YDPHY1%LIMC .and. .not.YDPHY1%LC1VAP) PC1 = MIN(YDPHY1%RC1MAX*YDPHY1%RD1, PC1)
        
        IF (YDPHY1%LC1VAP .and. (ZWS / ZD1) < PWWILT) THEN
          ZTS = ZTSVAR*MAX(YDCST%RTT, PTS) + (1.0_JPRB - ZTSVAR)*(YDCST%RTT - YDPHY1%GTSVAP)
          ZC1MAX = (YDPHY1%GC1S1*PWWILT + YDPHY1%GC1S2)*ZTS + (YDPHY1%GC1S3*PWWILT + YDPHY1%GC1S4)
          ZC1X2 = PWWILT*ZD1
          ZC1Y2 = ZC1SAT / ((PWWILT / ZWSAT)**ZBWA)
          ZC1MAX = MAX(ZC1Y2, ZC1MAX)
          ZZA = LOG(ZC1Y2 / YDPHY1%GC1Y1)
          ZLYMY1 = LOG(ZC1MAX / YDPHY1%GC1Y1)
          ZZB = -2.0_JPRB*ZC1X2*ZLYMY1
          ZZC = ZC1X2**2*ZLYMY1
          ZDELTA = ZZB**2 - 4._JPRB*ZZA*ZZC
          ZDELTA = MAX(0.0_JPRB, ZDELTA)
          Z1 = (-ZZB - SQRT(ZDELTA)) / (2.0_JPRB*ZZA)
          Z2 = Z1**2 / ZLYMY1
          PC1 = ZC1MAX*YDPHY1%RD1*EXP(-(ZWS - Z1)**2 / Z2)
        END IF
        
        ! ** COEFFICIENTS HYDRAULIQUES C2, C3 - HYDRAULIC COEFFICIENTS C2, C3 **
        IF (YDPHY%LFGEL) THEN
          ZWP = ZWP + PWPI / ZD2
        END IF
        IF (YDPHY1%LIMW) ZWP = MAX(PWWILT, ZWP)
        PC2 = MAX(0.0_JPRB, ZC2REF*ZWP / (ZWSAT - ZWP + ZEPW))
        PC3 = ZC3REF / PD2
        
        ! ** CAS DE LA GLACE - ICE CAP **
        
      ELSE
        PCG = YDPHY1%RCTGLA
        IF (YDPHY%LGLACIERS) THEN
          ZNEIJC = MIN(1.0_JPRB, PSNS / YDPHY1%WCRINC)
          PCN = 2.0_JPRB*SQRT(YDPHY1%GSNC1 / (PRHONS**YDPHY1%GSNC2))
          PCT = 1.0_JPRB / ((1.0_JPRB - ZNEIJC) / PCG + ZNEIJC / PCN)
        ELSE
          PCN = YDPHY1%RCTGLA
          PCT = YDPHY1%RCTGLA
        END IF
        PC1 = 0.0_JPRB
        PC2 = 0.0_JPRB
        PC3 = 0.0_JPRB
      END IF
    END IF
    
    
  END IF
  
  
END SUBROUTINE ACSOL_OPENACC
