SUBROUTINE CPTEND_NEW_OPENACC (YDCST, YDMODEL, KLON, KIDIA, KFDIA, KFLEV, PGNORDL, PGNORDM, PDIFCQ, PDIFCQI, PDIFCQL, PDIFCS,  &
& PDIFEXT, PDIFTQ, PDIFTQI, PDIFTQL, PDIFTS, PFCCQL, PFCCQN, PFCSQL, PFCSQN, PFPLSL, PFPLSN, PFPLSG, PFPLCL, PFPLCN, PFPLCG,  &
& PFESL, PFESN, PFESG, PFECL, PFECN, PFECG, PFASL, PFASN, PFASG, PFACL, PFACN, PFCQLNG, PFCQING, PFCQRNG, PFCQSNG, PFCQGNG,  &
& PFCQNG, PFRMH, PFRMQ, PFRSO, PFRTH, PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRTU, PSTRTV, PSTRMU, PSTRMV, PDIFCQLC, PDIFCQIC,  &
& PFIMCC, PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC, PFCNEGQLC, PFCNEGQIC, PFCNEGQRC, PFCNEGQSC, PFTKE, PFTKEI, PFEFB1, PFEFB2, PFEFB3,  &
& PDELP, PRDELP, PAPHIF, PCP, PU, PV, PT, PQ, PQI, PQL, PQLCONV, PQICONV, PQRCONV, PQSCONV, PQR, PQS, PQG, PCPS, PTS, PFHSCL,  &
& PFHSCN, PFHSSL, PFHSSN, PFHSSG, PFHPCL, PFHPCN, PFHPCG, PFHPSL, PFHPSN, PFHPSG, PFHP, PFP, PFEPFP, PFCMPCQ, PFCMPSN, PFCMPSL,  &
& PTENDU, PTENDV, PTENDU_ZDEC, PTENDV_ZDEC, PTENDH, PTENDQ, PTENDQI, PTENDQL, PTENDQLCONV, PTENDQICONV, PTENDQRCONV,  &
& PTENDQSCONV, PTENDQR, PTENDQS, PTENDQG, PTENDTKE, PTENDEFB1, PTENDEFB2, PTENDEFB3, PTENDEXT, YDDDH, YDSTACK)
  !     ------------------------------------------------------------------
  !     ACTION DES PROCESSUS PHYSIQUES SUR LA QUANTITE DE MOUVEMENT ,
  !     LES VARIABLES THERMODYNAMIQUES ET SUR L'EQUATION DE CONTINUITE
  !     INTERFACE AVEC LES PARAMETRISATIONS PHYSIQUES  (IALPP)
  !     ------------------------------------------------------------------
  
  !     BUT
  !     ---
  !**** *CPTEND* CACUL DES TENDANCES PHYSIQUES SUR U, V, H, Q, QI, QL, TKE
  !      SPECIFIQUE ET SUR LA TEMPERATURE.
  
  !      VOIR DOCUMENTATION, INTERFACE PHYSICO-DYNAMIQUE.
  !                            -----------------
  
  !      POUR COMPRENDRE LA LOGIQUE DE CETTE ROUTINE, BIEN REALISER
  !      QUE LA VARIABLE THERMODYNAMIQUE DE LA PHYSIQUE EST L ENTHALPIE
  !                                                         -----------
  !      (PLUS EXACTEMENT L ENERGIE STATIQUE HUMIDE)
  
  !      LE TRANSPORT EVENTUEL PAR LES PLUIES EST PRIS EN COMPTE DE
  !      MANIERE MIXTE :
  !      - UNE PARTIE DE CE TRANSPORT EST CONTENUE DE MANIERE IMPLICITE
  !        DANS LA FORMULATION EN FLUX D ENTHALPIE
  !      - IL RESTE POURTANT UN TERME DE TRANSPORT D ENERGIE POTENTIELLE
  !        QUI EST TRAITE ICI COMME UNE ADVECTION VERTICALE
  
  !     ARGUMENTS D ENTREE
  !     ------------------
  !       KLON   : DIMENSION HORIZONTALE
  !       KIDIA  : DEBUT DE LA BOUCLE HORIZONTALE
  !       KFDIA  : BORNE HORIZONTALE DES CALCULS
  !       KFLEV  : DIMENSION ET BORNE VERTICALE
  !       PGNORDL,PGNORDM : compass.
  
  ! --- INPUT 2D (0:KLEV).
  !     -----------------.
  ! PDIFCQ     : FLUX CONVECTIF D'HUMIDITE SPECIFIQUE (HORS COND. ET RR).
  ! PDIFCQI    : FLUX CONVECTIF D'EAU SOLIDE (HORS COND. ET RR).
  ! PDIFCQL    : FLUX CONVECTIF D'EAU LIQUIDE (HORS COND. ET RR).
  ! PDIFCS     : FLUX CONVECTIF D'ENTHALPIE .
  ! PDIFEXT    : FLUX DES EXTRA-GFL .
  ! PDIFTQ     : FLUX TURBULENT (ET Q NEGATIF) D'HUMIDITE SPECIFIQUE.
  ! PDIFTQI    : FLUX TURBULENT (ET Q NEGATIF) D'EAU GLACE.
  ! PDIFTQL    : FLUX TURBULENT (ET Q NEGATIF) D'EAU LIQUIDE.
  ! PDIFTS     : FLUX TURBULENT D'ENTHALPIE (OU D'ENERGIE STATIQUE SECHE).
  ! PFCCQL     : FLUX DE CONDENSATION LIE AUX RR CONVECTIVES LIQUIDES.
  ! PFCCQN     : FLUX DE CONDENSATION LIE AUX RR CONVECTIVES NEIGEUSES.
  ! PFCSQL     : FLUX DE CONDENSATION LIE AUX RR STRATIFORMES LIQUIDES.
  ! PFCSQN     : FLUX DE CONDENSATION LIE AUX RR STRATIFORMES NEIGEUSES.
  ! PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
  ! PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.
  ! PFPLCG     : PRECIPITATIONS CONVECTIVES SOUS FORME GRAUPEL.
  ! PFPLSL     : PRECIPITATIONS STRATIFORMES SOUS FORME LIQUIDE.
  ! PFPLSN     : PRECIPITATIONS STRATIFORMES SOUS FORME NEIGE.
  ! PFPLSG     : PRECIPITATIONS STRATIFORMES SOUS FORME GRAUPEL.
  ! PFRMH      : FLUX MESOSPHERIQUE D'ENTHALPIE.
  ! PFRMQ      : FLUX MESOSPHERIQUE D'EAU.
  ! PFRSO      : FLUX DE RAYONNEMENT SOLAIRE.
  ! PFRTH      : FLUX DE RAYONNEMENT THERMIQUE.
  ! PSTRCU     : FLUX CONVECTIF DE QUANTITE DE MOUVEMENT "U".
  ! PSTRCV     : FLUX CONVECTIF DE QUANTITE DE MOUVEMENT "V".
  ! PSTRDU     : FLUX "GRAVITY WAVE DRAG" "U".
  ! PSTRDV     : FLUX "GRAVITY WAVE DRAG" "V".
  ! PSTRTU     : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "U".
  ! PSTRTV     : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "V".
  ! PSTRMU     : FLUX MESOSPHERIQUE DE QUANTITE DE MOUVEMENT "U".
  ! PSTRMV     : FLUX MESOSPHERIQUE DE QUANTITE DE MOUVEMENT "V".
  ! PDIFCQLC   : CONVECTIVE TRANSPORT FLUX OF QLC (LIQUID CONVECTIVE).
  ! PDIFCQIC   : CONVECTIVE TRANSPORT FLUX OF QIC (ICE CONVECTIVE).
  ! PFIMCC     : Q FLUX DUE TO ICING-MELTING FOLLOWING CONVECTIVE TRANSPORT OF CONVECTIVE LIQUID AND ICE WATER.
  ! PFEDQLC    : ENTRAINMENT-DETRAINMENT OF QLC AND QLR (LIQUID CONVECTIVE AND RESOLVED).
  ! PFEDQIC    : ENTRAINMENT-DETRAINMENT OF QIC AND QIR (ICE    CONVECTIVE AND RESOLVED).
  ! PFEDQRC    : ENTRAINMENT-DETRAINMENT OF QRC AND QRR (RAIN   CONVECTIVE AND RESOLVED).
  ! PFEDQSC    : ENTRAINMENT-DETRAINMENT OF QSC AND QSR (SNOW   CONVECTIVE AND RESOLVED).
  ! PFCNEGQLC  : CORRECT NEGATIVE VALUES OF QLC (LIQUID CONVECTIVE).
  ! PFCNEGQIC  : CORRECT NEGATIVE VALUES OF QIC (ICE    CONVECTIVE).
  ! PFCNEGQRC  : CORRECT NEGATIVE VALUES OF QRC (RAIN   CONVECTIVE).
  ! PFCNEGQSC  : CORRECT NEGATIVE VALUES OF QSC (SNOW   CONVECTIVE).
  ! PFTKE      : FLUX DE "TKE".
  
  ! --- INPUT 2D (1:KLEV).
  !     -----------------.
  ! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PAPHIF     : GEOPOTENTIEL AUX NIVEAUX DES COUCHES.
  ! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
  ! PU         : COMPOSANTE EN X DU VENT.
  ! PV         : COMPOSANTE EN Y DU VENT.
  ! PT         : TEMPERATURE.
  ! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
  ! PQI        : GLACE.
  ! PQL        : EAU LIQUIDE.
  ! PQR        : RAIN
  ! PQS        : SNOW
  ! PQG        : GRAUPEL
  ! PQLCONV    : LIQUID WATER (CONVECTIVE).
  ! PQICONV    : ICE    WATER (CONVECTIVE).
  ! PQRCONV    : RAIN   WATER (CONVECTIVE).
  ! PQSCONV    : SNOW   WATER (CONVECTIVE).
  
  ! - 1D.
  !   --.
  ! PCPS       : CHALEUR SPECIFIQUE EN SURFACE.
  ! PTS        : TEMPERATURE DE SURFACE.
  
  ! --- ARGUMENTS IMPLICITES.
  !     --------------------.
  ! CONSTANTES UNIVERSELLES = COMMON /YOMCST/: RG,RCPD
  ! INDICATEURS LOGIQUES    = COMMON /YOMPHY/: NDPSFI,LCONDWT
  
  ! --- SORTIES 2D (0:KFLEV).
  !     --------------------.
  ! PFHSCL : FLUX DE CHALEUR SENSIBLE LIE AUX RR CONVECTIVES LIQUIDES.
  ! PFHSCN : FLUX DE CHALEUR SENSIBLE LIE AUX RR CONVECTIVES NEIGEUSES.
  ! PFHSSL : FLUX DE CHALEUR SENSIBLE LIE AUX RR STRATIFORMES LIQUIDES.
  ! PFHSSN : FLUX DE CHALEUR SENSIBLE LIE AUX RR STRATIFORMES NEIGEUSES.
  ! PFHSSG : FLUX DE CHALEUR SENSIBLE LIE AUX RR STRATIFORMES GRAUPEL.
  ! PFHPCL : FLUX D'ENTHALPIE LIE A LA CONDENSATION CONVECTIVE LIQUIDE.
  ! PFHPCN : FLUX D'ENTHALPIE LIE A LA CONDENSATION CONVECTIVE NEIGEUSE.
  ! PFHPCG : FLUX D'ENTHALPIE LIE A LA CONDENSATION CONVECTIVE GRAUPEL.
  ! PFHPSL : FLUX D'ENTHALPIE LIE A LA CONDENSATION STRATIFORME LIQUIDE.
  ! PFHPSN : FLUX D'ENTHALPIE LIE A LA CONDENSATION STRATIFORME NEIGEUSE.
  ! PFHPSG : FLUX D'ENTHALPIE LIE A LA CONDENSATION STRATIFORME GRAUPEL.
  ! PFHP   : FLUX TOTAL D'ENTHALPIE + FLUX DE CHALEUR SENSIBLE.
  ! PFP    : FLUX TOTAL DE PRECIPITATIONS.
  ! PFEPFP : PSEUDO FLUX D'ENTHALPIE LIE A L'ENERGIE PRECIPITATIONS.
  
  ! --- SORTIES 2D (1:KFLEV).
  !     --------------------.
  ! PTENDU     : TENDANCE DU VENT SUR U.
  ! PTENDV     : TENDANCE DU VENT SUR V.
  ! PTENDU_ZDEC : TENDANCE DU VENT SUR U. USED IN CPUTQY TO COMPUTE T TENDENCIES (WITHOUT DEEP CONVECTION CONTRIBUTION)
  ! OF LCVTDK TO AVOID DOUBLE COUNTING)
  ! PTENDV_ZDEC : TENDANCE DU VENT SUR V. USED IN CPUTQY TO COMPUTE T TENDENCIES (WITHOUT DEEP CONVECTION CONTRIBUTION)
  ! OF LCVTDK TO AVOID DOUBLE COUNTING)
  ! PTENDH     : TENDANCE DE L'ENTHALPIE.
  ! PTENDQ     : TENDANCE DE L'HUMIDITE.
  ! PTENDQI    : TENDANCE DE L'EAU GLACE.
  ! PTENDQL    : TENDANCE DE L'EAU LIQUIDE.
  ! PTENDQR    : TENDANCE DU CONTENU EN EAU PRECIPITANT LIQUIDE.
  ! PTENDQS    : TENDANCE DU CONTENU EN EAU PRECIPITANT SOLIDE.
  ! PTENDQG    : TENDANCE DU CONTENU EN EAU PRECIPITANT GRAUPEL.
  ! PTENDQLCONV: TENDANCE DE L'EAU LIQUIDE (CONVECTIVE).
  ! PTENDQICONV: TENDANCE DE L'EAU GLACE   (CONVECTIVE).
  ! PTENDQRCONV: TENDANCE DE L'EAU PLUIE   (CONVECTIVE).
  ! PTENDQSCONV: TENDANCE DE L'EAU NEIGE   (CONVECTIVE).
  ! PTENDTKE   : TENDANCE DE TKE.
  ! PTENDEXT   : GFL EXTRA tendency.
  ! --- AUTEUR.
  !     ------.
  !     02/01/92 E.BAZILE.
  !        Reunification de Cpaty,Cpdthp,Cpdup par E.Bazile.
  
  ! --- MODIFICATIONS.
  !     --------------
  !      Modified 04-01-16 by P. Marquet (Lopez and Gueremy schemes,
  !                        they both add PFPEVPP to PTENDQ, with
  !                        PFPFP and PFADVP only for Lopez)
  !                        The signs of the fluxes PFPEVPP, PFPFP and
  !                        PFADVP have changed in ADVPRC.
  !      Modified 07-02-01 by M.Janousek (Catry's modifications for
  !                        NDPSFI=1; tendency of pTKE)
  !      Modified 07-05-07 by F.Bouyssel (tendency of TKE + Cleaning)
  !      Modified 07-06-13 by T.Kovacic, PFCMPCQ, PFCMPSN, PFCMPSL added for DDH
  !        Modified 11-02-01 by M. Mokhtari add the key LMDUST and traitement of passifs scalars
  !        Modified 11-03-31 by M. Deque : Relax. of Meso. Specific Humidity added (fix)
  !        Modified 11-12-01 by J. Van den Bergh: introduction of graupel
  !        2011-09-07 J.M. Piriou: PCMT convection scheme.
  !        2013-11, D. Degrauwe: Bugfix (use halflevel cp in case of NDPSFI=1).
  !        2014-02-20 J.M. Piriou: fix 2 bugs in ZFHIMCC computation.
  !        2014-04-30 J.M. Piriou: change sign in ZFHIMCC computation.
  !        2016-10-04 P. Marguinaud : Port to single precision
  !        2019-12-12 Y. Bouteloup : Introduction of PTENDU_ZDEC and PTENDV_ZDEC (for Tiedtke scheme)
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( CPTEND_NEW_OPENACC ) seq
  
  USE TYPE_MODEL, ONLY: MODEL
  USE PARKIND1, ONLY: JPIM, JPRB, JPRD
  USE YOMHOOK, ONLY: DR_HOOK, JPHOOK, LHOOK
  
  USE DDH_MIX, ONLY: ADD_FIELD_3D, NEW_ADD_FIELD_3D, TYP_DDH
  USE YOMLSFORC, ONLY: LMUSCLFA, NMUSCLFA
  USE YOMCST, ONLY: TCST
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
  REAL(KIND=JPRB), INTENT(IN) :: PGNORDL
  REAL(KIND=JPRB), INTENT(IN) :: PGNORDM
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQI(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCS(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFEXT(KLON, 0:KFLEV, 1:YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTQI(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTQL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFTS(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCCQL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCCQN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCSQL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCSQN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLSL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLSN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLSG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLCL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLCN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFPLCG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFESL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFESN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFESG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFECL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFECN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFECG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFASL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFASN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFASG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFACL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFACN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQLNG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQING(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQRNG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQSNG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQGNG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCQNG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRMH(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRMQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRSO(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRTH(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRCU(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRCV(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRDU(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRDV(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRTU(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRTV(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRMU(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PSTRMV(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQLC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDIFCQIC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFIMCC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEDQLC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEDQIC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEDQRC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEDQSC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCNEGQLC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCNEGQIC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCNEGQRC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFCNEGQSC(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFTKE(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFTKEI(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEFB1(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEFB2(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFEFB3(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PRDELP(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCP(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PU(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PT(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQI(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQL(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQLCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQICONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQRCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQSCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQR(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQS(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQG(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCPS
  REAL(KIND=JPRB), INTENT(IN) :: PTS
  REAL(KIND=JPRB), INTENT(OUT) :: PFHSCL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHSCN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHSSL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHSSN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHSSG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPCL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPCN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPCG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPSL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPSN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHPSG(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFHP(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFP(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFEPFP(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCMPCQ(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCMPSN(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCMPSL(KLON, 0:KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDU(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDU_ZDEC(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDV_ZDEC(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDH(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQ(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQI(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQL(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQLCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQICONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQRCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQSCONV(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQR(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQS(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDQG(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDTKE(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDEFB1(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDEFB2(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDEFB3(KLON, KFLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PTENDEXT(KLON, KFLEV, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
  TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
  !-----------------------------------------------------------------------
  
  temp (REAL (KIND=JPRB), ZGSDP, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZJTOT, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFHSENS, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFHDPSFI, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZTI, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQLH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQIH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQRH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQSH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZQGH, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZCHAT, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZLIFT, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPL, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPN, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLSL, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLSN, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLSG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLCL, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLCN, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFPLCG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZFHIMCC, (KLON, 0:KFLEV))
  
  temp (REAL (KIND=JPRB), ZTMPVAR, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZTMPFLUX, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTTUG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTTVG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTCUG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTCVG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTDUG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZSTDVG, (KLON, 0:KFLEV))
  temp (REAL (KIND=JPRB), ZTNDKKC, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZTNDKKD, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZTNDKKT, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZKENE, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZUZGEO, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZVMGEO, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZQ1, (KLON, KFLEV))
  temp (REAL (KIND=JPRB), ZQ2, (KLON, KFLEV))
  REAL(KIND=JPRB) :: ZCPH
  
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JGFL
  
  LOGICAL :: LLDPSFI
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
#include "wrscmr.intfb.h"
#include "fcttrm.func.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  alloc (ZGSDP)
  alloc (ZJTOT)
  alloc (ZFHSENS)
  alloc (ZFHDPSFI)
  alloc (ZTI)
  alloc (ZQH)
  alloc (ZQLH)
  alloc (ZQIH)
  alloc (ZQRH)
  alloc (ZQSH)
  alloc (ZQGH)
  alloc (ZCHAT)
  alloc (ZLIFT)
  alloc (ZFPL)
  alloc (ZFPN)
  alloc (ZFPG)
  alloc (ZFPLSL)
  alloc (ZFPLSN)
  alloc (ZFPLSG)
  alloc (ZFPLCL)
  alloc (ZFPLCN)
  alloc (ZFPLCG)
  alloc (ZFHIMCC)
  alloc (ZTMPVAR)
  alloc (ZTMPFLUX)
  alloc (ZSTTUG)
  alloc (ZSTTVG)
  alloc (ZSTCUG)
  alloc (ZSTCVG)
  alloc (ZSTDUG)
  alloc (ZSTDVG)
  alloc (ZTNDKKC)
  alloc (ZTNDKKD)
  alloc (ZTNDKKT)
  alloc (ZKENE)
  alloc (ZUZGEO)
  alloc (ZVMGEO)
  alloc (ZQ1)
  alloc (ZQ2)
  JLON = KIDIA
  
  !-----------------------------------------------------------------------
  
  !-----------------------------------------------------------------------
  
  ! ------------------------------------------------------------------
  ! intermediate CPTEND version made for acpluie_prog and Luc's scheme
  ! ------------------------------------------------------------------
  
  ! the following assumptions are made:
  
  ! * Lopez scheme uses both QR and QS as prognostic variable
  ! * the diffusive fluxes (for qv, qi, ql and s) have a turbulent
  !   and convective component
  ! * the pseudo-fluxes between the species (','',''') all have a
  !   stratiform component, only condensation has a convective
  !   component
  ! * CPFHPFS is integrated in this routine and should not be called
  ! ------------------------------------------------------------------
  
  !    -------------------------------------------------------------------
  
  LLDPSFI = YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI == 1
  ZLIFT = 0.0_JPRB
  ZCHAT = 0.0_JPRB
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
    ! Heat flux due to convective icing/melting of cloud condensates.
    ZFHIMCC(JLON, 0) = 0._JPRB
    DO JLEV=1,KFLEV
      ZFHIMCC(JLON, JLEV) = ZFHIMCC(JLON, JLEV - 1) + (PFIMCC(JLON, JLEV) - PFIMCC(JLON, JLEV - 1))*(YDCST%RLVZER - YDCST%RLSZER)
    END DO
  ELSE
    ZFHIMCC(JLON, :) = 0._JPRB
  END IF
  
  !  ------------------------------------------------------------
  !   1. CALCUL DE L'EVOLUTION DE Q ET CALCUL PARTIEL DE dU/dT ET
  !  ET DE dH/dt ( avec H = CpT + Phi + Ec )
  !  ------------------------------------------------------------
  
  ! Calculation of temperatures on half levels
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LPHSPSH) THEN
    ZTI(JLON, 0) = PT(JLON, 1)
    ZTI(JLON, KFLEV) = PT(JLON, KFLEV)
  ELSE
    ZTI(JLON, 0) = PT(JLON, 1)
    ZTI(JLON, KFLEV) = PTS
  END IF
  
  DO JLEV=1,KFLEV - 1
    ZTI(JLON, JLEV) = (PT(JLON, JLEV) + PT(JLON, JLEV + 1))*0.5_JPRB
  END DO
  
  ! preparation for case delta_m=1
  
  IF (LLDPSFI) THEN
    ZQH(JLON, 0) = 0.0_JPRB
    ZQLH(JLON, 0) = 0.0_JPRB
    ZQIH(JLON, 0) = 0.0_JPRB
    ZQRH(JLON, 0) = 0.0_JPRB
    ZQSH(JLON, 0) = 0.0_JPRB
    ZQH(JLON, KFLEV) = PQ(JLON, KFLEV)
    ZQLH(JLON, KFLEV) = PQL(JLON, KFLEV)
    ZQIH(JLON, KFLEV) = PQI(JLON, KFLEV)
    ZQRH(JLON, KFLEV) = PQR(JLON, KFLEV)
    ZQSH(JLON, KFLEV) = PQS(JLON, KFLEV)
    DO JLEV=1,KFLEV - 1
      ZQH(JLON, JLEV) = (PQ(JLON, JLEV) + PQ(JLON, JLEV + 1))*0.5_JPRB
      ZQLH(JLON, JLEV) = (PQL(JLON, JLEV) + PQL(JLON, JLEV + 1))*0.5_JPRB
      ZQIH(JLON, JLEV) = (PQI(JLON, JLEV) + PQI(JLON, JLEV + 1))*0.5_JPRB
      ZQRH(JLON, JLEV) = (PQR(JLON, JLEV) + PQR(JLON, JLEV + 1))*0.5_JPRB
      ZQSH(JLON, JLEV) = (PQS(JLON, JLEV) + PQS(JLON, JLEV + 1))*0.5_JPRB
    END DO
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      ZQGH(JLON, 0) = 0.0_JPRB
      ZQGH(JLON, KFLEV) = PQG(JLON, KFLEV)
      DO JLEV=1,KFLEV - 1
        ZQGH(JLON, JLEV) = (PQG(JLON, JLEV) + PQG(JLON, JLEV + 1))*0.5_JPRB
      END DO
    END IF
  END IF
  
  ! Transformation between absolute and relative precip fluxes
  
  IF (LLDPSFI) THEN
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      DO JLEV=0,KFLEV
        ZFPL(JLON, JLEV) =  &
        & (1.0_JPRB - ZQRH(JLON, JLEV))*PFPLSL(JLON, JLEV) - ZQRH(JLON, JLEV)*(PFPLSN(JLON, JLEV) + PFPLSG(JLON, JLEV))
        ZFPN(JLON, JLEV) =  &
        & (1.0_JPRB - ZQSH(JLON, JLEV))*PFPLSN(JLON, JLEV) - ZQSH(JLON, JLEV)*(PFPLSL(JLON, JLEV) + PFPLSG(JLON, JLEV))
        ZFPG(JLON, JLEV) =  &
        & (1.0_JPRB - ZQGH(JLON, JLEV))*PFPLSG(JLON, JLEV) - ZQGH(JLON, JLEV)*(PFPLSL(JLON, JLEV) + PFPLSN(JLON, JLEV))
        ZFPLSL(JLON, JLEV) = ZFPL(JLON, JLEV)
        ZFPLSN(JLON, JLEV) = ZFPN(JLON, JLEV)
        ZFPLSG(JLON, JLEV) = ZFPG(JLON, JLEV)
        ZFPL(JLON, JLEV) = (1.0_JPRB - ZQRH(JLON, JLEV))*PFPLCL(JLON, JLEV) - ZQRH(JLON, JLEV)*PFPLCN(JLON, JLEV)
        ZFPN(JLON, JLEV) = (1.0_JPRB - ZQSH(JLON, JLEV))*PFPLCN(JLON, JLEV) - ZQSH(JLON, JLEV)*PFPLCL(JLON, JLEV)
        ZFPG(JLON, JLEV) = (1.0_JPRB - ZQGH(JLON, JLEV))*PFPLCG(JLON, JLEV) - ZQGH(JLON, JLEV)*PFPLCG(JLON, JLEV)
        ZFPLCL(JLON, JLEV) = ZFPL(JLON, JLEV)
        ZFPLCN(JLON, JLEV) = ZFPN(JLON, JLEV)
        ZFPLCG(JLON, JLEV) = ZFPG(JLON, JLEV)
        ZFPL(JLON, JLEV) = ZFPLSL(JLON, JLEV) + ZFPLCL(JLON, JLEV)
        ZFPN(JLON, JLEV) = ZFPLSN(JLON, JLEV) + ZFPLCN(JLON, JLEV)
        ZFPG(JLON, JLEV) = ZFPLSG(JLON, JLEV) + ZFPLCG(JLON, JLEV)
        ZCPH = YDCST%RCPD + (YDCST%RCPV - YDCST%RCPD)*ZQH(JLON, JLEV) + (YDCST%RCW - YDCST%RCPD)*(ZQLH(JLON, JLEV) + ZQRH(JLON,  &
        & JLEV)) + (YDCST%RCS - YDCST%RCPD)*(ZQIH(JLON, JLEV) + ZQSH(JLON, JLEV) + ZQGH(JLON, JLEV))
        ZCHAT(JLON, JLEV) = (ZCPH - YDCST%RCW*ZQRH(JLON, JLEV) - YDCST%RCS*(ZQSH(JLON, JLEV) + ZQGH(JLON, JLEV))) / (1.0_JPRB -  &
        & ZQRH(JLON, JLEV) - ZQSH(JLON, JLEV) - ZQGH(JLON, JLEV))
        ZLIFT(JLON, JLEV) = (ZFPL(JLON, JLEV) + ZFPN(JLON, JLEV) + ZFPG(JLON, JLEV)) / (1.0_JPRB - ZQRH(JLON, JLEV) - ZQSH(JLON,  &
        & JLEV) - ZQGH(JLON, JLEV))
      END DO
    ELSE
      DO JLEV=0,KFLEV
        ZFPL(JLON, JLEV) = (1.0_JPRB - ZQRH(JLON, JLEV))*PFPLSL(JLON, JLEV) - ZQRH(JLON, JLEV)*PFPLSN(JLON, JLEV)
        ZFPN(JLON, JLEV) = (1.0_JPRB - ZQSH(JLON, JLEV))*PFPLSN(JLON, JLEV) - ZQSH(JLON, JLEV)*PFPLSL(JLON, JLEV)
        ZFPLSL(JLON, JLEV) = ZFPL(JLON, JLEV)
        ZFPLSN(JLON, JLEV) = ZFPN(JLON, JLEV)
        ZFPL(JLON, JLEV) = (1.0_JPRB - ZQRH(JLON, JLEV))*PFPLCL(JLON, JLEV) - ZQRH(JLON, JLEV)*PFPLCN(JLON, JLEV)
        ZFPN(JLON, JLEV) = (1.0_JPRB - ZQSH(JLON, JLEV))*PFPLCN(JLON, JLEV) - ZQSH(JLON, JLEV)*PFPLCL(JLON, JLEV)
        ZFPLCL(JLON, JLEV) = ZFPL(JLON, JLEV)
        ZFPLCN(JLON, JLEV) = ZFPN(JLON, JLEV)
        ZFPL(JLON, JLEV) = ZFPLSL(JLON, JLEV) + ZFPLCL(JLON, JLEV)
        ZFPN(JLON, JLEV) = ZFPLSN(JLON, JLEV) + ZFPLCN(JLON, JLEV)
        ZCPH = YDCST%RCPD + (YDCST%RCPV - YDCST%RCPD)*ZQH(JLON, JLEV) + (YDCST%RCW - YDCST%RCPD)*(ZQLH(JLON, JLEV) + ZQRH(JLON,  &
        & JLEV)) + (YDCST%RCS - YDCST%RCPD)*(ZQIH(JLON, JLEV) + ZQSH(JLON, JLEV))
        ZCHAT(JLON, JLEV) =  &
        & (ZCPH - YDCST%RCW*ZQRH(JLON, JLEV) - YDCST%RCS*ZQSH(JLON, JLEV)) / (1.0_JPRB - ZQRH(JLON, JLEV) - ZQSH(JLON, JLEV))
        ZLIFT(JLON, JLEV) = (ZFPL(JLON, JLEV) + ZFPN(JLON, JLEV)) / (1.0_JPRB - ZQRH(JLON, JLEV) - ZQSH(JLON, JLEV))
      END DO
    END IF
  ELSE
    DO JLEV=0,KFLEV
      ZFPL(JLON, JLEV) = PFPLSL(JLON, JLEV) + PFPLCL(JLON, JLEV)
      ZFPN(JLON, JLEV) = PFPLSN(JLON, JLEV) + PFPLCN(JLON, JLEV)
    END DO
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      DO JLEV=0,KFLEV
        ZFPG(JLON, JLEV) = PFPLSG(JLON, JLEV)
      END DO
    END IF
  END IF
  ! Diagnostics
  
  DO JLEV=0,KFLEV
    
    IF (LLDPSFI) THEN
      
      PFHSCL(JLON, JLEV) = ZFPLCL(JLON, JLEV)*ZTI(JLON, JLEV)*YDCST%RCW
      PFHSCN(JLON, JLEV) = ZFPLCN(JLON, JLEV)*ZTI(JLON, JLEV)*YDCST%RCS
      PFHSSL(JLON, JLEV) = ZFPLSL(JLON, JLEV)*ZTI(JLON, JLEV)*YDCST%RCW
      PFHSSN(JLON, JLEV) = ZFPLSN(JLON, JLEV)*ZTI(JLON, JLEV)*YDCST%RCS
      IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
        PFHSSG(JLON, JLEV) = ZFPLSG(JLON, JLEV)*ZTI(JLON, JLEV)*YDCST%RCS
      ELSE
        PFHSSG(JLON, JLEV) = 0._JPRB
      END IF
      
    ELSE
      
      PFHSCL(JLON, JLEV) = PFPLCL(JLON, JLEV)*ZTI(JLON, JLEV)*(YDCST%RCW - YDCST%RCPD)
      PFHSCN(JLON, JLEV) = PFPLCN(JLON, JLEV)*ZTI(JLON, JLEV)*(YDCST%RCS - YDCST%RCPD)
      PFHSSL(JLON, JLEV) = PFPLSL(JLON, JLEV)*ZTI(JLON, JLEV)*(YDCST%RCW - YDCST%RCPD)
      PFHSSN(JLON, JLEV) = PFPLSN(JLON, JLEV)*ZTI(JLON, JLEV)*(YDCST%RCS - YDCST%RCPD)
      IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
        PFHSSG(JLON, JLEV) = PFPLSG(JLON, JLEV)*ZTI(JLON, JLEV)*(YDCST%RCS - YDCST%RCPD)
      ELSE
        PFHSSG(JLON, JLEV) = 0._JPRB
      END IF
      
    END IF
    
    PFHPCL(JLON, JLEV) = -YDCST%RLVZER*(PFCCQL(JLON, JLEV) - PFECL(JLON, JLEV))
    PFHPCN(JLON, JLEV) = -YDCST%RLSZER*(PFCCQN(JLON, JLEV) - PFECN(JLON, JLEV))
    PFHPSL(JLON, JLEV) = -YDCST%RLVZER*(PFCSQL(JLON, JLEV) - PFESL(JLON, JLEV))
    PFHPSN(JLON, JLEV) = -YDCST%RLSZER*(PFCSQN(JLON, JLEV) - PFESN(JLON, JLEV))
    
    PFP(JLON, JLEV) = ZFPL(JLON, JLEV) + ZFPN(JLON, JLEV)
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      PFHPSG(JLON, JLEV) = -YDCST%RLSZER*(-PFESG(JLON, JLEV))
      PFHPCG(JLON, JLEV) = -YDCST%RLSZER*(-PFECG(JLON, JLEV))
      PFP(JLON, JLEV) = PFP(JLON, JLEV) + ZFPG(JLON, JLEV)
    ELSE
      PFHPSG(JLON, JLEV) = 0._JPRB
      PFHPCG(JLON, JLEV) = 0._JPRB
    END IF
    
    PFEPFP(JLON, JLEV) = -YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI*ZCHAT(JLON, JLEV)*ZTI(JLON, JLEV)*PFP(JLON, JLEV)
    
    PFHP(JLON, JLEV) = PFHSCL(JLON, JLEV) + PFHSCN(JLON, JLEV) + PFHSSL(JLON, JLEV) + PFHSSN(JLON, JLEV) + PFHPCL(JLON, JLEV) +  &
    & PFHPCN(JLON, JLEV) + PFHPSL(JLON, JLEV) + PFHPSN(JLON, JLEV) + PFEPFP(JLON, JLEV)
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      PFHP(JLON, JLEV) = PFHP(JLON, JLEV) + PFHSSG(JLON, JLEV) + PFHPSG(JLON, JLEV) + PFHPCG(JLON, JLEV)
    END IF
  END DO
  
  ! Computation of the total enthalpy flux J_tot (including NDPSFI==1)
  
  DO JLEV=0,KFLEV
    ZJTOT(JLON, JLEV) = PFRSO(JLON, JLEV) + PFRTH(JLON, JLEV) + PFRMH(JLON, JLEV) + PDIFTS(JLON, JLEV) + PDIFCS(JLON, JLEV) +  &
    & (YDCST%RCW - YDCST%RCPD)*ZFPL(JLON, JLEV)*ZTI(JLON, JLEV) + (YDCST%RCS - YDCST%RCPD)*ZFPN(JLON, JLEV)*ZTI(JLON, JLEV) -  &
    & YDCST%RLVZER*(PFCCQL(JLON, JLEV) + PFCSQL(JLON, JLEV) - PFESL(JLON, JLEV) - PFECL(JLON, JLEV)) - YDCST%RLSZER*(PFCCQN(JLON, &
    &  JLEV) + PFCSQN(JLON, JLEV) - PFESN(JLON, JLEV) - PFECN(JLON, JLEV)) + ZFHIMCC(JLON, JLEV)
  END DO
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    DO JLEV=0,KFLEV
      ZJTOT(JLON, JLEV) = ZJTOT(JLON, JLEV) + (YDCST%RCS - YDCST%RCPD)*ZFPG(JLON, JLEV)*ZTI(JLON, JLEV) +  &
      & YDCST%RLSZER*(PFESG(JLON, JLEV) + PFECG(JLON, JLEV))
    END DO
  END IF
  
  IF (LLDPSFI) THEN
    DO JLEV=0,KFLEV
      ZFHDPSFI(JLON, JLEV) = -(ZCHAT(JLON, JLEV) - YDCST%RCPD)*ZTI(JLON, JLEV)*(ZFPL(JLON, JLEV) + ZFPN(JLON, JLEV))
      IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
        ZFHDPSFI(JLON, JLEV) = ZFHDPSFI(JLON, JLEV) - (ZCHAT(JLON, JLEV) - YDCST%RCPD)*ZTI(JLON, JLEV)*ZFPG(JLON, JLEV)
      END IF
      ZJTOT(JLON, JLEV) = ZJTOT(JLON, JLEV) + ZFHDPSFI(JLON, JLEV)
    END DO
  ELSE
    ZFHDPSFI(JLON, 0:KFLEV) = 0.
  END IF
  
  
  !CDIR UNROLL=8
  DO JLEV=1,KFLEV
    
    ZGSDP(JLON, JLEV) = YDCST%RG*PRDELP(JLON, JLEV)
    
    PTENDU(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PSTRCU(JLON, JLEV - 1) - PSTRCU(JLON, JLEV)) + (PSTRDU(JLON, JLEV - 1) -  &
    & PSTRDU(JLON, JLEV)) + (PSTRMU(JLON, JLEV - 1) - PSTRMU(JLON, JLEV)) + (PSTRTU(JLON, JLEV - 1) - PSTRTU(JLON, JLEV)))
    
    PTENDV(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PSTRCV(JLON, JLEV - 1) - PSTRCV(JLON, JLEV)) + (PSTRDV(JLON, JLEV - 1) -  &
    & PSTRDV(JLON, JLEV)) + (PSTRMV(JLON, JLEV - 1) - PSTRMV(JLON, JLEV)) + (PSTRTV(JLON, JLEV - 1) - PSTRTV(JLON, JLEV)))
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVTDK) THEN
      !     PTENDU_ZDEC(JLON,JLEV) = ZGSDP(JLON,JLEV)*(&
      !      & (PSTRDU (JLON,JLEV-1) - PSTRDU (JLON,JLEV)) +&
      !      & (PSTRMU (JLON,JLEV-1) - PSTRMU (JLON,JLEV)) +&
      !      & (PSTRTU (JLON,JLEV-1) - PSTRTU (JLON,JLEV)) )
      
      PTENDU_ZDEC(JLON, JLEV) = 0.0_JPRB
      !    PTENDV_ZDEC(JLON,JLEV) = ZGSDP(JLON,JLEV)*(&
      !     & (PSTRDV (JLON,JLEV-1) - PSTRDV (JLON,JLEV)) +&
      !     & (PSTRMV (JLON,JLEV-1) - PSTRMV (JLON,JLEV)) +&
      !     & (PSTRTV (JLON,JLEV-1) - PSTRTV (JLON,JLEV)) )
      
      PTENDV_ZDEC(JLON, JLEV) = 0.0_JPRB
    ELSE
      PTENDU_ZDEC(JLON, JLEV) = PTENDU(JLON, JLEV)
      PTENDV_ZDEC(JLON, JLEV) = PTENDV(JLON, JLEV)
    END IF
    
    PTENDQ(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQ(JLON, JLEV - 1) - PDIFTQ(JLON, JLEV)) + (PDIFCQ(JLON, JLEV - 1) -  &
    & PDIFCQ(JLON, JLEV)) + (PFRMQ(JLON, JLEV - 1) - PFRMQ(JLON, JLEV)) + (PFCCQL(JLON, JLEV - 1) - PFCCQL(JLON, JLEV)) +  &
    & (PFCCQN(JLON, JLEV - 1) - PFCCQN(JLON, JLEV)) + (PFCSQL(JLON, JLEV - 1) - PFCSQL(JLON, JLEV)) + (PFCSQN(JLON, JLEV - 1) -  &
    & PFCSQN(JLON, JLEV)) + (PFCQNG(JLON, JLEV - 1) - PFCQNG(JLON, JLEV)) - (PFECL(JLON, JLEV - 1) - PFECL(JLON, JLEV)) -  &
    & (PFESL(JLON, JLEV - 1) - PFESL(JLON, JLEV)) - (PFECN(JLON, JLEV - 1) - PFECN(JLON, JLEV)) - (PFESN(JLON, JLEV - 1) -  &
    & PFESN(JLON, JLEV)))
    
    PTENDH(JLON, JLEV) = ZGSDP(JLON, JLEV)*(ZJTOT(JLON, JLEV - 1) - ZJTOT(JLON, JLEV))
    
  END DO
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQ(JLON, JLEV) = PTENDQ(JLON, JLEV) + ZGSDP(JLON, JLEV)*(-(PFESG(JLON, JLEV - 1) - PFESG(JLON, JLEV)) - (PFECG(JLON,  &
      & JLEV - 1) - PFECG(JLON, JLEV)))
    END DO
  END IF
  
  
  
  !  ------------------------------------------------------------
  !   2. CALCUL DE L'EVOLUTION DE QL, QI, QR, QS, QG
  !  ------------------------------------------------------------
  
  ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ! Pronostic equations for liquid/solid water/precipitation
  ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT .and. .not.YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
    
    ! - - - - - - - - - - - - - - - - - -
    ! Usual equation for QL=suspended liquid water
    ! - - - - - - - - - - - - - - - - - -
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQL(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQL(JLON, JLEV - 1) - PDIFTQL(JLON, JLEV)) + (PDIFCQL(JLON, JLEV - 1) -  &
      & PDIFCQL(JLON, JLEV)) + (PFCQLNG(JLON, JLEV - 1) - PFCQLNG(JLON, JLEV)) + (PFACL(JLON, JLEV - 1) - PFACL(JLON, JLEV)) +  &
      & (PFASL(JLON, JLEV - 1) - PFASL(JLON, JLEV)) - (PFCSQL(JLON, JLEV - 1) - PFCSQL(JLON, JLEV)) - (PFCCQL(JLON, JLEV - 1) -  &
      & PFCCQL(JLON, JLEV)))
    END DO
    
    ! - - - - - - - - - - - - - - - - - -
    ! equation for QI=suspended ice water
    ! - - - - - - - - - - - - - - - - - -
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQI(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQI(JLON, JLEV - 1) - PDIFTQI(JLON, JLEV)) + (PDIFCQI(JLON, JLEV - 1) -  &
      & PDIFCQI(JLON, JLEV)) + (PFCQING(JLON, JLEV - 1) - PFCQING(JLON, JLEV)) + (PFACN(JLON, JLEV - 1) - PFACN(JLON, JLEV)) +  &
      & (PFASN(JLON, JLEV - 1) - PFASN(JLON, JLEV)) - (PFCSQN(JLON, JLEV - 1) - PFCSQN(JLON, JLEV)) - (PFCCQN(JLON, JLEV - 1) -  &
      & PFCCQN(JLON, JLEV)))
    END DO
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      DO JLEV=1,KFLEV
        PTENDQI(JLON, JLEV) = PTENDQI(JLON, JLEV) + ZGSDP(JLON, JLEV)*(PFASG(JLON, JLEV - 1) - PFASG(JLON, JLEV))
      END DO
    END IF
    
    ! -----------------------------------
    ! Equation for QR=rain water
    ! -----------------------------------
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQR(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFESL(JLON, JLEV - 1) - PFESL(JLON, JLEV)) + (PFECL(JLON, JLEV - 1) - PFECL(JLON, &
      &  JLEV)) + (PFCQRNG(JLON, JLEV - 1) - PFCQRNG(JLON, JLEV)) + (ZFPL(JLON, JLEV - 1) - ZFPL(JLON, JLEV)) - (PFACL(JLON, JLEV &
      &  - 1) - PFACL(JLON, JLEV)) - (PFASL(JLON, JLEV - 1) - PFASL(JLON, JLEV)))
    END DO
    
    ! ---------------------------------
    ! Equation for QS=snow water
    ! --------------------------------
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQS(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFESN(JLON, JLEV - 1) - PFESN(JLON, JLEV)) + (PFECN(JLON, JLEV - 1) - PFECN(JLON, &
      &  JLEV)) + (PFCQSNG(JLON, JLEV - 1) - PFCQSNG(JLON, JLEV)) + (ZFPN(JLON, JLEV - 1) - ZFPN(JLON, JLEV)) - (PFACN(JLON, JLEV &
      &  - 1) - PFACN(JLON, JLEV)) - (PFASN(JLON, JLEV - 1) - PFASN(JLON, JLEV)))
    END DO
    
    ! ---------------------------------
    ! Equation for QG=graupel
    ! --------------------------------
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
      !cdir unroll=8
      DO JLEV=1,KFLEV
        PTENDQG(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFESG(JLON, JLEV - 1) - PFESG(JLON, JLEV)) + (PFECG(JLON, JLEV - 1) -  &
        & PFECG(JLON, JLEV)) + (PFCQGNG(JLON, JLEV - 1) - PFCQGNG(JLON, JLEV)) + (ZFPG(JLON, JLEV - 1) - ZFPG(JLON, JLEV)) -  &
        & (PFASG(JLON, JLEV - 1) - PFASG(JLON, JLEV)))
      END DO
    END IF
    
    
  ELSE IF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT .and. YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
    
    ! - - - - - - - - - - - - - - - - - -
    ! PCMT convection scheme.
    ! - - - - - - - - - - - - - - - - - -
    
    ! - - - - - - - - - - - - - - - - - -
    ! Usual equation for QL=suspended liquid water
    ! - - - - - - - - - - - - - - - - - -
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQL(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQL(JLON, JLEV - 1) - PDIFTQL(JLON, JLEV)) + (PDIFCQL(JLON, JLEV - 1) -  &
      & PDIFCQL(JLON, JLEV)) + (PFCQLNG(JLON, JLEV - 1) - PFCQLNG(JLON, JLEV)) - (PFEDQLC(JLON, JLEV - 1) - PFEDQLC(JLON, JLEV))  &
      & + (PFASL(JLON, JLEV - 1) - PFASL(JLON, JLEV)) - (PFCSQL(JLON, JLEV - 1) - PFCSQL(JLON, JLEV)))
    END DO
    
    ! - - - - - - - - - - - - - - - - - -
    ! equation for QI=suspended ice water
    ! - - - - - - - - - - - - - - - - - -
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQI(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PDIFTQI(JLON, JLEV - 1) - PDIFTQI(JLON, JLEV)) + (PDIFCQI(JLON, JLEV - 1) -  &
      & PDIFCQI(JLON, JLEV)) + (PFCQING(JLON, JLEV - 1) - PFCQING(JLON, JLEV)) - (PFEDQIC(JLON, JLEV - 1) - PFEDQIC(JLON, JLEV))  &
      & + (PFASN(JLON, JLEV - 1) - PFASN(JLON, JLEV)) - (PFCSQN(JLON, JLEV - 1) - PFCSQN(JLON, JLEV)))
    END DO
    
    ! -----------------------------------
    ! Equation for QR=rain water
    ! -----------------------------------
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQR(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFESL(JLON, JLEV - 1) - PFESL(JLON, JLEV)) + (PFCQRNG(JLON, JLEV - 1) -  &
      & PFCQRNG(JLON, JLEV)) - (PFEDQRC(JLON, JLEV - 1) - PFEDQRC(JLON, JLEV)) + (PFPLSL(JLON, JLEV - 1) - PFPLSL(JLON, JLEV)) -  &
      & (PFASL(JLON, JLEV - 1) - PFASL(JLON, JLEV)))
    END DO
    
    ! ---------------------------------
    ! Equation for QS=snow water
    ! --------------------------------
    
    !cdir unroll=8
    DO JLEV=1,KFLEV
      PTENDQS(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFESN(JLON, JLEV - 1) - PFESN(JLON, JLEV)) + (PFCQSNG(JLON, JLEV - 1) -  &
      & PFCQSNG(JLON, JLEV)) - (PFEDQSC(JLON, JLEV - 1) - PFEDQSC(JLON, JLEV)) + (PFPLSN(JLON, JLEV - 1) - PFPLSN(JLON, JLEV)) -  &
      & (PFASN(JLON, JLEV - 1) - PFASN(JLON, JLEV)))
    END DO
    ! - - - - - - - - - - - - - - - - - -
    ! Equation for QLCONV=suspended liquid water (CONV. PART)
    ! - - - - - - - - - - - - - - - - - -
    DO JLEV=1,KFLEV
      PTENDQLCONV(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFCNEGQLC(JLON, JLEV - 1) - PFCNEGQLC(JLON, JLEV)) + (PDIFCQLC(JLON, JLEV - 1 &
      & ) - PDIFCQLC(JLON, JLEV)) + (PFEDQLC(JLON, JLEV - 1) - PFEDQLC(JLON, JLEV)) + (PFIMCC(JLON, JLEV - 1) - PFIMCC(JLON, JLEV &
      & )) - (PFCCQL(JLON, JLEV - 1) - PFCCQL(JLON, JLEV)) + (PFACL(JLON, JLEV - 1) - PFACL(JLON, JLEV)))
    END DO
    ! - - - - - - - - - - - - - - - - - -
    ! Equation for QICONV=suspended ice water (CONV. PART)
    ! - - - - - - - - - - - - - - - - - -
    DO JLEV=1,KFLEV
      PTENDQICONV(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFCNEGQIC(JLON, JLEV - 1) - PFCNEGQIC(JLON, JLEV)) + (PDIFCQIC(JLON, JLEV - 1 &
      & ) - PDIFCQIC(JLON, JLEV)) + (PFEDQIC(JLON, JLEV - 1) - PFEDQIC(JLON, JLEV)) - (PFIMCC(JLON, JLEV - 1) - PFIMCC(JLON, JLEV &
      & )) - (PFCCQN(JLON, JLEV - 1) - PFCCQN(JLON, JLEV)) + (PFACN(JLON, JLEV - 1) - PFACN(JLON, JLEV)))
    END DO
    ! -----------------------------------
    ! Equation for QRCONV=rain (CONV. PART)
    ! -----------------------------------
    DO JLEV=1,KFLEV
      PTENDQRCONV(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFCNEGQRC(JLON, JLEV - 1) - PFCNEGQRC(JLON, JLEV)) + (PFPLCL(JLON, JLEV - 1)  &
      & - PFPLCL(JLON, JLEV)) + (PFEDQRC(JLON, JLEV - 1) - PFEDQRC(JLON, JLEV)) - (PFACL(JLON, JLEV - 1) - PFACL(JLON, JLEV)) +  &
      & (PFECL(JLON, JLEV - 1) - PFECL(JLON, JLEV)))
    END DO
    ! ---------------------------------
    ! Equation for QSCONV=snow (CONV. PART)
    ! --------------------------------
    DO JLEV=1,KFLEV
      PTENDQSCONV(JLON, JLEV) = ZGSDP(JLON, JLEV)*((PFCNEGQSC(JLON, JLEV - 1) - PFCNEGQSC(JLON, JLEV)) + (PFPLCN(JLON, JLEV - 1)  &
      & - PFPLCN(JLON, JLEV)) + (PFEDQSC(JLON, JLEV - 1) - PFEDQSC(JLON, JLEV)) - (PFACN(JLON, JLEV - 1) - PFACN(JLON, JLEV)) +  &
      & (PFECN(JLON, JLEV - 1) - PFECN(JLON, JLEV)))
    END DO
  END IF
  
  !     For DDH, could be used in next loop for PTENDQ, PTENDQI,PTENDQL
  
  IF (LLDPSFI) THEN
    DO JLEV=1,KFLEV
      PTENDQ(JLON, JLEV) =  &
      & PTENDQ(JLON, JLEV) - ZGSDP(JLON, JLEV)*(ZQH(JLON, JLEV - 1)*ZLIFT(JLON, JLEV - 1) - ZQH(JLON, JLEV)*ZLIFT(JLON, JLEV))
      IF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT) THEN
        PTENDQI(JLON, JLEV) = PTENDQI(JLON, JLEV) - ZGSDP(JLON, JLEV)*(ZQIH(JLON, JLEV - 1)*ZLIFT(JLON, JLEV - 1) - ZQIH(JLON,  &
        & JLEV)*ZLIFT(JLON, JLEV))
        PTENDQL(JLON, JLEV) = PTENDQL(JLON, JLEV) - ZGSDP(JLON, JLEV)*(ZQLH(JLON, JLEV - 1)*ZLIFT(JLON, JLEV - 1) - ZQLH(JLON,  &
        & JLEV)*ZLIFT(JLON, JLEV))
      END IF
    END DO
  END IF
  
  !  ------------------------------------------------------------
  !   3. CALCUL DE L'EVOLUTION DE TKE
  !  ------------------------------------------------------------
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LECT) THEN
    IF (JPRD == JPRB) THEN
      DO JLEV=1,KFLEV
        PTENDTKE(JLON, JLEV) = ZGSDP(JLON, JLEV)*(PFTKE(JLON, JLEV - 1) - PFTKE(JLON, JLEV))
      END DO
    ELSE
      ! This appears to be a more precise calculation of the TKE tendency
      ! but is not compatible with the interface of cptend_new and needs
      ! to be reviewed
      DO JLEV=1,KFLEV
        PTENDTKE(JLON, JLEV) = PFTKEI(JLON, JLEV)
      END DO
    END IF
  END IF
  
  !  ------------------------------------------------------------
  !   3.1 CALCUL DE L'EVOLUTION DE EFB1, EFB2 and EFB3
  !  ------------------------------------------------------------
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LEFB) THEN
    DO JLEV=1,KFLEV
      PTENDEFB1(JLON, JLEV) = ZGSDP(JLON, JLEV)*(PFEFB1(JLON, JLEV - 1) - PFEFB1(JLON, JLEV))
      PTENDEFB2(JLON, JLEV) = ZGSDP(JLON, JLEV)*(PFEFB2(JLON, JLEV - 1) - PFEFB2(JLON, JLEV))
      PTENDEFB3(JLON, JLEV) = ZGSDP(JLON, JLEV)*(PFEFB3(JLON, JLEV - 1) - PFEFB3(JLON, JLEV))
    END DO
  END IF
  
  !  ------------------------------------------------------------
  !   ?. CALCUL DE L'EVOLUTION DES SCALAIRES PASSIFS
  !  ------------------------------------------------------------
  
  IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMDUST .and. YDMODEL%YRML_GCONF%YGFL%NGFL_EXT /= 0) THEN
    DO JGFL=1,YDMODEL%YRML_GCONF%YGFL%NGFL_EXT
      DO JLEV=1,KFLEV
        PTENDEXT(JLON, JLEV, JGFL) = ZGSDP(JLON, JLEV)*(PDIFEXT(JLON, JLEV - 1, JGFL) - PDIFEXT(JLON, JLEV, JGFL))
      END DO
    END DO
  END IF
  !
  
  !  ------------------------------------------------------------
  !   4. CALCUL DE L'EVOLUTION DE P ET W (CAS NH)
  !  ------------------------------------------------------------
  
  ! TO DO
  
  !--------------------------------------------------------------------------
  
  
  !-----------------------------------------------------------------------
  
END SUBROUTINE CPTEND_NEW_OPENACC
