SUBROUTINE CUDDRAFN_OPENACC (YDCST, YDTHF, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON, KLEV, LDDRAF, PTENH, PQENH, PQSEN, PGEO, PGEOH,  &
& PAPH, PRFL, PTD, PQD, PMFU, PMFD, PMFDS, PMFDQ, PDMFDP, PDMFDE, PMFDDE_RATE, PKINED, YDSTACK)
  
  !          THIS ROUTINE CALCULATES CUMULUS DOWNDRAFT DESCENT
  
  !          PURPOSE.
  !          --------
  !          TO PRODUCE THE VERTICAL PROFILES FOR CUMULUS DOWNDRAFTS
  !          (I.E. T,Q,U AND V AND FLUXES)
  
  !          INTERFACE
  !          ---------
  
  !          THIS ROUTINE IS CALLED FROM *CUMASTR*.
  !          INPUT IS T,Q,P,PHI,U,V AT HALF LEVELS.
  !          IT RETURNS FLUXES OF S,Q AND EVAPORATION RATE
  !          AND U,V AT LEVELS WHERE DOWNDRAFT OCCURS
  
  !          METHOD.
  !          --------
  !          CALCULATE MOIST DESCENT FOR ENTRAINING/DETRAINING PLUME BY
  !          A) MOVING AIR DRY-ADIABATICALLY TO NEXT LEVEL BELOW AND
  !          B) CORRECTING FOR EVAPORATION TO OBTAIN SATURATED STATE.
  
  !     PARAMETER     DESCRIPTION                                   UNITS
  !     ---------     -----------                                   -----
  !     INPUT PARAMETERS (INTEGER):
  
  !    *KIDIA*        START POINT
  !    *KFDIA*        END POINT
  !    *KLON*         NUMBER OF GRID POINTS PER PACKET
  !    *KLEV*         NUMBER OF LEVELS
  
  !    INPUT PARAMETERS (LOGICAL):
  
  !    *LDDRAF*       .TRUE. IF DOWNDRAFTS EXIST
  
  !    INPUT PARAMETERS (REAL):
  
  !    *PTENH*        ENV. TEMPERATURE (T+1) ON HALF LEVELS          K
  !    *PQENH*        ENV. SPEC. HUMIDITY (T+1) ON HALF LEVELS     KG/KG
  !    *PQSEN*        ENV. SATUR. SPEC. HUMIDITY (T+1)             KG/KG
  !    *PGEO*         GEOPOTENTIAL                                  M2/S2
  !    *PGEOH*        GEOPOTENTIAL ON HALF LEVELS                  M2/S2
  !    *PAPH*         PROVISIONAL PRESSURE ON HALF LEVELS           PA
  !    *PMFU*         MASSFLUX UPDRAFTS                           KG/(M2*S)
  
  !    UPDATED PARAMETERS (REAL):
  
  !    *PRFL*         PRECIPITATION RATE                           KG/(M2*S)
  
  !    OUTPUT PARAMETERS (REAL):
  
  !    *PTD*          TEMPERATURE IN DOWNDRAFTS                      K
  !    *PQD*          SPEC. HUMIDITY IN DOWNDRAFTS                 KG/KG
  !    *PMFD*         MASSFLUX IN DOWNDRAFTS                       KG/(M2*S)
  !    *PMFDS*        FLUX OF DRY STATIC ENERGY IN DOWNDRAFTS       J/(M2*S)
  !    *PMFDQ*        FLUX OF SPEC. HUMIDITY IN DOWNDRAFTS         KG/(M2*S)
  !    *PDMFDP*       FLUX DIFFERENCE OF PRECIP. IN DOWNDRAFTS     KG/(M2*S)
  !    *PMFDDE_RATE*  DOWNDRAFT DETRAINMENT RATE                   KG/(M2*S)
  !    *PKINED*       DOWNDRAFT KINETIC ENERGY                     M2/S2
  
  !          EXTERNALS
  !          ---------
  !          *CUADJTQ* FOR ADJUSTING T AND Q DUE TO EVAPORATION IN
  !          SATURATED DESCENT
  
  !          REFERENCE
  !          ---------
  !          (TIEDTKE,1989)
  
  !     AUTHOR.
  !     -------
  !      M.TIEDTKE         E.C.M.W.F.    12/86 MODIF. 12/89
  
  !     MODIFICATIONS.
  !     --------------
  !      03-08-28 : Clean-up detrainment rates   P. BECHTOLD
  !      M.Hamrud      01-Oct-2003 CY28 Cleaning
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !----------------------------------------------------------------------
  
!$acc routine( CUDDRAFN_OPENACC ) seq
  
  USE YOEPHLI, ONLY: TEPHLI
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  USE YOETHF, ONLY: TTHF
  USE YOECUMF, ONLY: TECUMF
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(TTHF), INTENT(IN) :: YDTHF
  TYPE(TECUMF), INTENT(IN) :: YDECUMF
  TYPE(TEPHLI), INTENT(IN) :: YDEPHLI
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  LOGICAL, INTENT(IN) :: LDDRAF
  REAL(KIND=JPRB), INTENT(IN) :: PTENH(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQENH(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQSEN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PGEO(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PGEOH(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(IN) :: PAPH(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(INOUT) :: PRFL
  REAL(KIND=JPRB), INTENT(INOUT) :: PTD(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PQD(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PMFU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PMFD(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PMFDS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PMFDQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PDMFDP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PDMFDE(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PMFDDE_RATE(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PKINED(KLON, KLEV)
  REAL(KIND=JPRB) :: ZDMFEN
  REAL(KIND=JPRB) :: ZDMFDE
  REAL(KIND=JPRB) :: ZCOND
  REAL(KIND=JPRB) :: ZOENTR
  REAL(KIND=JPRB) :: ZBUOY
  REAL(KIND=JPRB) :: ZPH
  LOGICAL :: LLO2
  INTEGER(KIND=JPIM) :: IK
  INTEGER(KIND=JPIM) :: IS
  INTEGER(KIND=JPIM) :: ITOPDE
  INTEGER(KIND=JPIM) :: JK
  INTEGER(KIND=JPIM) :: JL
  
  REAL(KIND=JPRB) :: ZBUO
  REAL(KIND=JPRB) :: ZBUOYZ
  REAL(KIND=JPRB) :: ZBUOYV
  REAL(KIND=JPRB) :: ZDMFDP
  REAL(KIND=JPRB) :: ZDZ
  REAL(KIND=JPRB) :: ZENTR
  REAL(KIND=JPRB) :: ZMFDQK
  REAL(KIND=JPRB) :: ZMFDSK
  REAL(KIND=JPRB) :: ZQDDE
  REAL(KIND=JPRB) :: ZQEEN
  REAL(KIND=JPRB) :: ZRAIN
  REAL(KIND=JPRB) :: ZSDDE
  REAL(KIND=JPRB) :: ZSEEN
  REAL(KIND=JPRB) :: ZZENTR
  REAL(KIND=JPRB) :: ZRG
  REAL(KIND=JPRB) :: ZFACBUO
  REAL(KIND=JPRB) :: Z_CWDRAG
  REAL(KIND=JPRB) :: ZDKBUO
  REAL(KIND=JPRB) :: ZDKEN
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
#include "cuadjtq.intfb.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JL = KIDIA
  
  ITOPDE = YDECUMF%NJKT3
  ZRG = 1.0_JPRB / YDCST%RG
  ZFACBUO = 0.5_JPRB / (1.0_JPRB + 0.5_JPRB)
  Z_CWDRAG = (3._JPRB / 8._JPRB)*0.506_JPRB / 0.2_JPRB
  !----------------------------------------------------------------------
  
  !     1.           CALCULATE MOIST DESCENT FOR CUMULUS DOWNDRAFT BY
  !                     (A) CALCULATING ENTRAINMENT/DETRAINMENT RATES,
  !                         INCLUDING ORGANIZED ENTRAINMENT DEPENDENT ON
  !                         NEGATIVE BUOYANCY AND ASSUMING
  !                         LINEAR DECREASE OF MASSFLUX IN PBL
  !                     (B) DOING MOIST DESCENT - EVAPORATIVE COOLING
  !                         AND MOISTENING IS CALCULATED IN *CUADJTQ*
  !                     (C) CHECKING FOR NEGATIVE BUOYANCY AND
  !                         SPECIFYING FINAL T,Q,U,V AND DOWNWARD FLUXES
  !                    -------------------------------------------------
  
  ZOENTR = 0.0_JPRB
  ZBUOY = 0.0_JPRB
  ZDMFEN = 0.0_JPRB
  ZDMFDE = 0.0_JPRB
  PDMFDE(JL, :) = 0.0_JPRB
  PMFDDE_RATE(JL, :) = 0.0_JPRB
  PKINED(JL, :) = 0.0_JPRB
  
  DO JK=3,KLEV
    IS = 0
    ZPH = PAPH(JL, JK)
    LLO2 = LDDRAF .and. PMFD(JL, JK - 1) < 0.0_JPRB
    IF (LLO2) THEN
      IS = IS + 1
    END IF
    IF (IS == 0) CYCLE
    
    IF (LLO2) THEN
      ZENTR = YDECUMF%ENTRDD*PMFD(JL, JK - 1)*(PGEOH(JL, JK - 1) - PGEOH(JL, JK))*ZRG
      ! &*(1.6_JPRB-MIN(1.0_JPRB,PQENH(JL,JK-1)/PQSEN(JL,JK)))
      ZDMFEN = ZENTR
      ZDMFDE = ZENTR
    END IF
    
    IF (JK > ITOPDE) THEN
      IF (LLO2) THEN
        ZDMFEN = 0.0_JPRB
        ZDMFDE = PMFD(JL, ITOPDE)*(PAPH(JL, JK) - PAPH(JL, JK - 1)) / (PAPH(JL, KLEV + 1) - PAPH(JL, ITOPDE))
      END IF
    END IF
    
    IF (JK <= ITOPDE) THEN
      IF (LLO2) THEN
        ZDZ = -(PGEOH(JL, JK - 1) - PGEOH(JL, JK))*ZRG
        ZZENTR = ZOENTR*ZDZ*PMFD(JL, JK - 1)
        ZDMFEN = ZDMFEN + ZZENTR
        ZDMFEN = MAX(ZDMFEN, 0.3_JPRB*PMFD(JL, JK - 1))
        ZDMFEN = MAX(ZDMFEN, -0.75_JPRB*PMFU(JL, JK) - (PMFD(JL, JK - 1) - ZDMFDE))
        ZDMFEN = MIN(ZDMFEN, 0.0_JPRB)
      END IF
      
      PDMFDE(JL, JK) = ZDMFEN - ZDMFDE
      
    END IF
    IF (LLO2) THEN
      PMFD(JL, JK) = PMFD(JL, JK - 1) + ZDMFEN - ZDMFDE
      ZSEEN = (YDCST%RCPD*PTENH(JL, JK - 1) + PGEOH(JL, JK - 1))*ZDMFEN
      ZQEEN = PQENH(JL, JK - 1)*ZDMFEN
      ZSDDE = (YDCST%RCPD*PTD(JL, JK - 1) + PGEOH(JL, JK - 1))*ZDMFDE
      ZQDDE = PQD(JL, JK - 1)*ZDMFDE
      ZMFDSK = PMFDS(JL, JK - 1) + ZSEEN - ZSDDE
      ZMFDQK = PMFDQ(JL, JK - 1) + ZQEEN - ZQDDE
      PQD(JL, JK) = ZMFDQK*(1.0_JPRB / MIN(-YDECUMF%RMFCMIN, PMFD(JL, JK)))
      PTD(JL, JK) = (ZMFDSK*(1.0_JPRB / MIN(-YDECUMF%RMFCMIN, PMFD(JL, JK))) - PGEOH(JL, JK)) / YDCST%RCPD
      PTD(JL, JK) = MIN(400._JPRB, PTD(JL, JK))
      PTD(JL, JK) = MAX(100._JPRB, PTD(JL, JK))
      ZCOND = PQD(JL, JK)
    END IF
    
    IK = JK
    CALL CUADJTQ_OPENACC(YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON, KLEV, IK, ZPH, PTD, PQD, LLO2, 2, YDSTACK=YLSTACK)
    
    IF (LLO2) THEN
      ZCOND = ZCOND - PQD(JL, JK)
      ZBUO = PTD(JL, JK)*(1.0_JPRB + YDCST%RETV*PQD(JL, JK)) - PTENH(JL, JK)*(1.0_JPRB + YDCST%RETV*PQENH(JL, JK))
      IF (PRFL > 0.0_JPRB .and. PMFU(JL, JK) > 0.0_JPRB) THEN
        ZRAIN = PRFL / PMFU(JL, JK)
        ZBUO = ZBUO - PTD(JL, JK)*ZRAIN
      END IF
      IF (ZBUO >= 0.0_JPRB .or. PRFL <= (PMFD(JL, JK)*ZCOND)) THEN
        PMFD(JL, JK) = 0.0_JPRB
        ZBUO = 0.0_JPRB
      END IF
      PMFDS(JL, JK) = (YDCST%RCPD*PTD(JL, JK) + PGEOH(JL, JK))*PMFD(JL, JK)
      PMFDQ(JL, JK) = PQD(JL, JK)*PMFD(JL, JK)
      ZDMFDP = -PMFD(JL, JK)*ZCOND
      PDMFDP(JL, JK - 1) = ZDMFDP
      PRFL = PRFL + ZDMFDP
      
      ! COMPUTE ORGANIZED ENTRAINMENT FOR USE AT NEXT LEVEL
      
      ZBUOYZ = ZBUO / PTENH(JL, JK)
      ZBUOYV = ZBUOYZ
      ZBUOYZ = MIN(ZBUOYZ, 0.0_JPRB)
      ZDZ = -(PGEO(JL, JK - 1) - PGEO(JL, JK))
      ZBUOY = ZBUOY + ZBUOYZ*ZDZ
      ZOENTR = YDCST%RG*ZBUOYZ*0.5_JPRB / (1.0_JPRB + ZBUOY)
      
      ! STORE DOWNDRAUGHT DETRAINMENT RATES
      
      PMFDDE_RATE(JL, JK) = -ZDMFDE
      
      ! COMPUTE KINETIC ENERGY
      
      ZDKBUO = ZDZ*ZBUOYV*ZFACBUO
      IF (ZDMFEN < 0.0_JPRB) THEN
        ZDKEN = MIN(1.0_JPRB, (1 + Z_CWDRAG)*ZDMFEN / MIN(-YDECUMF%RMFCMIN, PMFD(JL, JK - 1)))
      ELSE
        ZDKEN = MIN(1.0_JPRB, (1 + Z_CWDRAG)*ZDMFDE / MIN(-YDECUMF%RMFCMIN, PMFD(JL, JK - 1)))
      END IF
      PKINED(JL, JK) = MAX(0.0_JPRB, (PKINED(JL, JK - 1)*(1 - ZDKEN) + ZDKBUO) / (1 + ZDKEN))
      
    END IF
    
  END DO
  
END SUBROUTINE CUDDRAFN_OPENACC
