SUBROUTINE ACFLUSO_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PQ, PT, PU, PV, PDPHIT,  &
& PDPHIU, PGZ0, PLSM, PQSATS, PRTI, PTS, LDHMT, PCD, PCDN, PCDROV, PCE, PCEROV, PCH, PCHROV, PQCLS, PRHCLS, PTCLS, PUCLS, PVCLS,  &
& PURAF, PVRAF, YDSTACK)
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  ! - INPUT  1D .
  ! - INPUT  LOGIQUE .
  ! - OUTPUT 1D .
  
  !     Sujet.
  !     ------
  
  !     - ROUTINE DE CALCUL ACTIF .
  !       DETERMINATION DES COEFFICIENTS D'ECHANGE EN SURFACE
  !       SUR LA MER (MEMO)
  !     - SI L'OPTION 'HMT' EST SELECTIONNEE :
  !          INTERPOLATION DES TEMPERATURES, HUMIDITES (SPECIFIQUES ET
  !          RELATIVES) ET VENTS AUX HAUTEURS "METEO"
  
  !     - COMPUTATION SEA SURFACE EXCHANGE COEFFICIENTS (MEMO)
  !     - IF THE SWITCH 'HMT' IS ON :
  !          TEMPERATURE, MOISTURE (SPECIFIC AND RELATIVE) AND WIND
  !          INTERPOLATION AT STANDARD "METEOROLOGICAL" LEVELS
  
  !**   Interface.
  !     ----------
  !        *CALL* *ACFLUSO*
  
  !-----------------------------------------------------------------------
  ! WARNING: THE ENGLISH VERSION OF VARIABLES' NAMES IS TO BE READ IN THE
  !          "APLPAR" CODE.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS D'ENTREE.
  !     -------------------
  
  ! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.
  
  ! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
  ! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
  ! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
  ! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 2D (0:KLEV) .
  
  ! PAPHI      : GEOPOTENTIEL AUX DEMI-NIVEAUX.
  ! PAPRS      : PRESSION AUX DEMI-NIVEAUX.
  
  ! - 2D (1:KLEV) .
  
  ! PAPHIF     : GEOPOTENTIEL AUX NIVEAUX DES COUCHES.
  ! PAPRSF     : PRESSION AUX NIVEAUX.
  ! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
  ! PT         : TEMPERATURE.
  ! PU         : COMPOSANTE EN X DU VENT.
  ! PV         : COMPOSANTE EN Y DU VENT.
  
  ! - 1D
  
  ! PDPHIT     : HAUTEUR D INTERPOLATION POUR T ET Q (EN GEOPOTENTIEL).
  ! PDPHIU     : HAUTEUR D INTERPOLATION POUR U ET V (EN GEOPOTENTIEL).
  ! PGZ0       : G FOIS LA LONGUEUR DE RUGOSITE COURANTE.
  ! PQSATS     : HUMIDITE SPECIFIQUE DE SATURATION EN SURFACE.
  ! PRTI       : INVERSE DE R*T.
  ! PTS        : TEMPERATURE DE SURFACE.
  
  ! - 1D (GEOGRAPHIQUE) .
  
  ! PLSM       : INDICE TERRE/MER.
  
  ! - LOGIQUES .
  
  ! LDHMT      : CALCULS NECESSAIRES A L'INTERPOLATION AUX HAUTEURS METEO
  !              DU VENT, DE LA TEMPERATURE ET DE L'HUMIDITE.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS DE SORTIE.
  !     --------------------
  
  ! PCD        : COEFFICIENT D'ECHANGE EN SURFACE POUR U ET V.
  ! PCDN       : COEFFICIENT NEUTRE D'ECHANGE EN SURFACE.
  ! PCDROV     : PCD RENORME EN DENSITE FOIS VITESSE.
  ! PCE        : COEFFICIENT D'ECHANGE EN SURFACE POUR Q.
  ! PCEROV     : PCE RENORME EN DENSITE FOIS VITESSE.
  ! PCH        : COEFFICIENT D'ECHANGE EN SURFACE POUR T.
  ! PCHROV     : PCH RENORME EN DENSITE FOIS VITESSE.
  ! PQCLS      : SORTIE DIAGNOSTIQUE DE L'HUMIDITE SPECIFIQUE A HTQ METEO.
  ! PRHCLS     : SORTIE DIAGNOSTIQUE DE L'HUMIDITE RELATIVE A HTQ METEO.
  ! PTCLS      : SORTIE DIAGNOSTIQUE DE LA TEMPERATURE A HTQ METEO.
  ! PUCLS      : SORTIE DIAGNOSTIQUE DU VENT EN X A HUV METEO.
  ! PVCLS      : SORTIE DIAGNOSTIQUE DU VENT EN Y A HUV METEO.
  ! PURAF      : SORTIE DIAGNOSTIQUE DU VENT DE RAFALES TURBULENTES EN X
  ! PVRAF      : SORTIE DIAGNOSTIQUE DU VENT DE RAFALES TURBULENTES EN Y
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS IMPLICITES.
  !     ---------------------
  
  ! COMMON/YOMPHY /
  ! COMMON/YOMCST /
  ! COMMON/YOMPHY0/
  ! COMMON/YOMPHY2/
  ! COMMON/FCTTRM /
  
  !-----------------------------------------------------------------------
  
  !     Externes.
  !     ---------
  
  !     *fnct_psi*
  
  !     Methode.
  !     --------
  
  !     Auteur.
  !     -------
  !        07-03, J.F. Gueremy d'apres S. Belamari.
  
  !     Modifications.
  !     --------------
  !      2007-03, P. Marquet : introduction of ZICHCE=1 if LFLCHCE=.TRUE.
  !                            => PCE=PCH as output
  !      2007-04, P. Marquet : introduction of NITERFL, LFLWEG
  !      2007-10, P. Marquet : NITERFL, LFLWEG, LFLCHCE : definis localement
  !                            pour les tests UDC de octobre 2007
  !        M.Hamrud      01-Oct-2003 CY28 Cleaning
  !      2008-03, F. Bouyssel : NITERFL, LFLWEG, LFLCHCE en namelist
  !      2008-09, F. Bouyssel : Vectorisation de la routine
  !                             Suppression LFLCHCE, LFLWEG. Ajout RFLCHCE
  !      2009-02, E. Bazile: Bug correction for wind gust.
  !      K. Yessad (Jul 2009): remove CDLOCK + some cleanings
  !      2012-04-19, F. Bouyssel: link between coefficient for temperature and coefficient for humidity
  !      2016-10-04, P. Marguinaud : Port to single precision
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
!$acc routine( ACFLUSO_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB, JPRD
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PT(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PV(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PDPHIT(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PDPHIU(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PGZ0(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PLSM(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PQSATS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PRTI(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PTS(KLON)
  LOGICAL, INTENT(IN) :: LDHMT
  REAL(KIND=JPRB), INTENT(INOUT) :: PCD(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCDN(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCDROV(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCE(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PCEROV(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCH(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCHROV(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PQCLS(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PRHCLS(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PTCLS(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PUCLS(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PVCLS(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PURAF(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PVRAF(KLON)
  
  !-----------------------------------------------------------------------
  
  REAL(KIND=JPRB) :: ZCEN
  REAL(KIND=JPRB) :: ZCHN
  REAL(KIND=JPRB) :: ZDELTAQ10N
  REAL(KIND=JPRB) :: ZDELTAT10N
  REAL(KIND=JPRB) :: ZDELTAU10N
  REAL(KIND=JPRB) :: ZDQ
  REAL(KIND=JPRB) :: ZDTH
  REAL(KIND=JPRB) :: ZDU
  REAL(KIND=JPRB) :: ZHT
  REAL(KIND=JPRB) :: ZQ
  REAL(KIND=JPRB) :: ZQSR
  REAL(KIND=JPRB) :: ZT
  REAL(KIND=JPRB) :: ZTS
  REAL(KIND=JPRB) :: ZTSR
  REAL(KIND=JPRB) :: ZUSR
  REAL(KIND=JPRB) :: ZDPHI
  REAL(KIND=JPRB) :: ZCIS
  REAL(KIND=JPRB) :: ZLSM
  
  REAL(KIND=JPRB) :: ZDELTAU10NODU  ! ZDELTAU10N / ZDU
  REAL(KIND=JPRB) :: ZDELTAT10NODT  ! ZDELTAT10N / ZDTH
  REAL(KIND=JPRB) :: ZDELTAQ10NODQ  ! ZDELTAQ10N / ZDQ
  
  REAL(KIND=JPRB) :: ZUSRODU  ! ZUSR / ZDU
  REAL(KIND=JPRB) :: ZTSRODT  ! ZTSR / ZDTH
  REAL(KIND=JPRB) :: ZQSRODQ  ! ZQSR / ZDQ
  
  
  INTEGER(KIND=JPIM) :: JJ
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPRB) :: ZDELTA
  REAL(KIND=JPRB) :: ZDQCLS
  REAL(KIND=JPRB) :: ZDTCLS
  REAL(KIND=JPRB) :: ZDUCLS
  REAL(KIND=JPRB) :: ZEPS
  REAL(KIND=JPRB) :: ZEPS1
  REAL(KIND=JPRB) :: ZEW
  REAL(KIND=JPRB) :: ZLMO
  REAL(KIND=JPRB) :: ZLMOMAX
  REAL(KIND=JPRB) :: ZLMOMIN
  REAL(KIND=JPRB) :: ZLMOTCLS
  REAL(KIND=JPRB) :: ZLMOUCLS
  REAL(KIND=JPRB) :: ZLOGHS10
  REAL(KIND=JPRB) :: ZPCLS
  REAL(KIND=JPRB) :: ZPSI_T
  REAL(KIND=JPRB) :: ZPSI_U
  REAL(KIND=JPRB) :: ZQSR1
  REAL(KIND=JPRB) :: ZQSR2
  REAL(KIND=JPRB) :: ZSCRAF
  REAL(KIND=JPRB) :: ZTSR1
  REAL(KIND=JPRB) :: ZTSR2
  REAL(KIND=JPRB) :: ZUSR1
  REAL(KIND=JPRB) :: ZUSR2
  REAL(KIND=JPRB) :: ZICHCE
  REAL(KIND=JPRB) :: ZCEFAC
  REAL(KIND=JPRB) :: ZCHIK
  REAL(KIND=JPRB) :: ZPSIK
  REAL(KIND=JPRB) :: ZPSIKU
  REAL(KIND=JPRB) :: ZPSIKT
  REAL(KIND=JPRB) :: ZCHIC
  REAL(KIND=JPRB) :: ZPSIC
  REAL(KIND=JPRB) :: ZPIS2
  REAL(KIND=JPRB) :: ZPI
  REAL(KIND=JPRB) :: ZSQR3
  
  REAL(KIND=JPRB) :: ZLSM0
  REAL(KIND=JPRB) :: ZLSM1
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  !-----------------------------------------------------------------------
  
#include "fcttrm.func.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON = KIDIA
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  
  !     ------------------------------------------------------------------
  
  !         AUXILIARY CONSTANTS.
  
  ZEPS = 1.E-12_JPRB
  ZEPS1 = 1.E-04_JPRB
  ZLMOMAX = 0.25_JPRB
  ZLMOMIN = -200._JPRB
  ZPIS2 = 2.0_JPRB*ATAN(1.0_JPRB)
  ZPI = 2.0_JPRB*ZPIS2
  ZSQR3 = SQRT(3.0_JPRB)
  
  ZICHCE = MAX(0.0_JPRB, YDML_PHY_MF%YRPHY0%RFLCHCE)
  ZCEFAC = MAX(1.0_JPRB, -YDML_PHY_MF%YRPHY0%RFLCHCE)
  
  !         INITIALISATIONS BEFORE ITERATIVE LOOP.
  
  ZLSM = PLSM(JLON) + (1.0_JPRB - PLSM(JLON))*MAX(0.0_JPRB, SIGN(1.0_JPRB, YDML_PHY_MF%YRPHY1%TMERGL - PTS(JLON)))
  ZDPHI = PAPHIF(JLON, KLEV) - PAPHI(JLON, KLEV)
  ZCIS = PU(JLON, KLEV)**2 + PV(JLON, KLEV)**2 + (YDML_PHY_MF%YRPHY0%GEVAVF*ZDPHI / YDCST%RG)**2
  ZDU = SQRT(ZCIS)
  ZT = PT(JLON, KLEV) - YDCST%RTT
  ZTS = PTS(JLON) - YDCST%RTT
  ZQ = PQ(JLON, KLEV)
  ZHT = (PAPHIF(JLON, KLEV) - PAPHI(JLON, KLEV)) / YDCST%RG
  ZDQ = ZQ - PQSATS(JLON)
  ZDTH = ZT - ZTS + ZHT*YDCST%RG / YDCST%RCPD
  ZUSR = 0.04_JPRB*ZDU
  ZTSR = 0.04_JPRB*ZDTH
  ZQSR = 0.04_JPRB*ZDQ
  ZDELTAU10N = ZDU
  ZDELTAT10N = ZDTH
  ZDELTAQ10N = ZDQ
  ZDELTAU10NODU = 1._JPRB
  ZDELTAT10NODT = 1._JPRB
  ZDELTAQ10NODQ = 1._JPRB
  
  !         ITERATIVE LOOP TO COMPUTE U*, T*, Q*.
  
  DO JJ=1,YDML_PHY_MF%YRPHY%NITERFL
    
    !cdir iexpand(FNCT_PSI)
    ZUSR1 = ZUSR
    ZTSR1 = ZTSR
    ZQSR1 = ZQSR
    ! Neutral coefficient for wind speed cdn
    IF (ZDELTAU10N <= 16.8_JPRB) THEN
      PCDN(JLON) =  &
      & (-2.2261E-07_JPRB*ZDELTAU10N**3) + (1.3067E-05_JPRB*ZDELTAU10N**2) + (-1.2719E-04_JPRB*ZDELTAU10N) + 1.3013E-03_JPRB
    ELSE IF (ZDELTAU10N <= 50._JPRB) THEN
      PCDN(JLON) = (4.2684E-09_JPRB*ZDELTAU10N**4) + (-4.8208E-07_JPRB*ZDELTAU10N**3) + (1.6212E-05_JPRB*ZDELTAU10N**2) +  &
      & (-0.00013056_JPRB*ZDELTAU10N) + 0.0013633_JPRB
    ELSE
      PCDN(JLON) = 1.7828E-3_JPRB
    END IF
    ! Neutral coefficient for temperature chn
    IF (ZDELTAU10N <= 33._JPRB) THEN
      ZCHN = (3.5763E-12_JPRB*ZDELTAU10N**5) + (3.4517E-09_JPRB*ZDELTAU10N**4) + (-0.00043701E-03_JPRB*ZDELTAU10N**3) +  &
      & (0.016038E-03_JPRB*ZDELTAU10N**2) + (-0.12455E-03_JPRB*ZDELTAU10N) + 1.2536E-03_JPRB
    ELSE
      ZCHN = 3.1374E-3_JPRB
    END IF
    ! Neutral coefficient for humidity cen
    IF (ZDELTAU10N <= 29._JPRB) THEN
      ZCEN = (5.0864E-09_JPRB*ZDELTAU10N**4) + (-3.9144E-07_JPRB*ZDELTAU10N**3) + (1.1467E-05_JPRB*ZDELTAU10N**2) +  &
      & (-0.00011384_JPRB*ZDELTAU10N) + 0.0012687_JPRB
    ELSE IF (ZDELTAU10N <= 33._JPRB) THEN
      ZCEN = (-2.6995E-06_JPRB*ZDELTAU10N**2) + (1.8229E-04_JPRB*ZDELTAU10N) + (-1.3526E-03_JPRB)
    ELSE
      ZCEN = 1.7232E-03_JPRB
    END IF
    
    ZUSR2 = SQRT(PCDN(JLON))
    ZTSR2 = ZCHN / SQRT(PCDN(JLON))
    ZQSR2 = (ZCEFAC*ZCEN*(1.0_JPRB - ZICHCE) + ZCHN*ZICHCE) / SQRT(PCDN(JLON))
    
    ZUSRODU = ZUSR2*ZDELTAU10NODU
    ZTSRODT = ZTSR2*ZDELTAT10NODT
    ZQSRODQ = ZQSR2*ZDELTAQ10NODQ
    
    ZUSR2 = ZUSR2*ZDELTAU10N
    ZTSR2 = ZTSR2*ZDELTAT10N
    ZQSR2 = ZQSR2*ZDELTAQ10N
    
    ZLMO = YDCST%RG*YDML_PHY_MF%YRPHY0%VKARMN*ZHT*(ZTSR2*(1.0_JPRB + YDCST%RETV*ZQ) + YDCST%RETV*(ZT + YDCST%RTT)*ZQSR2) / ((ZT + &
    &  YDCST%RTT)*(1.0_JPRB + YDCST%RETV*ZQ)*ZUSR2*ZUSR2)
    ZLMO = MAX(MIN(ZLMO, ZLMOMAX), ZLMOMIN)
    IF (ZLMO == 0._JPRB) THEN
      ZPSI_U = 0._JPRB
      ZPSI_T = 0._JPRB
    ELSE IF (ZLMO > 0._JPRB) THEN
      ZPSI_U = -7.0_JPRB*ZLMO
      ZPSI_T = -7.0_JPRB*ZLMO
    ELSE
      ZCHIK = (1.0_JPRB - 16.0_JPRB*ZLMO)**0.25_JPRB
      ZPSIKU = 2.0_JPRB*LOG((1.0_JPRB + ZCHIK) / 2.0_JPRB) + LOG((1.0_JPRB + ZCHIK**2) / 2.0_JPRB) - 2.0_JPRB*ATAN(ZCHIK) + ZPIS2
      ZPSIKT = 2.0_JPRB*LOG((1.0_JPRB + ZCHIK**2) / 2.0_JPRB)
      ZCHIC = (1.0_JPRB - 12.87_JPRB*ZLMO)**0.333_JPRB
      ZPSIC =  &
      & 1.5_JPRB*LOG((ZCHIC**2 + ZCHIC + 1.0_JPRB) / 3.0_JPRB) - ZSQR3*ATAN((2.0_JPRB*ZCHIC + 1.0_JPRB) / ZSQR3) + ZPI / ZSQR3
      ZPSI_U = ZPSIC + (ZPSIKU - ZPSIC) / (1.0_JPRB + ZLMO**2)
      ZPSI_T = ZPSIC + (ZPSIKT - ZPSIC) / (1.0_JPRB + ZLMO**2)
    END IF
    ZLOGHS10 = LOG(ZHT / 10._JPRB)
    
    ZDELTAU10N = ZDU - ZUSR2*(ZLOGHS10 - ZPSI_U) / YDML_PHY_MF%YRPHY0%VKARMN
    ZDELTAT10N = ZDTH - ZTSR2*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    ZDELTAQ10N = ZDQ - ZQSR2*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    
    ZUSR = ZUSR2
    ZTSR = ZTSR2
    ZQSR = ZQSR2
    
    ZDELTAU10NODU = 1._JPRB - ZUSRODU*(ZLOGHS10 - ZPSI_U) / YDML_PHY_MF%YRPHY0%VKARMN
    ZDELTAT10NODT = 1._JPRB - ZTSRODT*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    ZDELTAQ10NODQ = 1._JPRB - ZQSRODQ*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    
  END DO
  
  !         COMPUTATION OF EXCHANGE COEFFICIENTS AND VARIABLES AT
  !         STANDARD "METEOROLOGICAL" LEVELS.
  
  !DEC$ IVDEP
  ZLSM0 = ZLSM
  ZLSM1 = 1.0_JPRB - ZLSM
  
  PCD(JLON) = ZLSM0*PCD(JLON) + ZLSM1*ZUSRODU**2
  PCH(JLON) = ZLSM0*PCH(JLON) + ZLSM1*ZUSRODU*ZTSRODT
  PCE(JLON) = ZLSM0*PCH(JLON) + ZLSM1*(ZUSRODU*ZQSRODQ*(1.0_JPRB - ZICHCE) + PCH(JLON)*ZICHCE)
  
  PCDROV(JLON) = ZLSM0*PCDROV(JLON) + ZLSM1*PCD(JLON)*ZDU*PAPRS(JLON, KLEV)*PRTI(JLON)
  PCHROV(JLON) = ZLSM0*PCHROV(JLON) + ZLSM1*PCH(JLON)*ZDU*PAPRS(JLON, KLEV)*PRTI(JLON)
  PCEROV(JLON) =  &
  & ZLSM0*PCHROV(JLON) + ZLSM1*(PCE(JLON)*ZDU*PAPRS(JLON, KLEV)*PRTI(JLON)*(1.0_JPRB - ZICHCE) + PCHROV(JLON)*ZICHCE)
  
  IF (LDHMT) THEN
    ZLMOUCLS = YDML_PHY_MF%YRPHY0%VKARMN*PDPHIU(JLON)*(ZTSR*(1.0_JPRB + YDCST%RETV*ZQ) + YDCST%RETV*(ZT + YDCST%RTT)*ZQSR) / ((ZT &
    &  + YDCST%RTT)*(1.0_JPRB + YDCST%RETV*ZQ)*ZUSR*ZUSR)
    ZLMOTCLS = ZLMOUCLS*PDPHIT(JLON) / PDPHIU(JLON)
    ZLMOUCLS = MAX(MIN(ZLMOUCLS, ZLMOMAX), ZLMOMIN)
    ZLMOTCLS = MAX(MIN(ZLMOTCLS, ZLMOMAX), ZLMOMIN)
    IF (ZLMOUCLS == 0._JPRB) THEN
      ZPSI_U = 0._JPRB
    ELSE IF (ZLMOUCLS > 0._JPRB) THEN
      ZPSI_U = -7.0_JPRB*ZLMOUCLS
    ELSE
      ZCHIK = (1.0_JPRB - 16.0_JPRB*ZLMOUCLS)**0.25_JPRB
      ZPSIK = 2.0_JPRB*LOG((1.0_JPRB + ZCHIK) / 2.0_JPRB) + LOG((1.0_JPRB + ZCHIK**2) / 2.0_JPRB) - 2.0_JPRB*ATAN(ZCHIK) + ZPIS2
      ZCHIC = (1.0_JPRB - 12.87_JPRB*ZLMOUCLS)**0.333_JPRB
      ZPSIC =  &
      & 1.5_JPRB*LOG((ZCHIC**2 + ZCHIC + 1.0_JPRB) / 3.0_JPRB) - ZSQR3*ATAN((2.0_JPRB*ZCHIC + 1.0_JPRB) / ZSQR3) + ZPI / ZSQR3
      ZPSI_U = ZPSIC + (ZPSIK - ZPSIC) / (1.0_JPRB + ZLMOUCLS**2)
    END IF
    IF (ZLMOTCLS == 0._JPRB) THEN
      ZPSI_T = 0._JPRB
    ELSE IF (ZLMOTCLS > 0._JPRB) THEN
      ZPSI_T = -7.0_JPRB*ZLMOTCLS
    ELSE
      ZCHIK = (1.0_JPRB - 16.0_JPRB*ZLMOTCLS)**0.25_JPRB
      ZPSIK = 2.0_JPRB*LOG((1.0_JPRB + ZCHIK**2) / 2.0_JPRB)
      ZCHIC = (1.0_JPRB - 12.87_JPRB*ZLMOTCLS)**0.333_JPRB
      ZPSIC =  &
      & 1.5_JPRB*LOG((ZCHIC**2 + ZCHIC + 1.0_JPRB) / 3.0_JPRB) - ZSQR3*ATAN((2.0_JPRB*ZCHIC + 1.0_JPRB) / ZSQR3) + ZPI / ZSQR3
      ZPSI_T = ZPSIC + (ZPSIK - ZPSIC) / (1.0_JPRB + ZLMOTCLS**2)
    END IF
    ZLOGHS10 = LOG(PDPHIU(JLON) / 10._JPRB / YDCST%RG)
    ZDUCLS = ZDELTAU10N + ZUSR*(ZLOGHS10 - ZPSI_U) / YDML_PHY_MF%YRPHY0%VKARMN
    PUCLS(JLON) = ZLSM0*PUCLS(JLON) + ZLSM1*PU(JLON, KLEV)*ZDUCLS / ZDU
    PVCLS(JLON) = ZLSM0*PVCLS(JLON) + ZLSM1*PV(JLON, KLEV)*ZDUCLS / ZDU
    ZLOGHS10 = LOG(PDPHIT(JLON) / 10._JPRB / YDCST%RG)
    ZDTCLS = ZDELTAT10N + ZTSR*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    PTCLS(JLON) = ZLSM0*PTCLS(JLON) + ZLSM1*(ZDTCLS + PTS(JLON) - PDPHIT(JLON) / YDCST%RCPD)
    ZDQCLS = ZDELTAQ10N + ZQSR*(ZLOGHS10 - ZPSI_T) / YDML_PHY_MF%YRPHY0%VKARMN
    PQCLS(JLON) = ZLSM0*PQCLS(JLON) + ZLSM1*(ZDQCLS + PQSATS(JLON))
    IF (YDML_PHY_MF%YRPHY%LNEIGE) THEN
      ZDELTA = MAX(0.0_JPRB, SIGN(1.0_JPRB, YDCST%RTT - PTCLS(JLON)))
    ELSE
      ZDELTA = 0.0_JPRB
    END IF
    ZPCLS = PAPRS(JLON, KLEV) + PDPHIT(JLON) / (YDCST%RG*ZHT)*(PAPRSF(JLON, KLEV) - PAPRS(JLON, KLEV))
    ZEW = FOEW(PTCLS(JLON), ZDELTA)
    PRHCLS(JLON) =  &
    & ZLSM0*PRHCLS(JLON) + ZLSM1*(ZPCLS*PQCLS(JLON)*(YDCST%RETV + 1.0_JPRB)) / (ZEW*(1.0_JPRB + YDCST%RETV*PQCLS(JLON)))
  END IF
  
  
  !         GUSTINESS.
  
  IF (YDML_PHY_MF%YRPHY2%LRAFTUR) THEN
    !DEC$ IVDEP
    ZSCRAF = (PCD(JLON)*(PU(JLON, KLEV)**2 + PV(JLON, KLEV)**2) / MAX(ZEPS1, PUCLS(JLON)**2 + PVCLS(JLON)**2)) / (1.0_JPRB +  &
    & (LOG(1.0_JPRB + PDPHIU(JLON) / YDML_PHY_MF%YRPHY2%GZ0RAF) / LOG(1.0_JPRB + PDPHIU(JLON) / PGZ0(JLON)))**2)
    ZSCRAF = 1.0_JPRB + YDML_PHY_MF%YRPHY2%FACRAF*SQRT(ZSCRAF)
    PURAF(JLON) = ZLSM*PURAF(JLON) + (1.0_JPRB - ZLSM)*ZSCRAF*PUCLS(JLON)
    PVRAF(JLON) = ZLSM*PVRAF(JLON) + (1.0_JPRB - ZLSM)*ZSCRAF*PVCLS(JLON)
  END IF
  
  !-----------------------------------------------------------------------
END SUBROUTINE ACFLUSO_OPENACC
