SUBROUTINE ARP_GROUND_PARAM_OPENACC (YDCST, YDMCC, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, KCSS, PAPHI, PCP, PFRSO, PQ,  &
& PRDELP, PT, PU, PV, PXURO, PXQRO, PXTRO, PAPRS, PQL, PQI, PCOEFN, PCD, PCDN, PCDROV, PCHROV, PCEROV, PCPS, PCT, PDQSTS, PEMIS,  &
& PFHPS, PHQ, PHTR, PHU, PHV, PLSM, PIVEG, PNEIJ, PQS, PQSATS, PTP, PTS, PVEG, PXDROV, PXHROV, PWS, PWSI, PDSE, PCFAS, PCFAU,  &
& PCFBS, PCFBU, PCFBV, PCFBQ, PCOEFA, PALPHA1, PLVT, PQICE, PDIFWQ, PDIFWS, PSFU, PSFV, PSC_FEVI, PSC_FEVN, PSC_FCLL, PSC_FCLN,  &
& PFCHSP, PFCLL, PFCLN, PFCS, PFEVI, PFEVL, PFEVN, PFEVV, PFTR, PLHS, PQSH, PFRTH, PGZ0F, PGZ0HF, YDSTACK)
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  ! - INPUT  1D .
  ! - INPUT  2D from acdifv1.f90
  ! -- OUTPUT 2-D for acdifv2.f90
  ! - OUTPUT 1D .
  ! - OUTPUT 1D .
  ! - INPUT/OUTPUT 2D .
  ! - INPUT/OUTPUT 1D .
  
  !!     Sujet.
  !     ------
  !     - ROUTINE DE CALCUL ACTIF .
  !       CALCULS DES FLUX EN SURFACE INCLUANT LA CORRECTION
  !       DES HUMIDITES NEGATIVES : FLUX TURBULENTS VERTICAUX, APPEL A LA
  !       FORMULE DE CHARNOCK, CORRECTION DES FLUX DE RAYONNEMENT
  !       THERMIQUE ET TOUS LES FLUX AU ET DANS LE SOL CORRESPONDANTS .
  !     - COMPUTATION OF SURFACE FLUX INCLUDING A NEGATIVE
  !       HUMIDITY CORRECTION : VERTICAL TURBULENT FLUXES, CALL TO THE
  !       CHARNOCK FORMULA, THERMAL RADIATION FLUXES' CORRECTION AND ALL
  !       CORRESPONDING FLUXES AT THE SURFACE OR IN THE SOIL .
  
  !**   Interface.
  !     ----------
  !        *CALL* *ARP_GROUND_PARAM*
  
  !-----------------------------------------------------------------------
  ! WARNING: THE ENGLISH VERSION OF VARIABLES' NAMES IS TO BE READ IN THE
  !          "APLPAR" CODE.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS D'ENTREE.
  !     -------------------
  
  ! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.
  
  ! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
  ! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
  ! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
  ! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
  ! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
  ! KCSS       : NOMBRE DE NIVEAUX PROFONDS DANS LE SOL (1 SI LSOLV=.F.).
  
  ! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
  !   CATEGORIE).
  
  ! - 2D (0:KLEV) .
  
  ! PAPHI      : GEOPOTENTIEL AUX DEMI-NIVEAUX.
  ! PFRSO      : FLUX DE RAYONNEMENT SOLAIRE.
  ! PKTROV     : COEFFICIENT D'ECHANGE VERTICAL DE T ET Q EN KG/(M*M*S).
  ! PKUROV     : COEFFICIENT D'ECHANGE VERTICAL DE U ET V EN KG/(M*M*S).
  ! PKNROV     : COEFFICIENT D'ECHANGE VERTICAL NEUTRE (U,V) EN KG/(M*M*S).
  ! PXTROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PKTROV.
  ! PXUROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PKUROV.
  ! PXPTKEROV  : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PTKEROV
  
  ! - 2D (1:KLEV) .
  
  ! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
  ! PDELP      : EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
  ! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
  ! PT         : TEMPERATURE.
  ! PU         : COMPOSANTE EN X DU VENT.
  ! PV         : COMPOSANTE EN Y DU VENT.
  ! PAPRSF     : PRESSION AUX NIVEAUX DES COUCHES.
  ! PR         : CONSTANTE DES GAZ POUR L'AIR.
  ! PQL        : HUMIDITE SPECIFIQUE DE L'EAU LIQUIDE.
  ! PQI        : HUMIDITE SPECIFIQUE DE L'EAU GLACE.
  ! PCOEFN     : COEFFICIENT STATISTIQUE POUR LES FLUX D'EAUX CONDENSEES.
  ! PTKE       : TURBULENT KINETIC ENERGY
  ! PALPH      : LOG(PAPRS(JLEV)/PAPRSF(JLEV)) (FOR HYDROSTATICS).
  ! PLNPR      : LOG(PAPRS(JLEV)/PAPRS(JLEV-1)) (FOR HYDROSTATICS).
  ! PTENDPTKE  : TKE INCREMENT (USED BY PSEUDOPROGNOSTIC TKE SCHEME)
  
  ! - 1D (PROGNOSTIQUE) .
  
  ! PTP        : TEMPERATURE EN PROFONDEUR.
  !     (KCSS)
  ! PTS        : TEMPERATURE DE SURFACE.
  ! PWS        : RESERVOIR D'EAU SUPERFICIEL.
  ! PWSI       : RESERVOIR D'EAU GELEE SUPERFICIEL.
  
  ! - 1D (GEOGRAPHIQUE) .
  
  ! PLSM       : INDICE TERRE/MER.
  ! PIVEG      : TABLEAU PERMETTANT D'IDENTIFIER LE TYPE DE VEGETATION
  !              DANS CHAQUE MAILLE DU DOMAINE SIMULE.
  ! PVEG       : PROPORTION DE SOL COUVERT PAR LA VEGETATION.
  
  ! - 1D (DIAGNOSTIQUE) .
  
  ! PCD        : COEFFICIENT D'ECHANGE EN SURFACE POUR U ET V.
  ! PCDN       : COEFFICIENT NEUTRE D'ECHANGE EN SURFACE.
  ! PCDROV     : PCD RENORME EN DENSITE FOIS VITESSE.
  ! PCHROV     : PCH RENORME EN DENSITE FOIS VITESSE.
  ! PCEROV     : PCE RENORME EN DENSITE FOIS VITESSE.
  ! PCPS       : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR AU SOL.
  ! PCT        : COEFFICIENT THERMIQUE DU MILIEU SOL-VEGETATION.
  ! PDQSTS     : DERIVEE DE PQSATS PAR RAPPORT A LA TEMPERATURE.
  ! PEMIS      : EMISSIVITE DE SURFACE COURANTE.
  ! PFHPS      : FLUX DE CHALEUR VERS LE SOL ASSOCIE AUX PRECIPITATIONS.
  ! PHQ        : POIDS DE L'HUMIDITE DE L'AIR DANS L'HUMIDITE DE SURFACE.
  ! PHU        : POIDS DE L'HUMIDITE SATURANTE DANS L'HUMIDITE DE SURFACE.
  ! PHTR       : RESISTANCE A LA TRANSPIRATION DU COUVERT VEGETAL.
  ! PHV        : RESISTANCE A L'EVAPOTRANSPIRATION DU COUVERT VEGETAL.
  ! PNEIJ      : PROPORTION DE SOL ENNEIGE.
  ! PQS        : HUMIDITE SPECIFIQUE DE SURFACE.
  ! PQSATS     : HUMIDITE SPECIFIQUE DE SATURATION EN SURFACE.
  ! PXDROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PCDROV.
  ! PXHROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PCHROV.
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS DE SORTIE.
  !     --------------------
  
  ! - 1D
  
  ! PDIFWQ     : FLUX TURBULENT (ET Q NEGATIF) D'HUMIDITE SPECIFIQUE.
  ! PDIFWS     : FLUX TURBULENT D'ENTHALPIE (OU D'ENERGIE STATIQUE SECHE).
  ! PSFU       : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "U".
  ! PSFV       : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "V".
  
  ! - 2D (1:KLEV) .
  
  ! PTENDPTKE  : TENDENCE D'ENERGIE CINETIQUE TURBULENTE.
  
  ! - 1D (DIAGNOSTIQUE) .
  
  ! PFCHSP     : FLUX DE CHALEUR DE LA SURFACE VERS LE SOL PROFOND.
  !     (KCSS)
  ! PFCLL      : FLUX DE CHALEUR LATENTE SUR EAU LIQUIDE (OU SOL HUMIDE).
  ! PFCLN      : FLUX DE CHALEUR LATENTE SUR NEIGE (OU GLACE).
  ! PFCS       : FLUX DE CHALEUR SENSIBLE EN SURFACE.
  ! PFEVI      : FLUX DE VAPEUR D'EAU SUR SOL GELE.
  ! PFEVL      : FLUX DE VAPEUR D'EAU SUR EAU LIQUIDE (OU SOL HUMIDE).
  ! PFEVN      : FLUX DE VAPEUR D'EAU SUR NEIGE (OU GLACE).
  ! PFEVV      : FLUX D'EVAPOTRANSPIRATION.
  ! PFTR       : FLUX DE TRANSPIRATION.
  ! PLHS       : CHALEUR LATENTE EN SURFACE.
  ! PQSH       : TOTAL SPEC. MOISTURE AT SURFACE DIAGNOSED FROM FLUX - FOR MOIST Ri COMPUTATION
  ! PSC_*      : multiplicators for corresponding fluxes - used after TOMs for update of fluxes
  
  
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS EN ENTREE/SORTIE.
  !     ---------------------------
  
  ! - 2D (0:KLEV) .
  
  ! PFRTH      : FLUX DE RAYONNEMENT THERMIQUE.
  
  ! - 1D (GEOGRAPHIQUE) .
  
  ! PGZ0F      : CHAMP TEMPOREL DE G FOIS LA LONGUEUR DE RUGOSITE.
  ! PGZ0HF     : CHAMP TEMPOREL DE G FOIS LA LONGUEUR DE RUGOSITE THERM.
  
  !-----------------------------------------------------------------------
  
  !     Auteur.
  !     -------
  !        2008-02, R. Brozkova
  
  !     Modified.
  !     ---------
  !        2008-05, F. Bouyssel Introduction de PCEROV
  !        K. Yessad (Jul 2009): remove CDLOCK + some cleanings
  !        I. Bastak-Duran, F. Vana  26-Jan-2012  new arrays for TOMs
  !     R. El Khatib 22-Jun-2022 A contribution to simplify phasing after the refactoring of YOMCLI/YOMCST/YOETHF.
  !-----------------------------------------------------------------------
  
  ! -   ARGUMENTS IMPLICITES.
  !     ---------------------
  
  ! COMMON/YOMPHY /
  ! COMMON/YOMCST /
  ! COMMON/YOMMCC /
  ! COMMON/YOMPHY0/
  ! COMMON/YOMPHY1/
  ! COMMON/YOMPHY2/
  ! COMMON/FCTTRM /
  
  !-----------------------------------------------------------------------
  
!$acc routine( ARP_GROUND_PARAM_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  USE YOMMCC, ONLY: TMCC
  
  !-----------------------------------------------------------------------
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(TMCC), INTENT(IN) :: YDMCC
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  INTEGER(KIND=JPIM), INTENT(IN) :: KCSS
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
  REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PFRSO(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PRDELP(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PT(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PV(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQL(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PQI(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCOEFN(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCD(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCDN(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCDROV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCHROV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCEROV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCPS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCT(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PDQSTS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PEMIS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PFHPS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PHQ(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PHTR(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PHU(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PHV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PLSM(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PIVEG(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PNEIJ(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PQS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PQSATS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PTP(KLON, KCSS)
  REAL(KIND=JPRB), INTENT(IN) :: PTS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PVEG(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PXDROV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PXHROV(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PWS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PWSI(KLON)
  
  ! - OUTPUT  2D for acdifv2.f90
  REAL(KIND=JPRB), INTENT(OUT) :: PCFBQ(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PALPHA1(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PCOEFA(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PLVT(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(OUT) :: PQICE(KLON, 0:KLEV)
  ! - INPUT  2D from acdifv1.f90
  REAL(KIND=JPRB), INTENT(IN) :: PDSE(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCFAS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PCFAU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCFBS(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCFBU(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PCFBV(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PXURO(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PXQRO(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PXTRO(KLON, 0:KLEV)
  
  REAL(KIND=JPRB), INTENT(OUT) :: PDIFWQ(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PDIFWS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSFU(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSFV(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCHSP(KLON, KCSS)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCLL(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCLN(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFCS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFEVI(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFEVL(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFEVN(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFEVV(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFTR(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PLHS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PQSH(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSC_FEVI(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSC_FEVN(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSC_FCLL(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSC_FCLN(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PFRTH(KLON, 0:KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PGZ0F(KLON)
  REAL(KIND=JPRB), INTENT(INOUT) :: PGZ0HF(KLON)
  
  !-----------------------------------------------------------------------
  
  temp (REAL (KIND=JPRB), ZN1, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZN2, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZSUB1, (KLON, KLEV))
  temp (REAL (KIND=JPRB), ZSUB2, (KLON, KLEV))
  REAL(KIND=JPRB) :: ZCSVT
  REAL(KIND=JPRB) :: ZRHST
  REAL(KIND=JPRB) :: ZXLRO
  REAL(KIND=JPRB) :: ZCHRL
  REAL(KIND=JPRB) :: ZCHRS
  REAL(KIND=JPRB) :: ZCQVQ
  REAL(KIND=JPRB) :: ZCQVT
  REAL(KIND=JPRB) :: ZCSDT
  REAL(KIND=JPRB) :: ZCTVQ
  REAL(KIND=JPRB) :: ZCTVS
  REAL(KIND=JPRB) :: ZCTVT
  REAL(KIND=JPRB) :: ZDLLS
  REAL(KIND=JPRB) :: ZDLLW
  REAL(KIND=JPRB) :: ZDLS
  REAL(KIND=JPRB) :: ZDRCN
  temp (REAL (KIND=JPRB), ZDTPL, (KLON, KCSS))
  REAL(KIND=JPRB) :: ZLHS
  REAL(KIND=JPRB) :: ZLHW
  REAL(KIND=JPRB) :: ZPN
  REAL(KIND=JPRB) :: ZRCOR
  REAL(KIND=JPRB) :: ZRHSQ
  REAL(KIND=JPRB) :: ZRHSS
  REAL(KIND=JPRB) :: ZSUBS
  REAL(KIND=JPRB) :: ZNTS
  REAL(KIND=JPRB) :: ZWSI
  REAL(KIND=JPRB) :: ZXDRO
  REAL(KIND=JPRB) :: ZXSRO
  
  REAL(KIND=JPRB) :: ZGDT
  REAL(KIND=JPRB) :: ZMUL
  
  temp (REAL (KIND=JPRB), ZIPOI, (KLON, KLEV))
  
  temp (REAL (KIND=JPRB), ZQT, (KLON, KLEV))
  
  INTEGER(KIND=JPIM) :: JCSS
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  
  REAL(KIND=JPRB) :: ZCPVMD
  REAL(KIND=JPRB) :: ZCPVMS
  REAL(KIND=JPRB) :: ZCPVMW
  REAL(KIND=JPRB) :: ZDIVIS
  REAL(KIND=JPRB) :: ZDLDQ
  REAL(KIND=JPRB) :: ZELIM
  REAL(KIND=JPRB) :: ZEPS1
  REAL(KIND=JPRB) :: ZFENT
  REAL(KIND=JPRB) :: ZFQ
  REAL(KIND=JPRB) :: ZPUL
  REAL(KIND=JPRB) :: ZMERL
  REAL(KIND=JPRB) :: ZDQSATL
  REAL(KIND=JPRB) :: ZLV
  REAL(KIND=JPRB) :: ZLIQ
  REAL(KIND=JPRB) :: ZDQSATI
  REAL(KIND=JPRB) :: ZLS
  REAL(KIND=JPRB) :: ZICE
  REAL(KIND=JPRB) :: ZQSATL
  REAL(KIND=JPRB) :: ZTLI
  REAL(KIND=JPRB) :: ZSRVCPT2
  REAL(KIND=JPRB) :: ZTH
  REAL(KIND=JPRB) :: ZQSATI
  REAL(KIND=JPRB) :: ZCPH
  REAL(KIND=JPRB) :: ZEISP
  REAL(KIND=JPRB) :: ZELSP
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  !-----------------------------------------------------------------------
  
#include "fcttrm.func.h"
#include "fctdoi.func.h"
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  alloc (ZN1)
  alloc (ZN2)
  alloc (ZSUB1)
  alloc (ZSUB2)
  alloc (ZDTPL)
  alloc (ZIPOI)
  alloc (ZQT)
  JLON = KIDIA
  
  !-----------------------------------------------------------------------
  !-----------------------------------------------------------------------
  
  !     ------------------------------------------------------------------
  !     0 - FORCAGES DES FLUX DE SURFACE, DIFF VERT DES VARIABLES CONSERV.
  !         SURFACE FLUXES FORCING TERMS, VERT DIFF OF CONSERV VARIABLES.
  
  
  DO JLEV=KTDIA,KLEV
    ZN1(JLON, JLEV) = 0.0_JPRB
    ZN2(JLON, JLEV) = 0.0_JPRB
    ZSUB1(JLON, JLEV) = 0.0_JPRB
    ZSUB2(JLON, JLEV) = 0.0_JPRB
  END DO
  
  
  
  IF (YDML_PHY_MF%YRPHY%LDIFCONS) THEN
    DO JLEV=KTDIA,KLEV
      ZQT(JLON, JLEV) = PQ(JLON, JLEV) + PQL(JLON, JLEV) + PQI(JLON, JLEV)
    END DO
    !     GOING TO HALF-LEVELS FOR THE OTHER COMPUTATIONS.
    
    DO JLEV=KTDIA,KLEV - 1
      !DEC$ IVDEP
      ZTH = (PT(JLON, JLEV) + PT(JLON, JLEV + 1))*0.5_JPRB
      ZLV = FOLH(ZTH, 0.0_JPRB)
      ZLS = FOLH(ZTH, 1.0_JPRB)
      PQICE(JLON, JLEV) = FONICE(ZTH, YDML_PHY_MF%YRPHY0%RDTFAC)
      ZCPH = (PCP(JLON, JLEV) + PCP(JLON, JLEV + 1))*0.5_JPRB
      ZTLI = ZTH - 0.5_JPRB*(ZLV*(PQL(JLON, JLEV) + PQL(JLON, JLEV + 1)) + ZLS*(PQI(JLON, JLEV) + PQI(JLON, JLEV + 1))) / ZCPH
      ZICE = PQICE(JLON, JLEV)
      ZLIQ = 1.0_JPRB - ZICE
      PLVT(JLON, JLEV) = ZLV*ZLIQ + ZLS*ZICE
      ZEISP = FOEW(ZTLI, 1.0_JPRB) / PAPRS(JLON, JLEV)
      ZELSP = FOEW(ZTLI, 0.0_JPRB) / PAPRS(JLON, JLEV)
      ZQSATI = FOQS(ZEISP)
      ZQSATL = FOQS(ZELSP)
      ZSRVCPT2 = 1.0_JPRB / (YDCST%RV*ZTLI*ZTLI*ZCPH)
      ZDQSATI = ZQSATI*FOLH(ZTLI, 1.0_JPRB)*ZSRVCPT2
      ZDQSATL = ZQSATL*FOLH(ZTLI, 0.0_JPRB)*ZSRVCPT2
      PALPHA1(JLON, JLEV) = (ZLIQ*ZDQSATL + ZICE*ZDQSATI)
      PCOEFA(JLON, JLEV) =  &
      & (PCOEFN(JLON, JLEV) + PCOEFN(JLON, JLEV + 1))*0.5_JPRB / ((1.0_JPRB + ZDQSATL*ZLV)*ZLIQ + (1.0_JPRB + ZDQSATI*ZLS)*ZICE)
    END DO
    
  ELSE
    
    ! - - - - - - - - - - - - - - - - - - - - - - - - -
    ! Set the "moist" variables to "dry" neutral values
    ! - - - - - - - - - - - - - - - - - - - - - - - - -
    DO JLEV=KTDIA,KLEV
      ZQT(JLON, JLEV) = PQ(JLON, JLEV)
    END DO
    
    DO JLEV=KTDIA,KLEV - 1
      PQICE(JLON, JLEV) = 0.0_JPRB
      PLVT(JLON, JLEV) = 0.0_JPRB
      PALPHA1(JLON, JLEV) = 0.0_JPRB
      PCOEFA(JLON, JLEV) = 0.0_JPRB
    END DO
    
    
  END IF
  
  !*
  !     ------------------------------------------------------------------
  !     II - CALCUL DES PARAMETRES DERIVES
  
  !          COMPUTATION OF DERIVED PARAMETERS
  
  ZGDT = YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
  
  
  
  !     ------------------------------------------------------------------
  !     I - CONSTANTES AUXILIAIRES.
  
  !         AUXILIARY CONSTANTS.
  
  ZCPVMD = YDCST%RCPV - YDCST%RCPD
  ZCPVMW = YDCST%RCPV - YDCST%RCW
  ZCPVMS = YDCST%RCPV - YDCST%RCS
  
  !*
  !     ------------------------------------------------------------------
  !     II - CALCUL DES PARAMETRES DERIVES ET CONSTANTE DE SECURITE (POUR
  !     CSDT).
  
  !          COMPUTATION OF DERIVED PARAMETERS AND SECURITY CONSTANT (FOR
  !     CSDT).
  
  
  
  ZPUL = 2.0_JPRB*YDCST%RPI / YDCST%RDAY
  
  ZEPS1 = 1.E-08_JPRB
  
  
  !*
  !     ------------------------------------------------------------------
  !     III - MISE A DES VALEURS CONSTANTES DES VALEURS DERIVEES DE
  !     L'INERTIE THERMIQUE ET DU TEMPS CARACTERISTIQUE (DIURNE PAR
  !     DEFINITION) DU SOL (PHYSIQUE DU SOL HYPER-SIMPLIFIEE).
  
  !           SETTING TO CONSTANT VALUES OF THE VALUES DERIVED FROM THE
  !     SOIL'S THERMAL INERTIA AND CHARACTERISTIC TIME (DIURNAL BY
  !     DEFINITION) (HYPER-SIMPLIFIED SOIL PHYSICS).
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZCSDT     : PRODUIT DU PAS DE TEMPS PAR LA CONSTANTE DU SOL.
  !            : PRODUCT OF THE TIME-STEP BY THE SOIL CONSTANT.
  ! ZDTPL     : PRODUIT DU PAS DE TEMPS PAR LA PULSATION DIURNE.
  !     (KCSS)
  !            : PRODUCT OF THE TIME-STEP BY THE DIURNAL PULSATION.
  
  !     CALCULS OPTIONNELS SUIVANT LE TYPE DE SCHEMA SOL/VEG CHOISI.
  !     OPTIONAL COMPUTATIONS ACCORDING TO THE CHOSEN SOIL/VEG SCHEME.
  
  IF (YDML_PHY_MF%YRPHY%LSOLV) THEN
    ZCSDT = PLSM(JLON)*YDML_PHY_MF%YRPHY2%TSPHY*PCT(JLON)
    DO JCSS=1,KCSS
      ZDIVIS = 1.0_JPRB / (YDML_PHY_MF%YRPHY1%SODELX(0)*(YDML_PHY_MF%YRPHY1%SODELX(JCSS - 1) + YDML_PHY_MF%YRPHY1%SODELX(JCSS)))
      IF (YDML_PHY_MF%YRPHY1%NCHSP == 0) THEN
        ZDTPL(JLON, JCSS) = PLSM(JLON)*YDML_PHY_MF%YRPHY2%TSPHY*ZPUL*ZDIVIS
      ELSE
        ZDTPL(JLON, JCSS) = PLSM(JLON)*YDML_PHY_MF%YRPHY2%TSPHY*ZPUL*ZDIVIS*(1.0_JPRB - PNEIJ(JLON)**YDML_PHY_MF%YRPHY1%NCHSP)
      END IF
    END DO
  ELSE
    ZCSDT = PLSM(JLON)*YDML_PHY_MF%YRPHY2%TSPHY*PCT(JLON)
    ZDTPL(JLON, 1) = PLSM(JLON)*YDML_PHY_MF%YRPHY2%TSPHY*ZPUL
    DO JCSS=2,KCSS
      ZDTPL(JLON, JCSS) = 0.0_JPRB
    END DO
  END IF
  
  
  !*
  
  DO JLEV=KTDIA,KLEV
    ZIPOI(JLON, JLEV) = PRDELP(JLON, JLEV)*ZGDT
  END DO
  
  !     AMPLIFICATION EVENTUELLE "ANTI-FIBRILLATION" DES COEFFICIENTS
  !     D'ECHANGE.
  !     POTENTIAL "ANTI-FIBRILLATION" AMPLIFICATION OF THE EXCHANGE
  !     COEFFICIENTS.
  
  ZXDRO = PCDROV(JLON)*PXDROV(JLON)
  
  !     ------------------------------------------------------------------
  !     VI - CALCULS POUR LA QUANTITE DE MOUVEMENT : CONDITION DE SURFACE,
  !     CALCUL DE "CHARNOCK" PUIS SUBSTITUTION AVEC CALCUL DES FLUX A TOUS
  !     LES NIVEAUX.
  
  !          COMPUTATION FOR MOMENTUM : SURFACE CONDITION, "CHARNOCK-TYPE"
  !     CALCULATION THEN SUBSTITUTION WITH FLUXES' COMPUTATION AT ALL
  !     LEVELS.
  
  !     CALCULS EN SURFACE.
  !     SURFACE CALCULATIONS.
  
  
  !DEC$ IVDEP
  
  ZELIM = PXURO(JLON, KLEV - 1)*ZIPOI(JLON, KLEV)
  ZMUL = 1.0_JPRB / (1.0_JPRB + ZELIM*(1.0_JPRB - PCFAU(JLON, KLEV - 1)) + ZXDRO*ZIPOI(JLON, KLEV))
  PCFBU(JLON, KLEV) = ZMUL*(PU(JLON, KLEV) + ZELIM*PCFBU(JLON, KLEV - 1))
  PCFBV(JLON, KLEV) = ZMUL*(PV(JLON, KLEV) + ZELIM*PCFBV(JLON, KLEV - 1))
  
  ZMERL = (1.0_JPRB - PLSM(JLON))*(1.0_JPRB - MAX(0.0_JPRB, SIGN(1.0_JPRB, YDML_PHY_MF%YRPHY1%TMERGL - PTS(JLON))))
  PGZ0F(JLON) = PGZ0F(JLON) + ZMERL*(YDCST%RG*YDML_PHY_MF%YRPHY0%VZ0CM*PCD(JLON) / PCDN(JLON) +  &
  & YDML_PHY_MF%YRPHY0%VCHRNK*PCD(JLON)*SQRT((PCFBU(JLON, KLEV)**2 + PCFBV(JLON, KLEV)**2)*(PU(JLON, KLEV)**2 + PV(JLON, KLEV)**2 &
  & )) - PGZ0F(JLON))
  PGZ0HF(JLON) = PGZ0HF(JLON) + ZMERL*(PGZ0F(JLON)*EXP(-SQRT(PCD(JLON)*SQRT((PCFBU(JLON, KLEV)**2 + PCFBV(JLON, KLEV)**2) &
  & *(PU(JLON, KLEV)**2 + PV(JLON, KLEV)**2)))*YDML_PHY_MF%YRPHY0%VZIUSTAR0) - PGZ0HF(JLON))
  PSFU(JLON) = PCDROV(JLON)*PCFBU(JLON, KLEV)
  PSFV(JLON) = PCDROV(JLON)*PCFBV(JLON, KLEV)
  
  !*
  !     ------------------------------------------------------------------
  !     VII - CALCULS PRELIMINAIRES AU SOL POUR LE COUPLAGE DES SOLUTIONS
  !     IMPLICITES EN S ET Q A TRAVERS LA VALEUR DE TS (ON AURA DEUX
  !     VALEURS, A PRIORI EGALES, DU COEFFICIENT CH NORMALISE POUR LES
  !     ETUDES DE SENSIBILITE AUX CHALEURS LATENTES/SENSIBLES).
  
  !           PRELIMINARY COMPUTATIONS AT THE SURFACE FOR THE COUPLING OF
  !     THE IMPLICIT SOLUTIONS IN S AND Q THROUGH THE TS VALUE (ONE WILL
  !     HAVE TWO VALUES, A PRIORI IDENTICAL, OF THE NORMALIZED CH
  !     COEFFICIENT TO ALLOW SENSITIVITY STUDIES FOR SENSIBLE/LATENT
  !     HEATS).
  
  
  !     CALCULS CORRESPONDANT A EVAPORATION/SUBLIMATION.
  !     COMPUTATIONS CORRESPONDING TO EVAPORATION/SUBLIMATION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZPN       : PROPORTION DE LA SURFACE EVAPORANT EN PHASE GLACE.
  !           : PROPORTION OF THE SURFACE EVAPORATING IN ICE PHASE.
  ! ZWSI      : PROPORTION DE GLACE DANS LE RESERVOIR DE SURFACE.
  !           : PROPORTION OF ICE IN THE SUPERFICIAL RESERVOIR.
  
  IF (YDML_PHY_MF%YRPHY%LNEIGE) THEN
    IF (YDML_PHY_MF%YRPHY%LFGEL) THEN
      ZWSI = MIN(1.0_JPRB, PWSI(JLON) / MAX(PWSI(JLON) + PWS(JLON), ZEPS1))
    ELSE
      ZWSI = 0.0_JPRB
    END IF
    ZPN = PLSM(JLON)*(PNEIJ(JLON) + (1.0_JPRB - PNEIJ(JLON))*ZWSI) + (1.0_JPRB - PLSM(JLON))*MAX(0.0_JPRB, SIGN(1.0_JPRB,  &
    & YDML_PHY_MF%YRPHY1%TMERGL - PTS(JLON)))
    IF (YDML_PHY_MF%YRPHY%LSOLV .and. YDMCC%LMCC02) THEN
      IF (NINT(PIVEG(JLON)) == YDML_PHY_MF%YRPHY1%NTVGLA) ZPN = 1.0_JPRB
    END IF
  ELSE
    ZPN = 0.0_JPRB
  END IF
  
  !     CALCUL DE LA CHALEUR LATENTE PONDEREE ET DE SES DEUX CONTRIBUTIONS
  !     PAR APPEL A LA FONCTION DEFINIE.
  !     COMPUTATION OF THE WEIGHTED LATENT HEAT AND OF ITS TWO COMPONENTS
  !     THROUGH CALLS TO THE DEFINED FUNCTION.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZLHW      : CONTRIBUTION DE LA PHASE LIQUIDE A LA CHALEUR LATENTE.
  !            : CONTRIBUTION OF THE LIQUID PHASE TO THE LATENT HEAT.
  ! ZLHS      : CONTRIBUTION DE LA PHASE GLACE A LA CHALEUR LATENTE.
  !            : CONTRIBUTION OF THE ICE PHASE TO THE LATENT HEAT.
  
  ZLHW = (1.0_JPRB - ZPN)*FOLH(PTS(JLON), 0.0_JPRB)
  ZLHS = ZPN*FOLH(PTS(JLON), 1.0_JPRB)
  PLHS(JLON) = ZLHW + ZLHS
  
  !     DIFFERENTIATION DU COEFFICIENT D'ECHANGE EN SURFACE ENTRE CHALEUR
  !     LATENTE/SENSIBLE.
  !     DIFFERENTIATION BETWEEN THE SURFACE EXCHANGE COEFFICIENTS FOR
  !     LATENT/SENSIBLE HEAT.
  
  !     AMPLIFICATION EVENTUELLE "ANTI-FIBRILLATION" DES COEFFICIENTS
  !     D'ECHANGE.
  !     POTENTIAL "ANTI-FIBRILLATION" AMPLIFICATION OF THE EXCHANGE
  !     COEFFICIENTS.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZCHRL     : COEFFICIENT D'ECHANGE PCHROV POUR LA CHALEUR LATENTE.
  !            : EXCHANGE COEFFICIENT PCHROV FOR LATENT HEAT.
  ! ZCHRS     : COEFFICIENT D'ECHANGE PCHROV POUR LA CHALEUR SENSIBLE.
  !            : EXCHANGE COEFFICIENT PCHROV FOR SENSIBLE HEAT.
  
  ZCHRL = PCEROV(JLON)
  ZXLRO = ZCHRL*PXHROV(JLON)
  ZCHRS = PCHROV(JLON)
  ZXSRO = ZCHRS*PXHROV(JLON)
  
  
  !     CONTRIBUTION AUX COEFFICIENTS DE LA MATRICE TRIDIAGONALE.
  !     CONTRIBUTION TO THE COEFFICIENTS OF THE TRIDIAGONAL MATRIX.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZDLS      : DERIVEE EN TEMPERATURE DU FLUX TOTAL ; PARTIE SENSIBLE.
  !            : TEMPERATURE DERIVATIVE OF THE TOTAL FLUX ; SENSIBLE PART.
  ! ZDLLW     : COMME ZDLS ; MOINS PARTIE LATENTE, PHASE LIQUIDE.
  !            : AS ZDLS ; MINUS LATENT PART, LIQUID PHASE.
  ! ZDLLS     : COMME ZDLS ; MOINS PARTIE LATENTE, PHASE GLACE.
  !            : AS ZDLS ; MINUS LATENT PART, ICE PHASE.
  ! ZDRCN     : MOINS DERIVEE EN TEMPERATURE DU FLUX DE RAYONNEMENT.
  !            : MINUS TEMPERATURE DERIVATIVE OF THE RADIATIVE FLUX.
  ! ZCQVQ     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT Q A Q.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING Q TO Q.
  ! ZCTVQ     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT TS A Q.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING TS TO Q.
  ! ZRHSQ     : CONTRIBUTION AU MEMBRE DE DROITE POUR LA LIGNE EN Q.
  !            : CONTRIBUTION TO THE RIGHT HAND SIDE FOR THE Q LINE.
  ! ZCTVS     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT TS A S.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING TS TO S.
  ! ZRHSS     : CONTRIBUTION AU MEMBRE DE DROITE POUR LA LIGNE EN S.
  !            : CONTRIBUTION TO THE RIGHT HAND SIDE FOR THE S LINE.
  ! ZCSVT     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT S A TS.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING S TO TS.
  ! ZCTVT     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT TS A TS.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING TS TO TS.
  ! ZCQVT     : CONTRIBUTION AU COEFFICIENT MATRICIEL LIANT Q A TS.
  !            : CONTRIBUTION TO THE MATRIX COEFFICIENT LINKING Q TO TS.
  ! ZRHST     : CONTRIBUTION AU MEMBRE DE DROITE POUR LA LIGNE EN TS.
  !            : CONTRIBUTION TO THE RIGHT HAND SIDE FOR THE TS LINE.
  
  ZDLS = (PQS(JLON) - PQ(JLON, KLEV))*ZCHRS*ZCPVMD
  ZDLLW = (PQS(JLON) - PQ(JLON, KLEV))*ZCHRL*ZCPVMW*(1.0_JPRB - ZPN)
  ZDLLS = (PQS(JLON) - PQ(JLON, KLEV))*ZCHRL*ZCPVMS*ZPN
  ZDLDQ = ZDLLW + ZDLLS - ZDLS
  ZDRCN = PEMIS(JLON)*4._JPRB*YDCST%RSIGMA*PTS(JLON)*PTS(JLON)*PTS(JLON)
  ZCQVQ = 1.0_JPRB - PHQ(JLON)
  ZCTVQ = PHU(JLON)*PDQSTS(JLON)
  ZRHSQ = PHU(JLON)*(PQSATS(JLON) - PTS(JLON)*PDQSTS(JLON))
  ZCTVS = PCPS(JLON) + ZCPVMD*PTS(JLON)*ZCTVQ
  ZRHSS = PAPHI(JLON, KLEV) - ZCPVMD*PTS(JLON)*ZCTVQ*PTS(JLON)
  ZCSVT = ZCHRS*ZCSDT
  ZCSVT = ZCSVT*PXHROV(JLON)
  ZCTVT = ZDTPL(JLON, 1) + ZCSDT*(ZDRCN + ZDLDQ + ZCHRL*PLHS(JLON)*ZCTVQ + ZCHRS*PCPS(JLON))
  ZCTVT = ZCTVT*PXHROV(JLON)
  ZCQVT = ZCQVQ*ZCSDT*(ZCHRL*PLHS(JLON) - ZCHRS*ZCPVMD*PTS(JLON))
  ZCQVT = ZCQVT*PXHROV(JLON)
  
  ZRHST = ZDTPL(JLON, 1)*PTP(JLON, 1) + ZCSDT*(PFRSO(JLON, KLEV) + PFRTH(JLON, KLEV) + (ZDRCN + ZDLDQ)*PTS(JLON) -  &
  & ZCHRL*PLHS(JLON)*ZRHSQ - ZCHRS*(PAPHI(JLON, KLEV) - ZCPVMD*PHU(JLON)*PTS(JLON)*PQSATS(JLON)))
  IF (YDML_PHY_MF%YRPHY%LPHSPSH) THEN
    ZRHST = ZRHST + PFHPS(JLON)*ZCSDT
  END IF
  ZRHST = ZRHST*PXHROV(JLON)
  
  !*
  !     ------------------------------------------------------------------
  !     VIII - CALCULS POUR LA TEMPERATURE ET L'HUMIDITE SPECIFIQUE :
  !     PARTIE ELIMINATION. COMME A LA SURFACE ON DIFFERENTIE LES
  !     COEFFICIENTS NORMALISES (A PRIORI EGAUX) POUR S ET Q.
  
  !            COMPUTATION FOR TEMPERATURE AND SPECIFIC HUMIDITY :
  !     ELIMINATION PART. LIKE AT THE SURFACE ONE DIFFERENTIATES THE
  !     (A PRIORI EQUAL) NORMALIZED COEFFICIENTS FOR S AND Q.
  
  
  
  
  !     CALCULS D'ELIMINATION EN SURFACE POUR S, TS ET Q.
  !     SURFACE ELIMINATION CALCULATION FOR S, TS AND Q.
  
  ZELIM = PXTRO(JLON, KLEV - 1)*ZIPOI(JLON, KLEV)
  ZMUL = 1.0_JPRB / (1.0_JPRB + ZELIM*(1.0_JPRB - PCFAS(JLON, KLEV - 1)) + ZXSRO*ZIPOI(JLON, KLEV))
  ZSUB1(JLON, KLEV) = ZMUL*ZXSRO*ZIPOI(JLON, KLEV)*ZCTVS
  PCFBS(JLON, KLEV) = ZMUL*(PDSE(JLON, KLEV) + ZXSRO*ZIPOI(JLON, KLEV)*ZRHSS + ZELIM*PCFBS(JLON, KLEV - 1))
  
  ZELIM = ZCSVT
  ZMUL = 1.0_JPRB / (1.0_JPRB - ZELIM*ZSUB1(JLON, KLEV) + ZCTVT)
  ZSUBS = ZMUL*ZCQVT
  ZNTS = ZMUL*(PTS(JLON) + ZRHST + ZELIM*PCFBS(JLON, KLEV))
  
  
  ZELIM = ZXLRO*ZIPOI(JLON, KLEV)*ZCTVQ
  ZMUL = 1.0_JPRB / (1.0_JPRB - ZELIM*ZSUBS + ZXLRO*ZIPOI(JLON, KLEV)*ZCQVQ + PXQRO(JLON, KLEV - 1)*ZIPOI(JLON, KLEV))
  ZSUB2(JLON, KLEV) = ZMUL*PXQRO(JLON, KLEV - 1)*ZIPOI(JLON, KLEV)
  ZN2(JLON, KLEV) = ZMUL*(ZQT(JLON, KLEV) + ZXLRO*ZIPOI(JLON, KLEV)*ZRHSQ + ZELIM*ZNTS)
  
  
  !     ELIMINATION POUR UNE COUCHE STANDARD POUR L'HUMIDITE SPECIFIQUE
  !     CORRIGEE DES VALEURS NEGATIVES, Q.
  !     ELIMINATION FOR A STANDART LAYER FOR THE SPECIFIC HUMIDITY
  !     CORRECTED FROM NEGATIVE VALUES, Q.
  
  DO JLEV=KLEV - 1,KTDIA + 1,-1
    ZELIM = PXQRO(JLON, JLEV)*ZIPOI(JLON, JLEV)
    ZMUL = 1.0_JPRB / (1.0_JPRB + ZELIM*(1.0_JPRB - ZSUB2(JLON, JLEV + 1)) + PXQRO(JLON, JLEV - 1)*ZIPOI(JLON, JLEV))
    ZSUB2(JLON, JLEV) = ZMUL*PXQRO(JLON, JLEV - 1)*ZIPOI(JLON, JLEV)
    ZN2(JLON, JLEV) = ZMUL*(ZQT(JLON, JLEV) + ZELIM*ZN2(JLON, JLEV + 1))
  END DO
  
  !     ELIMINATION AU SOMMET POUR Q.
  !     TOP ELIMINATION FOR Q.
  
  ZELIM = PXQRO(JLON, KTDIA)*ZIPOI(JLON, KTDIA)
  ZMUL = 1.0_JPRB / (1.0_JPRB + ZELIM*(1.0_JPRB - ZSUB2(JLON, KTDIA + 1)))
  ZN2(JLON, KTDIA) = ZMUL*(ZQT(JLON, KTDIA) + ZELIM*ZN2(JLON, KTDIA + 1))
  
  !     SUBSTITUTION POUR UNE COUCHE STANDARD POUR Q.
  !     BACK-SUBSTITUTION FOR A STANDART LEVEL FOR Q.
  
  DO JLEV=KTDIA + 1,KLEV
    ZN2(JLON, JLEV) = ZN2(JLON, JLEV) + ZSUB2(JLON, JLEV)*ZN2(JLON, JLEV - 1)
  END DO
  
  
  DO JLEV=KTDIA,KLEV
    PCFBQ(JLON, JLEV) = ZN2(JLON, JLEV)
  END DO
  
  
  !     CALCULS DE SUBSTITUTION EN SURFACE POUR TS ET S.
  !     SURFACE BACK-SUBSTITUTION CALCULATIONS FOR TS AND S.
  
  ZNTS = ZNTS + ZSUBS*ZN2(JLON, KLEV)
  PCFBS(JLON, KLEV) = PCFBS(JLON, KLEV) + ZSUB1(JLON, KLEV)*ZNTS
  
  
  !     SUBSTITUTION POUR UNE COUCHE STANDARD ET AU SOMMET POUR S.
  !     BACK-SUBSTITUTION FOR A STANDART LEVEL AND AT THE TOP FOR S.
  
  DO JLEV=KLEV - 1,KTDIA,-1
    PCFBS(JLON, JLEV) = PCFBS(JLON, JLEV) + PCFAS(JLON, JLEV)*PCFBS(JLON, JLEV + 1)
  END DO
  
  !     FLUX EN SURFACE ET DANS LE SOL.
  !     SURFACE AND SOIL FLUXES.
  
  ! - TEMPORAIRE(S) 1D .
  
  ! ZRCOR     : CORRECTION UNIFORME DU RAYONNEMENT THERMIQUE.
  !            : UNIFORM CORRECTION FOR THE THERMAL RADIATION FLUX.
  
  ZFQ = ZCHRL*(ZCQVQ*ZN2(JLON, KLEV) - ZCTVQ*ZNTS - ZRHSQ)
  PFEVI(JLON) = ZFQ*ZWSI*(1.0_JPRB - PNEIJ(JLON))
  PFEVL(JLON) = ZFQ*(1.0_JPRB - ZPN)
  PFEVN(JLON) = ZFQ*ZPN
  PFCLL(JLON) = ZLHW*ZFQ - ZDLLW*(ZNTS - PTS(JLON))
  PFCLN(JLON) = ZLHS*ZFQ - ZDLLS*(ZNTS - PTS(JLON))
  PFCHSP(JLON, 1) = (ZNTS - PTP(JLON, 1))*ZDTPL(JLON, 1) / MAX(ZEPS1, ZCSDT)
  ZFENT = ZCHRS*(PCFBS(JLON, KLEV) - ZCTVS*ZNTS - ZRHSS)
  PFCS(JLON) = ZFENT - ZCPVMD*PTS(JLON)*ZFQ + ZDLS*(ZNTS - PTS(JLON))
  ZRCOR = -ZDRCN*(ZNTS - PTS(JLON))
  PFRTH(JLON, KLEV) = PFRTH(JLON, KLEV) + ZRCOR
  PDIFWQ(JLON) = ZFQ
  PDIFWS(JLON) = ZFENT
  
  ! storage of multiplicators for correction after TOMs
  PSC_FEVI(JLON) = ZWSI*(1.0_JPRB - PNEIJ(JLON))
  PSC_FEVN(JLON) = ZPN
  PSC_FCLL(JLON) = ZLHW
  PSC_FCLN(JLON) = ZLHS
  
  !     CALCULS OPTIONNELS POUR UN TYPE DE SCHEMA SOL/VEG.
  !     OPTIONAL COMPUTATIONS FOR ONE SOIL/VEG SCHEME.
  
  IF (YDML_PHY_MF%YRPHY%LSOLV) THEN
    PFEVV(JLON) = ZCHRL*PVEG(JLON)*(PHV(JLON) - PNEIJ(JLON))*(ZN2(JLON, KLEV) - PQSATS(JLON) - PDQSTS(JLON)*(ZNTS - PTS(JLON)))
    PFTR(JLON) = MAX(0.0_JPRB, SIGN(1.0_JPRB, PQSATS(JLON) - PQ(JLON, KLEV)))*ZCHRL*PHTR(JLON)*PVEG(JLON)*(1.0_JPRB - PNEIJ(JLON) &
    & )*(ZN2(JLON, KLEV) - PQSATS(JLON) - PDQSTS(JLON)*(ZNTS - PTS(JLON)))
  END IF
  
  
  !     AUTRES COUCHES PROFONDES (S'IL Y EN A).
  !     OTHER DEEP LAYERS (IF ANY).
  
  DO JCSS=2,KCSS
    PFCHSP(JLON, JCSS) = (PTP(JLON, JCSS - 1) - PTP(JLON, JCSS))*ZDTPL(JLON, JCSS) / MAX(ZEPS1, ZCSDT)
  END DO
  
  !     FLUX ATMOSPHERIQUES.
  !     ATMOSPHERIC FLUXES.
  
  DO JLEV=KLEV - 1,KTDIA,-1
    PFRTH(JLON, JLEV) = PFRTH(JLON, JLEV) + ZRCOR
  END DO
  
  !     CONDITION A LA LIMITE SUPERIEURE.
  !     UPPER BOUNDARY CONDITION.
  
  PFRTH(JLON, KTDIA - 1) = PFRTH(JLON, KTDIA - 1) + ZRCOR
  
  IF (YDML_PHY_MF%YRPHY%LCOEFKTKE) THEN
    PQSH(JLON) = ZQT(JLON, KLEV) - PDIFWQ(JLON) / (PCHROV(JLON)*PXHROV(JLON))
  END IF
  
  !-----------------------------------------------------------------------
END SUBROUTINE ARP_GROUND_PARAM_OPENACC
