
SUBROUTINE ACDIFV2_OPENACC (LDSFORCS, YDCST, YGFL, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PAPRS, PCFAQ, PCFAS, PCFAU, PCFASV, PCFBQ, PCFBS, PCFBU, PCFBV, PCFBSV, PKTROV,&
& PKQROV, PKQLROV, PKUROV, PDSE, PQT, PU, PV, POID, PT, PQL, PQI, PRDELP, PCOEFA, PALPHA1&
&, PLVT, PQICE, PSFSV, PFCS, PFEV, PFMDU, PFMDV, PTSN, PXHROV, PDIFSV, PDIFTQ, PDIFTS, PSTRTU&
&, PSTRTV, PDIFTQL, PDIFTQI, PDIFCQ, PDIFCS, PSTRCU, PSTRCV, PSHEAR, YDSTACK)
!$acc routine (ACDIFV2_OPENACC) seq
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOM_YGFL,ONLY:TYPE_GFLD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

LOGICAL, INTENT (IN)::LDSFORCS
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFAQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFAS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFAU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFASV (KLON, KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (IN)::PCFBQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFBS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFBU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFBV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCFBSV (KLON, KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (IN)::PKTROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKQROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKQLROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKUROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PFEV (KLON)
REAL (KIND=JPRB), INTENT (IN)::PSFSV (KLON, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (IN)::PFMDU (KLON)
REAL (KIND=JPRB), INTENT (IN)::PFMDV (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PXHROV (KLON)
REAL (KIND=JPRB), INTENT (IN)::PALPHA1 (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCOEFA (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLVT (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQICE (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDSE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::POID (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFSV (KLON, 0:KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (OUT)::PDIFTQ (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFTS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRTU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRTV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFCQ (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFCS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRCU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRCV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFTQL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFTQI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSHEAR (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

temp (REAL (KIND=JPRB), ZEDMFV, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZEDMFU, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZEDMFS, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZEDMFQ, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZKSVRV, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZNSV1, (KLON, KLEV, 1:YGFL%NGFL_EXT))
temp (REAL (KIND=JPRB), ZN2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZN1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZKSRV, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZKQRV, (KLON, 0:KLEV))

temp (REAL (KIND=JPRB), ZSUB1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZIPOI, (KLON, KLEV))

INTEGER (KIND=JPIM)::JGFL
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV

REAL (KIND=JPRB)::ZEXNER
REAL (KIND=JPRB)::ZCPVMD

REAL (KIND=JPRB)::ZQICE
REAL (KIND=JPRB)::ZTH
REAL (KIND=JPRB)::ZQC
REAL (KIND=JPRB)::ZELIM
REAL (KIND=JPRB)::ZMUL
REAL (KIND=JPRB)::ZGDT

REAL (KIND=JPRB)::ZDIFTQC
REAL (KIND=JPRB)::ZDIFTQ
REAL (KIND=JPRB)::ZDIFTS

#include "fcttrm.func.h"
#include "fctdoi.func.h"

YLSTACK = YDSTACK

alloc (ZEDMFV)
alloc (ZEDMFU)
alloc (ZEDMFS)
alloc (ZEDMFQ)
alloc (ZKSVRV)
alloc (ZNSV1)
alloc (ZN2)
alloc (ZN1)
alloc (ZKSRV)
alloc (ZKQRV)
alloc (ZSUB1)
alloc (ZIPOI)



JLON = KIDIA


ZCPVMD=YDCST%RCPV-YDCST%RCPD
ZGDT=YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY

DO JLEV=KTDIA, KLEV
  
  ZN1 (JLON, JLEV)=PCFBU (JLON, JLEV)
  ZN2 (JLON, JLEV)=PCFBV (JLON, JLEV)
  
ENDDO


PSTRTU (JLON, KLEV)=PFMDU (JLON)
PSTRTV (JLON, KLEV)=PFMDV (JLON)


IF (YDML_PHY_MF%YRPHY%LCOEFKTKE) THEN
  
  PSHEAR (JLON, KLEV)=PSTRTU (JLON, KLEV)*ZN1 (JLON, KLEV)+PSTRTV (JLON, KLEV)*ZN2 (JLON, KLEV)
  
ENDIF


IF (YDML_PHY_MF%YRPHY%LEDMFI.AND.YDML_PHY_MF%YRPHY%LEDMFS) THEN
  
  ZEDMFU (JLON, KLEV)=PSTRTU (JLON, KLEV)
  ZEDMFV (JLON, KLEV)=PSTRTV (JLON, KLEV)
  
ENDIF


IF (YDML_PHY_MF%YRARPHY%LMSE.OR.LDSFORCS.OR.YDML_PHY_MF%YRPHY%LEDMFI) THEN
  
  ZN1 (JLON, KLEV)=ZN1 (JLON, KLEV)+PCFAU (JLON, KLEV)*PSTRTU (JLON, KLEV)
  ZN2 (JLON, KLEV)=ZN2 (JLON, KLEV)+PCFAU (JLON, KLEV)*PSTRTV (JLON, KLEV)
  
ENDIF


IF (YDML_PHY_MF%YRPHY%LEDMFI) THEN

  DO JLEV=KLEV-1, KTDIA,-1
    
    ZN1 (JLON, JLEV)=ZN1 (JLON, JLEV)+PCFAU (JLON, JLEV)*ZN1 (JLON, JLEV+1)
    ZN2 (JLON, JLEV)=ZN2 (JLON, JLEV)+PCFAU (JLON, JLEV)*ZN2 (JLON, JLEV+1)

    IF (YDML_PHY_MF%YRPHY%LEDMFS) THEN
      ZEDMFU (JLON, JLEV)=ZEDMFU (JLON, JLEV+1)+POID (JLON, JLEV+1)*(ZN1 (JLON, JLEV+1)-PU (JLON, JLEV+1))
      ZEDMFV (JLON, JLEV)=ZEDMFV (JLON, JLEV+1)+POID (JLON, JLEV+1)*(ZN2 (JLON, JLEV+1)-PV (JLON, JLEV+1))
      PSTRTU (JLON, JLEV)=PKUROV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
      PSTRTV (JLON, JLEV)=PKUROV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
      PSTRCU (JLON, JLEV)=ZEDMFU (JLON, JLEV)-PSTRTU (JLON, JLEV)
      PSTRCV (JLON, JLEV)=ZEDMFV (JLON, JLEV)-PSTRTV (JLON, JLEV)
    ELSE
      PSTRTU (JLON, JLEV)=PSTRTU (JLON, JLEV+1)+POID (JLON, JLEV+1)*(ZN1 (JLON, JLEV+1)-PU (JLON, JLEV+1))
      PSTRTV (JLON, JLEV)=PSTRTV (JLON, JLEV+1)+POID (JLON, JLEV+1)*(ZN2 (JLON, JLEV+1)-PV (JLON, JLEV+1))
    ENDIF

  
  ENDDO

ELSE

  DO JLEV=KLEV-1, KTDIA,-1
    
    ZN1 (JLON, JLEV)=ZN1 (JLON, JLEV)+PCFAU (JLON, JLEV)*ZN1 (JLON, JLEV+1)
    ZN2 (JLON, JLEV)=ZN2 (JLON, JLEV)+PCFAU (JLON, JLEV)*ZN2 (JLON, JLEV+1)
    PSTRTU (JLON, JLEV)=PKUROV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
    PSTRTV (JLON, JLEV)=PKUROV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))

    IF (YDML_PHY_MF%YRPHY%LCOEFKTKE) THEN
      PSHEAR (JLON, JLEV)=PSTRTU (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV&
      &+1))+PSTRTV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
    ENDIF

  
  ENDDO

ENDIF


PSTRTU (JLON, KTDIA-1)=0.0_JPRB
PSTRTV (JLON, KTDIA-1)=0.0_JPRB

IF (YDML_PHY_MF%YRPHY%LEDMFS) THEN
  PSTRCU (JLON, KTDIA-1)=0.0_JPRB
  PSTRCV (JLON, KTDIA-1)=0.0_JPRB
ENDIF



DO JLEV=KTDIA, KLEV-1
  
  ZKQRV (JLON, JLEV)=PKTROV (JLON, JLEV)
  ZKSRV (JLON, JLEV)=PKTROV (JLON, JLEV)
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZN1 (JLON, JLEV)=PCFBS (JLON, JLEV)
  ZN2 (JLON, JLEV)=PCFBQ (JLON, JLEV)
  
ENDDO


IF (YDML_PHY_MF%YRARPHY%LMSE.OR.LDSFORCS) THEN
  
  ZEXNER=(PAPRS (JLON, KLEV)/YDCST%RATM)**YDCST%RKAPPA
  PDIFTQ (JLON, KLEV)=PFEV (JLON)
  PDIFTS (JLON, KLEV)=PFCS (JLON)*ZEXNER+PFEV (JLON)*ZCPVMD*PTSN (JLON)
  
ENDIF


IF (YDML_PHY_MF%YRPHY%LEDMFI.AND.YDML_PHY_MF%YRPHY%LEDMFS) THEN
  
  ZEDMFQ (JLON, KLEV)=PDIFTQ (JLON, KLEV)
  ZEDMFS (JLON, KLEV)=PDIFTS (JLON, KLEV)
  
ENDIF


IF (YDML_PHY_MF%YRARPHY%LMSE.OR.LDSFORCS.OR.YDML_PHY_MF%YRPHY%LEDMFI) THEN
  
  ZN1 (JLON, KLEV)=ZN1 (JLON, KLEV)+PXHROV (JLON)*PCFAS (JLON, KLEV)*PDIFTS (JLON, KLEV)
  ZN2 (JLON, KLEV)=ZN2 (JLON, KLEV)+PXHROV (JLON)*PCFAQ (JLON, KLEV)*PDIFTQ (JLON, KLEV)

  

  IF (YDML_PHY_MF%YRPHY%LEDMFI) THEN

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZN1 (JLON, JLEV)=ZN1 (JLON, JLEV)+PCFAS (JLON, JLEV)*ZN1 (JLON, JLEV+1)
      ZN2 (JLON, JLEV)=ZN2 (JLON, JLEV)+PCFAQ (JLON, JLEV)*ZN2 (JLON, JLEV+1)

      IF (YDML_PHY_MF%YRPHY%LEDMFS) THEN
        ZEDMFQ (JLON, JLEV)=ZEDMFQ (JLON, JLEV+1)+POID (JLON&
        &, JLEV+1)*(ZN2 (JLON, JLEV+1)-PQT (JLON, JLEV+1))
        ZEDMFS (JLON, JLEV)=ZEDMFS (JLON, JLEV+1)+POID (JLON,&
        & JLEV+1)*(ZN1 (JLON, JLEV+1)-PDSE (JLON, JLEV+1))
        PDIFTQ (JLON, JLEV)=ZKQRV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
        PDIFTS (JLON, JLEV)=ZKSRV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
        PDIFCQ (JLON, JLEV)=ZEDMFQ (JLON, JLEV)-PDIFTQ (JLON, JLEV)
        PDIFCS (JLON, JLEV)=ZEDMFS (JLON, JLEV)-PDIFTS (JLON, JLEV)
      ELSE
        PDIFTQ (JLON, JLEV)=PDIFTQ (JLON, JLEV+1)+POID (JLON&
        &, JLEV+1)*(ZN2 (JLON, JLEV+1)-PQT (JLON, JLEV+1))
        PDIFTS (JLON, JLEV)=PDIFTS (JLON, JLEV+1)+POID (JLON,&
        & JLEV+1)*(ZN1 (JLON, JLEV+1)-PDSE (JLON, JLEV+1))
      ENDIF

    
    ENDDO

  ELSE

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZN1 (JLON, JLEV)=ZN1 (JLON, JLEV)+PCFAS (JLON, JLEV)*ZN1 (JLON, JLEV+1)
      ZN2 (JLON, JLEV)=ZN2 (JLON, JLEV)+PCFAQ (JLON, JLEV)*ZN2 (JLON, JLEV+1)
      PDIFTQ (JLON, JLEV)=ZKQRV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
      PDIFTS (JLON, JLEV)=ZKSRV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
    
    ENDDO

  ENDIF

  
  PDIFTQ (JLON, KTDIA-1)=0.0_JPRB
  PDIFTS (JLON, KTDIA-1)=0.0_JPRB

  IF (YDML_PHY_MF%YRPHY%LEDMFS) THEN
    PDIFCQ (JLON, KTDIA-1)=0.0_JPRB
    PDIFCS (JLON, KTDIA-1)=0.0_JPRB
  ENDIF


  

  IF ((YDML_PHY_MF%YRPHY%L3MT.OR.YDML_PHY_MF%YRPHY%LSTRAPRO.OR..NOT.YDML_PHY_MF%YRPHY%LNODIFQC&
    &).AND.YDML_PHY_MF%YRPHY%LDIFCONS.AND.(.NOT.YDML_PHY_MF%YRPHY%LCOEFKTKE)) THEN

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZDIFTS=ZKSRV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
      ZDIFTQ=ZKQRV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
      ZDIFTQC=PCOEFA (JLON, JLEV)*(ZDIFTQ-PALPHA1 (JLON, JLEV)*ZDIFTS)
      PDIFTS (JLON, JLEV)=ZDIFTS+ZDIFTQC*PLVT (JLON, JLEV)
      PDIFTQ (JLON, JLEV)=ZDIFTQ-ZDIFTQC
      PDIFTQL (JLON, JLEV)=ZDIFTQC*(1.0_JPRB-PQICE (JLON, JLEV))
      PDIFTQI (JLON, JLEV)=ZDIFTQC*PQICE (JLON, JLEV)
    
    ENDDO

  ENDIF


  IF (YDML_PHY_MF%YRARPHY%LMDUST.AND.(YGFL%NGFL_EXT/=0)) THEN

    DO JGFL=1, YGFL%NGFL_EXT

      DO JLEV=KTDIA, KLEV
        
        ZNSV1 (JLON, JLEV, JGFL)=PCFBSV (JLON, JLEV, JGFL)
      
      ENDDO


      DO JLEV=KTDIA, KLEV-1
        
        ZKSVRV (JLON, JLEV)=PKTROV (JLON, JLEV)
      
      ENDDO

      
      PDIFSV (JLON, KLEV, JGFL)=PSFSV (JLON, JGFL)
      ZNSV1 (JLON, KLEV, JGFL)=ZNSV1 (JLON, KLEV, JGFL)+PXHROV (JLON&
      &)*PCFASV (JLON, KLEV, JGFL)*PDIFSV (JLON, KLEV, JGFL)

      

      DO JLEV=KLEV-1, KTDIA,-1
        
        ZNSV1 (JLON, JLEV, JGFL)=ZNSV1 (JLON, JLEV, JGFL)+PCFASV&
        & (JLON, JLEV, JGFL)*ZNSV1 (JLON, JLEV+1, JGFL)
        PDIFSV (JLON, JLEV, JGFL)=ZKSVRV (JLON, JLEV)*(ZNSV1 (JLON, JLEV, JGFL)-ZNSV1 (JLON, JLEV+1, JGFL))
      
      ENDDO

      
      PDIFSV (JLON, KTDIA-1, JGFL)=0.0_JPRB
    
    ENDDO

  ENDIF

ELSE

  IF ((YDML_PHY_MF%YRPHY%L3MT.OR.YDML_PHY_MF%YRPHY%LSTRAPRO.OR..NOT.YDML_PHY_MF%YRPHY%LNODIFQC&
    &).AND.YDML_PHY_MF%YRPHY%LDIFCONS.AND.(.NOT.YDML_PHY_MF%YRPHY%LCOEFKTKE)) THEN

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZDIFTS=ZKSRV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
      ZDIFTQ=ZKQRV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
      ZDIFTQC=PCOEFA (JLON, JLEV)*(ZDIFTQ-PALPHA1 (JLON, JLEV)*ZDIFTS)
      PDIFTS (JLON, JLEV)=ZDIFTS+ZDIFTQC*PLVT (JLON, JLEV)
      PDIFTQ (JLON, JLEV)=ZDIFTQ-ZDIFTQC
      PDIFTQL (JLON, JLEV)=ZDIFTQC*(1.0_JPRB-PQICE (JLON, JLEV))
      PDIFTQI (JLON, JLEV)=ZDIFTQC*PQICE (JLON, JLEV)
    
    ENDDO

  ELSE

    DO JLEV=KLEV-1, KTDIA,-1
      
      PDIFTS (JLON, JLEV)=ZKSRV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
      PDIFTQ (JLON, JLEV)=ZKQRV (JLON, JLEV)*(ZN2 (JLON, JLEV)-ZN2 (JLON, JLEV+1))
      PDIFTQL (JLON, JLEV)=0.0_JPRB
      PDIFTQI (JLON, JLEV)=0.0_JPRB
    
    ENDDO

  ENDIF

  
  PDIFTQ (JLON, KTDIA-1)=0.0_JPRB
  PDIFTS (JLON, KTDIA-1)=0.0_JPRB
  PDIFTQL (JLON, KTDIA-1)=0.0_JPRB
  PDIFTQI (JLON, KTDIA-1)=0.0_JPRB
  
  
  PDIFTQL (JLON, KLEV)=0.0_JPRB
  PDIFTQI (JLON, KLEV)=0.0_JPRB
  
ENDIF


IF (YDML_PHY_MF%YRPHY%LDIFQL) THEN

  IF (YDML_PHY_MF%YRPHY%LDIFCEXP) THEN

    DO JLEV=KTDIA, KLEV
      
      ZIPOI (JLON, JLEV)=PRDELP (JLON, JLEV)*ZGDT
    
    ENDDO

    
    ZKQRV (JLON, KTDIA)=PKQLROV (JLON, KTDIA)
    ZMUL=1._JPRB/(1._JPRB+ZKQRV (JLON, KTDIA)*ZIPOI (JLON, KTDIA))
    ZSUB1 (JLON, KTDIA)=ZMUL*ZKQRV (JLON, KTDIA)*ZIPOI (JLON, KTDIA)
    ZQC=PQL (JLON, KTDIA)+PQI (JLON, KTDIA)
    ZN1 (JLON, KTDIA)=ZMUL*ZQC

    

    DO JLEV=KTDIA+1, KLEV-1
      
      ZKQRV (JLON, JLEV)=PKQLROV (JLON, JLEV)
      ZELIM=ZKQRV (JLON, JLEV-1)*ZIPOI (JLON, JLEV)
      ZMUL=1._JPRB/(1._JPRB+ZELIM*(1._JPRB-ZSUB1 (JLON, JLEV-1))+ZKQRV (JLON, JLEV)*ZIPOI (JLON, JLEV))
      ZSUB1 (JLON, JLEV)=ZMUL*ZKQRV (JLON, JLEV)*ZIPOI (JLON, JLEV)
      ZQC=PQL (JLON, JLEV)+PQI (JLON, JLEV)
      ZN1 (JLON, JLEV)=ZMUL*(ZQC+ZELIM*ZN1 (JLON, JLEV-1))
    
    ENDDO

    
    ZELIM=ZKQRV (JLON, KLEV-1)*ZIPOI (JLON, KLEV)
    ZMUL=1._JPRB/(1._JPRB+ZELIM*(1._JPRB-ZSUB1 (JLON, KLEV-1)))
    ZQC=PQL (JLON, KLEV)+PQI (JLON, KLEV)
    ZN1 (JLON, KLEV)=ZMUL*(ZQC+ZELIM*ZN1 (JLON, KLEV-1))

    

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZN1 (JLON, JLEV)=ZN1 (JLON, JLEV)+ZSUB1 (JLON, JLEV)*ZN1 (JLON, JLEV+1)
      PDIFTQL (JLON, JLEV)=PKQLROV (JLON, JLEV)*(ZN1 (JLON, JLEV)-ZN1 (JLON, JLEV+1))
    
    ENDDO


    DO JLEV=KTDIA, KLEV-1
      
      ZTH=(PT (JLON, JLEV)+PT (JLON, JLEV+1))*0.5_JPRB
      ZQICE=FONICE (ZTH, YDML_PHY_MF%YRPHY0%RDTFAC)
      PDIFTQI (JLON, JLEV)=ZQICE*PDIFTQL (JLON, JLEV)
      PDIFTQL (JLON, JLEV)=(1._JPRB-ZQICE)*PDIFTQL (JLON, JLEV)
    
    ENDDO

  ENDIF

ENDIF



ENDSUBROUTINE ACDIFV2_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
