
SUBROUTINE ACDIFV1_OPENACC (YDCST, YGFL, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPHIF, PAPRSF&
&, PCP, PDELP, PKTROV, PKQROV, PKUROV, PQ, PQL, PQI, PRDELP, PT, PU, PV, PSV, PXTROV, PXUROV, PXDROV&
&, PXHROV, PFS_UP, PFQT_UP, PFU_UP, PFV_UP, PMF_UP, PXURO, PXQRO, PXTRO, PCFAQ, PCFAS, PCFATH, PCFAU&
&, PCFASV, PCFBQ, PCFBS, PCFBTH, PCFBU, PCFBV, PCFBSV, PDSE, PQT, YDSTACK)
!$acc routine (ACDIFV1_OPENACC) seq
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOM_YGFL,ONLY:TYPE_GFLD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKTROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKQROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PKUROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PSV (KLON, KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (IN)::PFS_UP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFQT_UP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFU_UP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFV_UP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMF_UP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PXTROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PXUROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PXDROV (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PXHROV (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PXURO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PXQRO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PXTRO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFAQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFAS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFATH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFAU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFASV (KLON, KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (OUT)::PCFBQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFBS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFBTH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFBU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFBV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFBSV (KLON, KLEV, 1:YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (OUT)::PDSE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQT (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

temp (REAL (KIND=JPRB), ZRT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTL, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTHETA, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZPOID, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZIPOI, (KLON, KLEV))

INTEGER (KIND=JPIM)::JGFL
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV

REAL (KIND=JPRB)::ZGDTI
REAL (KIND=JPRB)::ZGDT

temp (REAL (KIND=JPRB), ZCE, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZBE, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZAE, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZCT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZBT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZAT, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZCU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZBU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZAU, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZF_UP, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZMF_UP, (KLON, 0:KLEV))

REAL (KIND=JPRB)::ZLS
REAL (KIND=JPRB)::ZLV

#include "tridifv1_openacc.intfb.h"
#include "fcttrm.func.h"

YLSTACK = YDSTACK

alloc (ZRT)
alloc (ZTL)
alloc (ZTHETA)
alloc (ZPOID)
alloc (ZIPOI)
alloc (ZCE)
alloc (ZBE)
alloc (ZAE)
alloc (ZCT)
alloc (ZBT)
alloc (ZAT)
alloc (ZCU)
alloc (ZBU)
alloc (ZAU)
alloc (ZF_UP)
alloc (ZMF_UP)



JLON = KIDIA


ZMF_UP (JLON,:)=0.0_JPRB
ZF_UP (JLON,:)=0.0_JPRB

IF (YDML_PHY_MF%YRPHY%LDIFCONS) THEN

  DO JLEV=KTDIA, KLEV
    
    ZLV=FOLH (PT (JLON, JLEV), 0.0_JPRB)
    ZLS=FOLH (PT (JLON, JLEV), 1.0_JPRB)
    PQT (JLON, JLEV)=PQ (JLON, JLEV)+PQL (JLON, JLEV)+PQI (JLON, JLEV)
    ZRT (JLON, JLEV)=PQT (JLON, JLEV)/(1._JPRB-PQT (JLON, JLEV))
    ZTL (JLON, JLEV)=PT (JLON, JLEV)-(ZLV*PQL (JLON, JLEV)+ZLS*PQI (JLON, JLEV))/PCP (JLON, JLEV)
  
  ENDDO

ELSE

  DO JLEV=KTDIA, KLEV
    
    PQT (JLON, JLEV)=PQ (JLON, JLEV)
    ZTL (JLON, JLEV)=PT (JLON, JLEV)
  
  ENDDO

ENDIF

ZGDT=YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
ZGDTI=1.0_JPRB/ZGDT

IF (YDML_PHY_MF%YRPHY2%LMULAF) THEN

  DO JLEV=KTDIA+1, KLEV-1
    
    PXTROV (JLON, JLEV)=MAX (PXTROV (JLON, JLEV), PXTROV (JLON, JLEV-1))
    PXUROV (JLON, JLEV)=MAX (PXUROV (JLON, JLEV), PXUROV (JLON, JLEV-1))
  
  ENDDO

  
  PXDROV (JLON)=MAX (PXDROV (JLON), PXUROV (JLON, KLEV-1))
  PXHROV (JLON)=MAX (PXHROV (JLON), PXTROV (JLON, KLEV-1))
  
ENDIF


DO JLEV=KTDIA, KLEV
  
  ZPOID (JLON, JLEV)=PDELP (JLON, JLEV)*ZGDTI
  ZIPOI (JLON, JLEV)=PRDELP (JLON, JLEV)*ZGDT
  PDSE (JLON, JLEV)=PCP (JLON, JLEV)*ZTL (JLON, JLEV)+PAPHIF (JLON, JLEV)
  ZTHETA (JLON, JLEV)=ZTL (JLON, JLEV)*(YDCST%RATM/PAPRSF (JLON, JLEV))**YDCST%RKAPPA
  
ENDDO


DO JLEV=KTDIA, KLEV-1
  
  PXURO (JLON, JLEV)=PKUROV (JLON, JLEV)*PXUROV (JLON, JLEV)
  
ENDDO


DO JLEV=KTDIA, KLEV-1
  
  PXTRO (JLON, JLEV)=PKTROV (JLON, JLEV)*PXTROV (JLON, JLEV)
  
ENDDO


IF (.NOT.YDML_PHY_MF%YRPHY%LDIFCEXP) THEN

  DO JLEV=KTDIA, KLEV-1
    
    PXQRO (JLON, JLEV)=PKTROV (JLON, JLEV)*PXTROV (JLON, JLEV)
  
  ENDDO

ELSEIF (YDML_PHY_MF%YRPHY%LDIFCEXP) THEN

  DO JLEV=KTDIA, KLEV-1
    
    PXQRO (JLON, JLEV)=PKQROV (JLON, JLEV)*PXTROV (JLON, JLEV)
  
  ENDDO

ENDIF


IF (YDML_PHY_MF%YRPHY%LEDMFI) THEN
  
  ZAE (JLON, KTDIA)=0._JPRB
  ZBE (JLON, KTDIA)=-PMF_UP (JLON, KTDIA)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, KTDIA)
  ZCE (JLON, KTDIA)=-PMF_UP (JLON, KTDIA)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, KTDIA)

  

  DO JLEV=KTDIA+1, KLEV-1
    
    ZAE (JLON, JLEV)=PMF_UP (JLON, JLEV-1)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, JLEV)
    ZBE (JLON, JLEV)=+PMF_UP (JLON, JLEV-1)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON&
    &, JLEV)-PMF_UP (JLON, JLEV)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, JLEV)
    ZCE (JLON, JLEV)=-PMF_UP (JLON, JLEV)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, JLEV)
  
  ENDDO

  
  ZAE (JLON, KLEV)=+PMF_UP (JLON, KLEV-1)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, KLEV)
  ZBE (JLON, KLEV)=+PMF_UP (JLON, KLEV-1)*0.5_JPRB*YDML_PHY_MF%YRPHY0%GCVIMPT*ZIPOI (JLON, KLEV)
  ZCE (JLON, KLEV)=0.0_JPRB
  
ELSE
  ZAE (JLON,:)=0._JPRB
  ZBE (JLON,:)=0._JPRB
  ZCE (JLON,:)=0._JPRB
ENDIF

ZAT (JLON,:)=0._JPRB
ZBT (JLON,:)=1._JPRB
ZCT (JLON,:)=0._JPRB

ZAT (JLON, KTDIA)=-PXTRO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)
ZBT (JLON, KTDIA)=1._JPRB+ZBE (JLON, KTDIA)+PXTRO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)
ZCT (JLON, KTDIA)=ZCE (JLON, KTDIA)-PXTRO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)


DO JLEV=KTDIA+1, KLEV-1
  
  ZAT (JLON, JLEV)=ZAE (JLON, JLEV)-ZIPOI (JLON, JLEV)*PXTRO (JLON, JLEV-1)
  ZBT (JLON, JLEV)=1._JPRB+ZBE (JLON, JLEV)+ZIPOI (JLON&
  &, JLEV)*(PXTRO (JLON, JLEV)+PXTRO (JLON, JLEV-1))
  ZCT (JLON, JLEV)=ZCE (JLON, JLEV)-ZIPOI (JLON, JLEV)*PXTRO (JLON, JLEV)
  
ENDDO


ZAT (JLON, KLEV)=ZAE (JLON, KLEV)-ZIPOI (JLON, KLEV)*PXTRO (JLON, KLEV-1)
ZBT (JLON, KLEV)=1._JPRB+ZBE (JLON, KLEV)+ZIPOI (JLON&
&, KLEV)*(PXTRO (JLON, KLEV)+PXTRO (JLON, KLEV-1))
ZCT (JLON, KLEV)=ZIPOI (JLON, KLEV)

ZAU (JLON,:)=0._JPRB
ZBU (JLON,:)=1._JPRB
ZCU (JLON,:)=0._JPRB

ZAU (JLON, KTDIA)=-PXURO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)
ZBU (JLON, KTDIA)=1._JPRB+ZBE (JLON, KTDIA)+PXURO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)
ZCU (JLON, KTDIA)=ZCE (JLON, KTDIA)-PXURO (JLON, KTDIA)*ZIPOI (JLON, KTDIA)


DO JLEV=KTDIA+1, KLEV-1
  
  ZAU (JLON, JLEV)=ZAE (JLON, JLEV)-ZIPOI (JLON, JLEV)*PXURO (JLON, JLEV-1)
  ZBU (JLON, JLEV)=1._JPRB+ZBE (JLON, JLEV)+ZIPOI (JLON&
  &, JLEV)*(PXURO (JLON, JLEV)+PXURO (JLON, JLEV-1))
  ZCU (JLON, JLEV)=ZCE (JLON, JLEV)-ZIPOI (JLON, JLEV)*PXURO (JLON, JLEV)
  
ENDDO


ZAU (JLON, KLEV)=ZAE (JLON, KLEV)-ZIPOI (JLON, KLEV)*PXURO (JLON, KLEV-1)
ZBU (JLON, KLEV)=1._JPRB+ZBE (JLON, KLEV)+ZIPOI (JLON&
&, KLEV)*(PXURO (JLON, KLEV)+PXURO (JLON, KLEV-1))
ZCU (JLON, KLEV)=ZIPOI (JLON, KLEV)

CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, ZAT, ZBT, ZCT, PFS_UP, PMF_UP, ZIPOI, PDSE, PCFAS, PCFBS, YDSTACK=YLSTACK)
CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, ZAT, ZBT, ZCT, PFQT_UP, PMF_UP, ZIPOI, PQT, PCFAQ, PCFBQ, YDSTACK=YLSTACK)
CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA,&
& KLEV, ZAT, ZBT, ZCT, ZF_UP, ZMF_UP, ZIPOI, ZTHETA, PCFATH, PCFBTH, YDSTACK=YLSTACK)

IF (YDML_PHY_MF%YRARPHY%LMDUST.AND.(YGFL%NGFL_EXT/=0)) THEN

  DO JGFL=1, YGFL%NGFL_EXT
    CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA&
    &, KLON, KTDIA, KLEV, ZAT, ZBT, ZCT, ZF_UP, ZMF_UP, ZIPOI, PSV (:,:, JGFL&
    &), PCFASV (:,:, JGFL), PCFBSV (:,:, JGFL), YDSTACK=YLSTACK)
  ENDDO

ENDIF

CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, ZAU, ZBU, ZCU, PFU_UP, PMF_UP, ZIPOI, PU, PCFAU, PCFBU, YDSTACK=YLSTACK)
CALL TRIDIFV1_OPENACC (YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, ZAU, ZBU, ZCU, PFV_UP, PMF_UP, ZIPOI, PV, PCFAU, PCFBV, YDSTACK=YLSTACK)


ENDSUBROUTINE ACDIFV1_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
