SUBROUTINE ACTKE_OPENACC (YDCST, YDLDDH, YDMDDH, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIAT&
&, KTDIAN, KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, PQICONV,&
& PQLCONV, PLSCPE, PCD, PCH, PGZ0, PTS, PQS, PQICE, PQLI, PECT, PPRODTH, PNLAB, PNLABCVP&
&, PKTROV, PKQROV, PKQLROV, PKUROV, PXTROV, PXUROV, PNBVNO, PNEBS, PQCS, PNEBS0, PQCS0&
&, PCOEFN, PFECT, PFECTI, PECT1, PTPRDY, PEDR, YDDDH, YDSTACK)
!$acc routine (ACTKE_OPENACC) seq
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE YOMMDDH,ONLY:TMDDH
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOMLSFORC,ONLY:LMUSCLFA, NMUSCLFA
USE YOMLDDH,ONLY:TLDDH
USE DDH_MIX,ONLY:ADD_FIELD_3D, TYP_DDH, NEW_ADD_FIELD_3D
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TLDDH), INTENT (IN)::YDLDDH
TYPE (TMDDH), INTENT (IN)::YDMDDH
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KTDIAT
INTEGER (KIND=JPIM), INTENT (IN)::KTDIAN
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PAPHI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQICONV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQLCONV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLSCPE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCD (KLON)
REAL (KIND=JPRB), INTENT (IN)::PCH (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGZ0 (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PQS (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PQICE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQLI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PECT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PPRODTH (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNLAB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNLABCVP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKTROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKQROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKQLROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKUROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PXTROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PXUROV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PNEBS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQCS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PNEBS0 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQCS0 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCOEFN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFECT (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFECTI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PECT1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTPRDY (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PEDR (KLON, KLEV)
TYPE (TYP_DDH), INTENT (INOUT)::YDDDH
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV

temp (REAL (KIND=JPRB), ZPHI3, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZLMECT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZUSLE, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZPRDY, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZPRODTH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDIAG, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZDISS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDIFF, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZECT1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZECT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDELPSG, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDET, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZECTCLS, (KLON))
temp (REAL (KIND=JPRB), ZKCLS, (KLON))

temp (REAL (KIND=JPRB), ZDIFFAR, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTABFL, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTABHL, (KLON, 0:KLEV))

temp (REAL (KIND=JPRB), ZFCORTKE, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZFDIFF, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZFDISS, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZFPRDY, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZFPRTH, (KLON, 0:KLEV))

temp (REAL (KIND=JPRB), ZEDR, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTCORTKE, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTDIFF, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTDISS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTPRTH, (KLON, KLEV))
REAL (KIND=JPRB)::ZEPSQ
temp (LOGICAL, LLCONV, (KLON, KLEV))

#include "acbl89_openacc.intfb.h"
#include "acturb_openacc.intfb.h"
#include "acevolet_openacc.intfb.h"
#include "hl2fl_openacc.intfb.h"
#include "fl2hl_openacc.intfb.h"
#include "wrscmr.intfb.h"
#include "aclender_openacc.intfb.h"

YLSTACK = YDSTACK

alloc (ZPHI3)
alloc (ZLMECT)
alloc (ZUSLE)
alloc (ZPRDY)
alloc (ZPRODTH)
alloc (ZDIAG)
alloc (ZDISS)
alloc (ZDIFF)
alloc (ZECT1)
alloc (ZECT)
alloc (ZDELPSG)
alloc (ZDET)
alloc (ZECTCLS)
alloc (ZKCLS)
alloc (ZDIFFAR)
alloc (ZTABFL)
alloc (ZTABHL)
alloc (ZFCORTKE)
alloc (ZFDIFF)
alloc (ZFDISS)
alloc (ZFPRDY)
alloc (ZFPRTH)
alloc (ZEDR)
alloc (ZTCORTKE)
alloc (ZTDIFF)
alloc (ZTDISS)
alloc (ZTPRTH)
alloc (LLCONV)



JLON = KIDIA


ZEPSQ=1.E-10_JPRB
ZTDIFF (JLON,:)=0.0_JPRB
PEDR (JLON,:)=0.0_JPRB
ZTDISS (JLON,:)=0.0_JPRB
ZTPRTH (JLON,:)=0.0_JPRB
PTPRDY (JLON,:)=0.0_JPRB
ZTCORTKE (JLON,:)=0.0_JPRB
ZFDIFF (JLON,:)=0.0_JPRB
ZFDISS (JLON,:)=0.0_JPRB
ZFPRTH (JLON,:)=0.0_JPRB
ZFPRDY (JLON,:)=0.0_JPRB
ZFCORTKE (JLON,:)=0.0_JPRB
ZDET (JLON,:)=0.0_JPRB
ZDELPSG (JLON,:)=0.0_JPRB
ZDIAG (JLON,:)=0.0_JPRB
ZDIFFAR (JLON,:)=0._JPRB

IF (YDML_PHY_MF%YRPHY%LECTFL) THEN
  CALL FL2HL_OPENACC (KIDIA, KFDIA, KLON, 1, KLEV, PAPRS, PAPRSF, PECT, ZECT, 1, YDSTACK=YLSTACK)
  
ELSE

  DO JLEV=1, KLEV
    
    ZECT (JLON, JLEV)=PECT (JLON, JLEV)
  
  ENDDO

ENDIF


DO JLEV=1, KLEV
  
  ZUSLE (JLON, JLEV)=0.0_JPRB
  ZLMECT (JLON, JLEV)=0.0_JPRB
  ZPHI3 (JLON, JLEV)=0.0_JPRB
  
ENDDO


ZECTCLS (JLON)=0.0_JPRB
ZKCLS (JLON)=0.0_JPRB


DO JLEV=KTDIAT, KLEV
  
  ZECT (JLON, JLEV)=MAX (YDML_PHY_MF%YRPHY0%ECTMIN, ZECT (JLON, JLEV))
  ZDELPSG (JLON, JLEV)=PDELP (JLON, JLEV)/YDCST%RG
  
ENDDO


IF (YDML_PHY_MF%YRPHY%NLEND==0) THEN
  CALL ACBL89_OPENACC (YDCST, YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA&
  &, KLON, KTDIAN, KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PT, ZECT, PQ, PQICE, PQLI&
  &, PNLAB, PNLABCVP, PGZ0, PTS, ZUSLE, ZLMECT, ZPHI3, YDSTACK=YLSTACK)
ELSEIF (YDML_PHY_MF%YRPHY%NLEND>0) THEN
  CALL ACLENDER_OPENACC (YDCST, YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA&
  &, KLON, KTDIAN, KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PT, PQ, PQICE, PQLI, PNLAB, PNLABCVP&
  &, PLSCPE, PU, PV, ZECT, PGZ0, ZUSLE, ZLMECT, ZPHI3, YDSTACK=YLSTACK)
ENDIF

CALL ACTURB_OPENACC (YDCST, YDML_PHY_MF%YRPHY, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON,&
& KTDIAT, KTDIAN, KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PR, PT, PU, PV, ZECT, PQ, LLCONV&
&, PLSCPE, ZLMECT, ZPHI3, PCD, PCH, PGZ0, PTS, PQS, PQICE, PQLI, PKTROV, PKQROV, PKQLROV&
&, PKUROV, PNBVNO, ZPRODTH, PNEBS, PQCS, PCOEFN, ZKCLS, ZECTCLS, YDSTACK=YLSTACK)
PNEBS0 (JLON,:)=PNEBS (JLON,:)
PQCS0 (JLON,:)=PQCS (JLON,:)
PXTROV (JLON,:)=1.0_JPRB
PXUROV (JLON,:)=1.0_JPRB

DO JLEV=KTDIAT, KLEV
  
  ZPRODTH (JLON, JLEV)=ZPRODTH (JLON, JLEV)+YDML_PHY_MF&
  &%YRPHY0%RPRTH*MAX (0._JPRB, PPRODTH (JLON, JLEV))
  
ENDDO

CALL ACEVOLET_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIAT, KTDIAN,&
& KLEV, PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, ZECT, PKUROV, PR, PT, PU, PV, ZUSLE&
&, ZPRODTH, ZKCLS, ZECTCLS, ZECT1, ZPRDY, ZDIFF, ZDISS, YDSTACK=YLSTACK)
PECT1 (JLON,:)=YDML_PHY_MF%YRPHY0%ECTMIN

DO JLEV=KTDIAT, KLEV
  
  ZEDR (JLON, JLEV)=MIN (100._JPRB, ZUSLE (JLON, JLEV)*YDCST%RG&
  &)*(0.5_JPRB*(ZECT1 (JLON, JLEV)+PECT (JLON, JLEV)))**1.5
  
ENDDO


IF (YDML_PHY_MF%YRPHY%LECTFL) THEN
  CALL HL2FL_OPENACC (KIDIA, KFDIA, KLON, 1, KLEV, PAPRS, PAPRSF, ZECT1, 1, PECT1, YDSTACK=YLSTACK)

  DO JLEV=KTDIAT, KLEV
    
    ZDET (JLON, JLEV)=(PECT1 (JLON, JLEV)-PECT (JLON, JLEV))/YDML_PHY_MF%YRPHY2%TSPHY
  
  ENDDO

  CALL HL2FL_OPENACC (KIDIA, KFDIA, KLON, 1, KLEV, PAPRS, PAPRSF, ZPRDY, 1, PTPRDY, YDSTACK=YLSTACK)
  CALL HL2FL_OPENACC (KIDIA, KFDIA, KLON, 1, KLEV, PAPRS, PAPRSF, ZEDR, 1, PEDR, YDSTACK=YLSTACK)
  
ELSE

  DO JLEV=KTDIAT, KLEV
    
    ZDET (JLON, JLEV)=(ZECT1 (JLON, JLEV)-PECT (JLON, JLEV))/YDML_PHY_MF%YRPHY2%TSPHY
    PECT1 (JLON, JLEV)=ZECT1 (JLON, JLEV)
    PTPRDY (JLON, JLEV)=ZPRDY (JLON, JLEV)
    PEDR (JLON, JLEV)=ZEDR (JLON, JLEV)
  
  ENDDO

  
ENDIF



DO JLEV=KTDIAT, KLEV
  
  PFECT (JLON, JLEV)=PFECT (JLON, JLEV-1)-ZDET (JLON, JLEV)*ZDELPSG (JLON, JLEV)
  PFECTI (JLON, JLEV)=ZDET (JLON, JLEV)
  
ENDDO



ENDSUBROUTINE ACTKE_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
