SUBROUTINE ACUPTQ_OPENACC (YDCST, KLON, KIDIA, KFDIA, KFLEV, LDPTQ, PFRSO, PFRTH&
&, PDIFCQ, PDIFCS, PDIFTQ, PDIFTS, PFCCQL, PFCCQN, PFPLCL, PFPLCN, PFECL, PFECN&
&, PFACL, PFACN, PRDELP, PT, PQ, PTS, PTENDH, PTENDQ, YDSTACK)
!$acc routine (ACUPTQ_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
LOGICAL, INTENT (IN)::LDPTQ
REAL (KIND=JPRB), INTENT (IN)::PFRSO (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFRTH (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQ (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCS (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQ (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTS (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQL (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQN (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLCL (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLCN (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECL (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECN (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACL (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACN (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQ (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTENDH (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQ (KLON, KFLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
temp (REAL (KIND=JPRB), ZGSDP, (KLON, KFLEV))
temp (REAL (KIND=JPRB), ZJTOT, (KLON, 0:KFLEV))
temp (REAL (KIND=JPRB), ZTI, (KLON, 0:KFLEV))

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV


YLSTACK = YDSTACK

alloc (ZGSDP)
alloc (ZJTOT)
alloc (ZTI)



JLON = KIDIA



ZTI (JLON, 0)=PT (JLON, 1)
ZTI (JLON, KFLEV)=PTS (JLON)


DO JLEV=1, KFLEV-1
  
  ZTI (JLON, JLEV)=(PT (JLON, JLEV)+PT (JLON, JLEV+1))*0.5_JPRB
  
ENDDO


DO JLEV=0, KFLEV

  

  IF (LDPTQ) THEN
    ZJTOT (JLON, JLEV)=PFRSO (JLON, JLEV)+PFRTH (JLON, JLEV)+PDIFTS (JLON, JLEV)+PDIFCS&
    & (JLON, JLEV)+(YDCST%RCW-YDCST%RCPD)*PFPLCL (JLON, JLEV)*ZTI (JLON, JLEV)+(YDCST%RCS&
    &-YDCST%RCPD)*PFPLCN (JLON, JLEV)*ZTI (JLON, JLEV)-YDCST%RLVZER*(PFCCQL (JLON, JLEV&
    &)-PFECL (JLON, JLEV))-YDCST%RLSZER*(PFCCQN (JLON, JLEV)-PFECN (JLON, JLEV))
  ELSE
    ZJTOT (JLON, JLEV)=PFRSO (JLON, JLEV)+PFRTH (JLON, JLEV)+PDIFTS (JLON, JLEV)
  ENDIF

  
ENDDO


DO JLEV=1, KFLEV
  
  ZGSDP (JLON, JLEV)=YDCST%RG*PRDELP (JLON, JLEV)

  IF (LDPTQ) THEN
    PTENDQ (JLON, JLEV)=ZGSDP (JLON, JLEV)*((PDIFTQ (JLON, JLEV-1)-PDIFTQ (JLON, JLEV))+(PDIFCQ (JLON, JLEV&
    &-1)-PDIFCQ (JLON, JLEV))+(PFCCQL (JLON, JLEV-1)-PFCCQL (JLON, JLEV))+(PFCCQN (JLON, JLEV-1)-PFCCQN (JLON&
    &, JLEV))-(PFECL (JLON, JLEV-1)-PFECL (JLON, JLEV))-(PFECN (JLON, JLEV-1)-PFECN (JLON, JLEV)))
    PTENDH (JLON, JLEV)=ZGSDP (JLON, JLEV)*(ZJTOT (JLON, JLEV-1)-ZJTOT (JLON, JLEV))
  ELSE
    PTENDQ (JLON, JLEV)=MAX (0._JPRB, ZGSDP (JLON, JLEV)*(PDIFTQ (JLON, JLEV-1)-PDIFTQ (JLON, JLEV)))
    PTENDH (JLON, JLEV)=MAX (0._JPRB, ZGSDP (JLON, JLEV)*(ZJTOT (JLON, JLEV-1)-ZJTOT (JLON, JLEV)))
  ENDIF

  
ENDDO



ENDSUBROUTINE ACUPTQ_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
