SUBROUTINE DPRECIPS_OPENACC (YDCST, YDPRECIPS, KIDIA, KFDIA, KLON, KLEV, POROG, PCLSTPW&
&, PDIAGH, PAPHIFM, PDZZ, PTPW, PQCM, PFPLSL, PFPLSN, PFPLSG, PDPRECIPS, YDSTACK)
!$acc routine (DPRECIPS_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMDPRECIPS,ONLY:TDPRECIPS
USE YOMCST,ONLY:TCST
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TDPRECIPS), INTENT (IN), TARGET::YDPRECIPS
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::POROG (KLON)
REAL (KIND=JPRB), INTENT (IN)::PCLSTPW (KLON)
REAL (KIND=JPRB), INTENT (IN)::PDIAGH (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAPHIFM (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDZZ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTPW (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQCM (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLSL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PFPLSN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PFPLSG (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PDPRECIPS (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::JLEVB
INTEGER (KIND=JPIM)::JLEVH
INTEGER (KIND=JPIM)::JL
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON

INTEGER (KIND=JPIM)::I2 
INTEGER (KIND=JPIM)::I1 
INTEGER (KIND=JPIM)::JJLEVM1 
INTEGER (KIND=JPIM)::JLEVM1 
INTEGER (KIND=JPIM)::ITOP 

REAL (KIND=JPRB)::ZINVG
REAL (KIND=JPRB)::ZALPHA
REAL (KIND=JPRB)::ZZ

REAL (KIND=JPRB)::ZPROFNEG 
REAL (KIND=JPRB)::ZLIQ 
REAL (KIND=JPRB)::ZRATIO 

temp (REAL (KIND=JPRB), ZHF, (KLON, KLEV))
REAL (KIND=JPRB)::ZHEIGHT 
REAL (KIND=JPRB)::ZTOT 
REAL (KIND=JPRB)::ZICE 

REAL (KIND=JPRB)::ZDCLWC 
REAL (KIND=JPRB)::ZANEG 
REAL (KIND=JPRB)::ZAPOS 


YLSTACK = YDSTACK

alloc (ZHF)



JLON = KIDIA


ZINVG=1._JPRB/YDCST%RG

ZLIQ =MAX (PFPLSL (JLON), 0._JPRB)
ZICE =MAX (PFPLSN (JLON), 0._JPRB)+MAX (PFPLSG (JLON), 0._JPRB)
ZTOT =ZLIQ +ZICE 
ZTOT =MAX (ZTOT , 1.E-8_JPRB)
ZRATIO =ZLIQ /ZTOT 
ZHEIGHT =POROG (JLON)*ZINVG

ITOP =1._JPIM

DO JLEV=KLEV, 1,-1
  
  ZHF (JLON, JLEV)=PAPHIFM (JLON, JLEV)*ZINVG
  ITOP =MAX (ITOP , JLEV*INT (MAX (0._JPRB, SIGN (1._JPRB&
  &, ZHF (JLON, JLEV)-YDPRECIPS%RHTOP-ZHEIGHT ))))
  
ENDDO

I1 =1._JPIM


DO JLEV=KLEV, ITOP ,-1
  I1 =MAX (I1 , JLEV*INT (MAX (0._JPRB, SIGN (1._JPRB, PTPW (JLON, JLEV)-YDCST%RTT))))
ENDDO


I2 =1._JPIM


DO JLEV=I1 , ITOP ,-1
  I2 =MAX (I2 , JLEV*INT (MAX (0._JPRB, SIGN (1._JPRB, YDCST%RTT-PTPW (JLON, JLEV)))))
ENDDO


ZPROFNEG =0._JPRB
ZANEG =0._JPRB
ZAPOS =0._JPRB


DO JLEV=KLEV, ITOP ,-1
  ZPROFNEG =ZPROFNEG +MAX (0._JPRB, SIGN (1._JPRB, PTPW (JLON, JLEV)-YDCST%RTT))
ENDDO




DO JLEV=KLEV, MIN (I1 +1, KLEV),-1
  ZANEG =ZANEG +PDZZ (JLON, JLEV)*(YDCST%RTT-PTPW (JLON, JLEV))
ENDDO




DO JLEV=I1 , MIN (I2 +1, I1 ),-1
  ZAPOS =ZAPOS +PDZZ (JLON, JLEV)*(PTPW (JLON, JLEV)-YDCST%RTT)
ENDDO


JLEVM1 =0

DO JLEV=KLEV, 1,-1
  
  ZZ=ZHF (JLON, JLEV)-YDPRECIPS%HDCLWC-ZHEIGHT 
  JJLEVM1 =MAX (0._JPRB, SIGN (1._JPRB, ZZ))*JLEV
  JLEVM1 =MAX (JJLEVM1 , JLEVM1 )
  
ENDDO


JLEVH=JLEVM1 
JLEVB=MIN (JLEVM1 +1, KLEV)

IF (JLEVH==JLEVB) THEN
  ZDCLWC =PQCM (JLON, JLEV)
ELSE
  ZALPHA=(ZHF (JLON, JLEVH)-YDPRECIPS%HDCLWC-ZHEIGHT )/(ZHF (JLON, JLEVH)-ZHF (JLON, JLEVB))
  ZDCLWC =PQCM (JLON, JLEVB)*ZALPHA+PQCM (JLON, JLEVH)*(1-ZALPHA)
ENDIF




IF (ZTOT >=YDPRECIPS%RPRECSEUIL) THEN

  IF (PDIAGH (JLON)>=YDPRECIPS%RDHAIL1) THEN

    IF (PDIAGH (JLON)>=YDPRECIPS%RDHAIL2) THEN
      PDPRECIPS (JLON)=10._JPRB
    ELSE
      PDPRECIPS (JLON)=9._JPRB
    ENDIF

  ELSEIF (PCLSTPW (JLON)<YDPRECIPS%RTPW) THEN

    IF (ZPROFNEG ==0._JPRB) THEN

      IF (ZDCLWC >YDPRECIPS%RDCLWC) THEN
        PDPRECIPS (JLON)=12._JPRB
      ELSEIF (PCLSTPW (JLON)<=YDPRECIPS%RTPW-2) THEN
        PDPRECIPS (JLON)=5._JPRB
      ELSE
        PDPRECIPS (JLON)=6._JPRB
      ENDIF

    ELSEIF (ZAPOS >=YDPRECIPS%RAWARM) THEN

      IF (ZANEG <YDPRECIPS%RACOLD) THEN
        PDPRECIPS (JLON)=3._JPRB
      ELSE
        PDPRECIPS (JLON)=8._JPRB
      ENDIF

    ELSE
      PDPRECIPS (JLON)=7._JPRB
    ENDIF

  ELSEIF (ZRATIO >YDPRECIPS%RDSEUIL4) THEN

    IF (ZLIQ >YDPRECIPS%RDSEUIL5) THEN
      PDPRECIPS (JLON)=1._JPRB
    ELSE
      PDPRECIPS (JLON)=11._JPRB
    ENDIF

  ELSEIF (ZRATIO >YDPRECIPS%RDSEUIL3) THEN
    PDPRECIPS (JLON)=7._JPRB
  ELSEIF (ZRATIO >YDPRECIPS%RDSEUIL2) THEN
    PDPRECIPS (JLON)=193._JPRB
  ELSEIF (ZRATIO >YDPRECIPS%RDSEUIL1) THEN
    PDPRECIPS (JLON)=6._JPRB
  ELSE
    PDPRECIPS (JLON)=5._JPRB
  ENDIF

ELSE
  PDPRECIPS (JLON)=0._JPRB
ENDIF




ENDSUBROUTINE DPRECIPS_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
