SUBROUTINE HL2FL_OPENACC (KIDIA, KFDIA, KLON, KTDIAT&
&, KLEV, PAPRS, PAPRSF, PXHL, KINI, PXFL, YDSTACK)
!$acc routine (HL2FL_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KTDIAT
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PXHL (KLON, KINI:KLEV)
INTEGER (KIND=JPIM), INTENT (IN)::KINI
REAL (KIND=JPRB), INTENT (OUT)::PXFL (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV


YLSTACK = YDSTACK




JLON = KIDIA


IF (KINI==1) THEN

  DO JLEV=KTDIAT+1, KLEV
    
    PXFL (JLON, JLEV)=((PXHL (JLON, JLEV)-PXHL (JLON, JLEV-1))*PAPRSF (JLON, JLEV)+PXHL (JLON, JLEV-1)*PAPRS&
    & (JLON, JLEV)-PXHL (JLON, JLEV)*PAPRS (JLON, JLEV-1))/(PAPRS (JLON, JLEV)-PAPRS (JLON, JLEV-1))
  
  ENDDO

  
  PXFL (JLON, KTDIAT)=PXFL (JLON, KTDIAT+1)
  
ELSE

  DO JLEV=KTDIAT, KLEV
    
    PXFL (JLON, JLEV)=((PXHL (JLON, JLEV)-PXHL (JLON, JLEV-1))*PAPRSF (JLON, JLEV)+PXHL (JLON, JLEV-1)*PAPRS&
    & (JLON, JLEV)-PXHL (JLON, JLEV)*PAPRS (JLON, JLEV-1))/(PAPRS (JLON, JLEV)-PAPRS (JLON, JLEV-1))
  
  ENDDO

ENDIF


ENDSUBROUTINE HL2FL_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
