SUBROUTINE MF_PHYS_BAYRAD_OPENACC (YDCPG_BNDS, YDCPG_OPTS, PBAY_QRCONV&
&, PBAY_QSCONV, PRCONV_T1, PSCONV_T1, YDMODEL, YDSTACK)
!$acc routine (MF_PHYS_BAYRAD_OPENACC) seq

USE PARKIND1,ONLY:JPIM, JPRB
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE TYPE_MODEL,ONLY:MODEL
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
REAL (KIND=JPRB), INTENT (IN)::PBAY_QRCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PBAY_QSCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PRCONV_T1 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSCONV_T1 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM) :: JLON

YLSTACK = YDSTACK




JLON = YDCPG_BNDS%KIDIA


IF ((.NOT.YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT).AND.(.NOT.YDCPG_OPTS%LAROME)) THEN

  IF (YDMODEL%YRML_GCONF%YGFL%YRCONV%LACTIVE) THEN
    PRCONV_T1 (JLON,:)=PBAY_QRCONV (JLON,:)
  ENDIF


  IF (YDMODEL%YRML_GCONF%YGFL%YSCONV%LACTIVE) THEN
    PSCONV_T1 (JLON,:)=PBAY_QSCONV (JLON,:)
  ENDIF

ENDIF


ENDSUBROUTINE MF_PHYS_BAYRAD_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
