SUBROUTINE QNGCOR_OPENACC (YDCST, YDPHY2, KIDIA, KFDIA, KLON, KTDIA, KLEV, PQ, PQL, PQI&
&, PRDELP, PDIFCQ, PDIFCQI, PDIFCQL, PDIFTQ, PDIFTQI, PDIFTQL, PFESL, PFESN, PFECL, PFECN&
&, PFASL, PFASN, PFACL, PFACN, PFCCQL, PFCCQN, PFCSQL, PFCSQN, PFCQNG, YDSTACK)
!$acc routine (QNGCOR_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMPHY2,ONLY:TPHY2
USE YOMCST,ONLY:TCST
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TPHY2), INTENT (IN)::YDPHY2
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQ (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQ (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFESL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFESN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFASL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFASN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PFCSQL (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PFCSQN (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PFCQNG (KLON, 0:KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

temp (REAL (KIND=JPRB), ZFCQNG, (KLON, 0:KLEV))
temp (REAL (KIND=JPRB), ZGSDPDT, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZQI, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQL, (KLON, KLEV))

REAL (KIND=JPRB)::ZQICORP 
REAL (KIND=JPRB)::ZQLCORP 

REAL (KIND=JPRB)::ZQCORP
REAL (KIND=JPRB)::ZQ

INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON


YLSTACK = YDSTACK

alloc (ZFCQNG)
alloc (ZGSDPDT)
alloc (ZQI)
alloc (ZQL)



JLON = KIDIA



ZQLCORP =0.0_JPRB
ZQICORP =0.0_JPRB


DO JLEV=0, KLEV
  
  ZFCQNG (JLON, JLEV)=0.0_JPRB
  
ENDDO


DO JLEV=1, KLEV
  
  ZGSDPDT (JLON, JLEV)=YDCST%RG*PRDELP (JLON, JLEV)*YDPHY2%TSPHY
  
ENDDO


DO JLEV=1, KLEV
  
  ZQL (JLON, JLEV)=PQL (JLON, JLEV)+ZGSDPDT (JLON, JLEV)*((PDIFTQL (JLON, JLEV-1)-PDIFTQL&
  & (JLON, JLEV))+(PDIFCQL (JLON, JLEV-1)-PDIFCQL (JLON, JLEV))+(PFACL (JLON, JLEV-1&
  &)-PFACL (JLON, JLEV))+(PFASL (JLON, JLEV-1)-PFASL (JLON, JLEV))-(PFCSQL (JLON, JLEV&
  &-1)-PFCSQL (JLON, JLEV))-(PFCCQL (JLON, JLEV-1)-PFCCQL (JLON, JLEV)))
  ZQI (JLON, JLEV)=PQI (JLON, JLEV)+ZGSDPDT (JLON, JLEV)*((PDIFTQI (JLON, JLEV-1)-PDIFTQI&
  & (JLON, JLEV))+(PDIFCQI (JLON, JLEV-1)-PDIFCQI (JLON, JLEV))+(PFACN (JLON, JLEV-1&
  &)-PFACN (JLON, JLEV))+(PFASN (JLON, JLEV-1)-PFASN (JLON, JLEV))-(PFCSQN (JLON, JLEV&
  &-1)-PFCSQN (JLON, JLEV))-(PFCCQN (JLON, JLEV-1)-PFCCQN (JLON, JLEV)))
  
ENDDO


DO JLEV=1, KTDIA-1
  
  ZQLCORP =ZQLCORP -ZQL (JLON, JLEV)/ZGSDPDT (JLON, JLEV)
  ZQICORP =ZQICORP -ZQI (JLON, JLEV)/ZGSDPDT (JLON, JLEV)
  PFCSQL (JLON, JLEV)=PFCSQL (JLON, JLEV)+ZQLCORP 
  PFCSQN (JLON, JLEV)=PFCSQN (JLON, JLEV)+ZQICORP 
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZQLCORP =ZQLCORP -MIN (0.0_JPRB, ZQL (JLON, JLEV))/ZGSDPDT (JLON, JLEV)
  ZQICORP =ZQICORP -MIN (0.0_JPRB, ZQI (JLON, JLEV))/ZGSDPDT (JLON, JLEV)
  PFCSQL (JLON, JLEV)=PFCSQL (JLON, JLEV)+ZQLCORP 
  PFCSQN (JLON, JLEV)=PFCSQN (JLON, JLEV)+ZQICORP 
  
ENDDO


DO JLEV=1, KLEV
  
  ZQ=PQ (JLON, JLEV)+ZGSDPDT (JLON, JLEV)*((PDIFTQ (JLON, JLEV-1)-PDIFTQ (JLON, JLEV))+(PDIFCQ (JLON&
  &, JLEV-1)-PDIFCQ (JLON, JLEV))+(PFCCQL (JLON, JLEV-1)-PFCCQL (JLON, JLEV))+(PFCCQN (JLON, JLEV-1&
  &)-PFCCQN (JLON, JLEV))+(PFCSQL (JLON, JLEV-1)-PFCSQL (JLON, JLEV))+(PFCSQN (JLON, JLEV-1)-PFCSQN&
  & (JLON, JLEV))-(PFECL (JLON, JLEV-1)-PFECL (JLON, JLEV))-(PFESL (JLON, JLEV-1)-PFESL (JLON, JLEV&
  &))-(PFECN (JLON, JLEV-1)-PFECN (JLON, JLEV))-(PFESN (JLON, JLEV-1)-PFESN (JLON, JLEV)))
  ZQCORP=ZQ+ZFCQNG (JLON, JLEV-1)*ZGSDPDT (JLON, JLEV)
  ZFCQNG (JLON, JLEV)=MIN (0.0_JPRB, ZQCORP)/ZGSDPDT (JLON, JLEV)
  
ENDDO


DO JLEV=0, KLEV
  
  PFCQNG (JLON, JLEV)=PFCQNG (JLON, JLEV)+ZFCQNG (JLON, JLEV)
  
ENDDO



ENDSUBROUTINE QNGCOR_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
