
SUBROUTINE SUOZON_OPENACC (KIDIA, KFDIA, KLON, KLEV, PROFO3, LDQINT&
&, PRESI, PRDELP, LD_LO3ABC, PVO3A, PVO3B, PVO3C, YDSTACK)
!$acc routine (SUOZON_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (OUT)::PROFO3 (KLON, 0:KLEV)
LOGICAL, INTENT (IN)::LDQINT
REAL (KIND=JPRB), INTENT (IN)::PRESI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
LOGICAL, INTENT (IN)::LD_LO3ABC
REAL (KIND=JPRB), INTENT (IN)::PVO3A (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVO3B (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVO3C (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV

REAL (KIND=JPRB)::ZQO32
REAL (KIND=JPRB)::ZQO31
REAL (KIND=JPRB)::ZQO3C
REAL (KIND=JPRB)::ZQO3B
REAL (KIND=JPRB)::ZQO3A
REAL (KIND=JPRB)::ZP
REAL (KIND=JPRB)::ZEPSO


YLSTACK = YDSTACK




JLON = KIDIA

ZEPSO=1.E-03_JPRB
ZQO31=0.6012E-01_JPRB
ZQO32=0.3166E+04_JPRB
ZQO32=SQRT (ZQO32*ZQO32*ZQO32)

DO JLEV=0, KLEV

  IF (LD_LO3ABC) THEN
    
    ZQO3A=PVO3A (JLON)
    ZQO3B=PVO3B (JLON)
    ZQO3C=PVO3C (JLON)/2._JPRB
    ZP=MAX (ZEPSO, PRESI (JLON, JLEV))
    PROFO3 (JLON, JLEV)=(2.0_JPRB*ZQO3A)/(1.0_JPRB+EXP (ZQO3C*LOG (ZQO3B/ZP)))
  
  ELSE
    
    ZP=MAX (ZEPSO, PRESI (JLON, JLEV))
    PROFO3 (JLON, JLEV)=(2.0_JPRB*ZQO31)/(1.0_JPRB+ZQO32/SQRT (ZP*ZP*ZP))
  
  ENDIF

ENDDO


IF (.NOT.LDQINT) THEN

  DO JLEV=KLEV, 1,-1
    
    PROFO3 (JLON, JLEV)=(PROFO3 (JLON, JLEV)-PROFO3 (JLON, JLEV-1))*PRDELP (JLON, JLEV)*0.5_JPRB
  
  ENDDO

  
  PROFO3 (JLON, 0)=PROFO3 (JLON, 0)/MAX (ZEPSO, PRESI (JLON, 0))*0.5_JPRB
  
ENDIF


ENDSUBROUTINE SUOZON_OPENACC

! 56ad6923076b622f9a4a36289517d0f4b37156a2
