SUBROUTINE GPTF2_EXPL_2TL_OPENACC (YDGEOMETRY, KST, KEND, LDFSTEP, P0U, P0V, P9U, P9V, YDSTACK)
  
  !**** *GPTF2_EXPL_2TL*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-11-2022
  
!$acc routine( GPTF2_EXPL_2TL_OPENACC ) seq
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: DR_HOOK, LHOOK, JPHOOK
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  INTEGER(KIND=JPIM), INTENT(IN) :: KST
  INTEGER(KIND=JPIM), INTENT(IN) :: KEND
  LOGICAL, INTENT(IN) :: LDFSTEP
  REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: P0U(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: P0V(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: P9U(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: P9V(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
  
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JROF
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KST
  YLSTACK = YDSTACK
  
  
  IF (LDFSTEP) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      P9U(JLON, JLEV) = P0U(JLON, JLEV)
      P9V(JLON, JLEV) = P0V(JLON, JLEV)
    END DO
  END IF
  
  
END SUBROUTINE GPTF2_EXPL_2TL_OPENACC
