INTERFACE
  SUBROUTINE GPRT_OPENACC (LDSPRT, KPROMA, KST, KEND, KLEV, PRD, PRV, PR, PT, PTL, PTM, PQL, PQM, PRT, PRTL, PRTM, PRL, PRM,  &
  & YDSTACK)
!$acc routine( GPRT_OPENACC )
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    !----------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    LOGICAL, INTENT(IN) :: LDSPRT
    INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
    INTEGER(KIND=JPIM), INTENT(IN) :: KST
    INTEGER(KIND=JPIM), INTENT(IN) :: KEND
    INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
    REAL(KIND=JPRB), INTENT(IN) :: PRD
    REAL(KIND=JPRB), INTENT(IN) :: PRV
    REAL(KIND=JPRB), INTENT(IN) :: PR(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PT(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PTL(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PTM(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PQL(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PQM(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PRT(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PRTL(KPROMA, KLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PRTM(KPROMA, KLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PRL(KPROMA, KLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PRM(KPROMA, KLEV)
    
    !----------------------------------------------------------
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE GPRT_OPENACC
END INTERFACE
