INTERFACE
  SUBROUTINE GPGRXYB_EXPL_OPENACC (YDCVER, KPROMA, KST, KEND, KFLEV, LDCOEF, YDVAB, PREL, PREM, PDELP, PLNPR, PRDELP, PALPH,  &
  & PRTGR, PRPRE, PRPP, PCOEFD_DER, PLNPRL_DER, PLNPRM_DER, PCOEFA_DER, PCOEFAPL_DER, PALPHPLL_DER, PALPHPLM_DER, PALPHL_DER,  &
  & PALPHM_DER, YDSTACK)
!$acc routine( GPGRXYB_EXPL_OPENACC ) seq
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, JPHOOK, DR_HOOK
    USE YOMCVER, ONLY: TCVER
    USE YOMVERT, ONLY: TVAB
    
    
    
    
    !     ------------------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(TCVER), INTENT(IN) :: YDCVER
    INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
    INTEGER(KIND=JPIM), INTENT(IN) :: KST
    INTEGER(KIND=JPIM), INTENT(IN) :: KEND
    INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
    LOGICAL, INTENT(IN) :: LDCOEF
    TYPE(TVAB), INTENT(IN) :: YDVAB
    REAL(KIND=JPRB), INTENT(IN) :: PREL(KPROMA)
    REAL(KIND=JPRB), INTENT(IN) :: PREM(KPROMA)
    REAL(KIND=JPRB), INTENT(IN) :: PDELP(KPROMA, KFLEV), PLNPR(KPROMA, KFLEV), PRDELP(KPROMA, KFLEV), PALPH(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PRTGR(KPROMA, KFLEV), PRPRE(KPROMA, KFLEV), PRPP(KPROMA, KFLEV)
    REAL(KIND=JPRB), TARGET, INTENT(OUT) :: PCOEFD_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PLNPRL_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PLNPRM_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), TARGET, INTENT(OUT) :: PCOEFA_DER(KPROMA, KFLEV), PCOEFAPL_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PALPHPLL_DER(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PALPHPLM_DER(KPROMA, KFLEV), PALPHL_DER(KPROMA, KFLEV), PALPHM_DER(KPROMA, KFLEV)
    
    !     ------------------------------------------------------------------
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE GPGRXYB_EXPL_OPENACC
END INTERFACE
