INTERFACE
  SUBROUTINE GPHLWI_OPENACC (YDDIMV, KPROMA, KST, KEND, PLNPR, PALPH, PWW, LDVERINT, YDSTACK)
!$acc routine( GPHLWI_OPENACC ) seq
    
    USE YOMDIMV, ONLY: TDIMV
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    !     ------------------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(TDIMV), INTENT(IN) :: YDDIMV
    INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
    INTEGER(KIND=JPIM), INTENT(IN) :: KST
    INTEGER(KIND=JPIM), INTENT(IN) :: KEND
    REAL(KIND=JPRB), INTENT(IN) :: PLNPR(KPROMA, YDDIMV%NFLEVG)
    REAL(KIND=JPRB), INTENT(IN) :: PALPH(KPROMA, YDDIMV%NFLEVG)
    REAL(KIND=JPRB), INTENT(OUT) :: PWW(KPROMA, YDDIMV%NFLEVG)
    LOGICAL, OPTIONAL, INTENT(IN) :: LDVERINT
    !     ------------------------------------------------------------------
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE GPHLWI_OPENACC
END INTERFACE
