INTERFACE
  SUBROUTINE GPXX_OPENACC (YDGEOMETRY, KFLEV, KPROMA, KST, KEND, PHIHL, PHIHM, PHIFL, PHIFM, PLNPR, PRT, PUF, PVF, PUH, PVH, PX,  &
  & PNHPPI, LDVFE, YDSTACK)
!$acc routine( GPXX_OPENACC ) seq
    
    USE PARKIND1, ONLY: JPIM, JPRB, JPRD
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    USE GEOMETRY_MOD, ONLY: GEOMETRY
    
    
    
    ! -----------------------------------------------------------------------------
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
    INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
    INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
    INTEGER(KIND=JPIM), INTENT(IN) :: KST
    INTEGER(KIND=JPIM), INTENT(IN) :: KEND
    REAL(KIND=JPRB), INTENT(IN) :: PHIHL(KPROMA, 0:KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PHIHM(KPROMA, 0:KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PHIFL(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PHIFM(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PLNPR(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PRT(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PUF(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PVF(KPROMA, KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PUH(KPROMA, 0:KFLEV)
    REAL(KIND=JPRB), INTENT(IN) :: PVH(KPROMA, 0:KFLEV)
    REAL(KIND=JPRB), INTENT(OUT) :: PX(KPROMA, KFLEV)
    REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PNHPPI(KPROMA, KFLEV)
    LOGICAL, OPTIONAL, INTENT(IN) :: LDVFE
    
    ! -----------------------------------------------------------------------------
    
    
    
    ! -----------------------------------------------------------------------------
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE GPXX_OPENACC
END INTERFACE
