SUBROUTINE RADHEAT_OPENACC (YDCST, YDTHF, YDERAD, YDERDI, YDML_PHY_MF, KIDIA, KFDIA, KLON, KLEV, PAPHM1, PEMIS, PEMTED, PMU0,  &
& PSOLO, PQM1, PTE, PTRSOL, PTRSOD, PTSM1M, PTSPHY, PTRSODIR, PTRSODIF, PALBD, PALBP, PFRSO, PFRTH, PFRSODS, PFRTHDS, PCEMTR,  &
& PCTRSO, PFRSOC, PFRTHC, PSUDU, PSDUR, PDSRP, PSFSWDIR, PSFSWDIF, PFRSOPS, PFRSOFS, PFRSOPT, YDSTACK)
  
  !**** *RADHEAT* - COMPUTES TEMPERATURE CHANGES DUE TO RADIATION.
  
  !     PURPOSE.
  !     --------
  
  !          THIS ROUTINE COMPUTES THE TENDENCIES OF THE ATMOSPHERE'S
  !     TEMPERATURE DUE TO THE EFFECTS OF LONG WAVE AND SHORT WAVE
  !     RADIATION. THE COMPUTATION IS DONE ON THE T-1 TIME LEVEL USING
  !     VALUES OF ATMOSPHERIC TRANSMISIVITIES AND EMISSIVITIES THAT HAVE
  !     BEEN STORED AT THE LAST FULL RADIATION TIME STEP. THE SURFACE
  !     SOLAR FLUX LATER TO BE USED IN THE SOIL PROCESS CALCULATIONS IS
  !     ALSO STORED.
  
  !**   INTERFACE.
  !     ----------
  
  !          *RADHEAT* IS CALLED FROM *CALLPAR*.
  !          THE ROUTINE TAKES ITS INPUT FROM THE LONG-TERM STORAGE: TS,
  !     T AND Q AT T-1 AND P ON LEVEL BOUNDARIES AND IN THE MIDDLE OF THE
  !     LAYERS AT THE SAME TIME. ALSO USED ARE THE FOUR PARAMERTERS
  !     DESCRIBING THE SUN'S POSITION. THE ROUTINE RETURNS ITS OUTPUT TO
  !     THE LONG TERM STORAGE: TENDENCIES OF T AND SURFACE SOLAR FLUX.
  
  !     METHOD.
  !     -------
  
  !          A CALL TO SUBROUTINE *SOLANG* GIVES FIELDS OF SOLAR ZENITH
  !     ANGLES AND RELATIVE DAY LENGTH FROM WHICH AN EFFECTIVE SOLAR
  !     INFLUX IS COMPUTED. THE RESULTS ARE OF COURSE DIFFERENT DEPENDING
  !     ON THE SWITCH ON OR OFF OF THE DIURNAL CYCLE. PRODUCT OF SOLAR
  !     INFLUX BY TRANSMISSIVITIES LEADS TO SOLAR FLUXES. THEN THE
  !     TEMPERATURES ARE INTERPOLATED/EXTRAPOLATED TO THE LAYER BOUNDARIES
  !     (AT THE BOTTOM ONE TAKES THE SURFACE TEMPERATURE) AND A PRODUCT BY
  !     EMISSIVITIES OF SIGMA*T**4 GIVES THERMAL FLUXES. THE TWO FLUXES
  !     ARE ADDED AND DIVERGENCES COMPUTED TO GIVE HEATING RATES.
  
  !          WITH THE METEO-FRANCE PHYSICS, THE CONSTANT EMISSIVITY
  !     HYPOTHESIS LEADS TO SPURIOUS OSCILLATIONS IN THE STRATOSPHERE. A
  !     CONSTANT THERMAL FLUX APPROACH IS THEREFORE USED UNTIL A NEW
  !     SUBROUTINE RISES...
  
  !     EXTERNALS.
  !     ----------
  
  !     REFERENCE.
  !     ----------
  
  !          SEE RADIATION'S PART OF THE MODEL'S DOCUMENTATION FOR DETAILS
  !     ABOUT THE MATHEMATICS OF THIS ROUTINE.
  
  !     AUTHOR.
  !     -------
  !      J.-F. GELEYN     E.C.M.W.F.    82/06/03.
  
  !     MODIFICATIONS.
  !     --------------
  !      M.Hamrud      01-Oct-2003 CY28 Cleaning
  !      JJMorcrette 20090408 bug-fix to solar zenith angle
  !      M. Janiskova     03-Mar-2009 Code re-arrangement for adjoint comp.
  !      A. Alias    Dec 2010 Call to RADHEAT modified to compute PSFSWDIF/PSFSWDIR outputs
  !      Y. Bouteloup Nov 2014 : Correction of a bug in the computation of SW downward diagnostic
  !                              in the case LMSE=TRUE
  !      Y. Bouteloup Jun 2015 : Re-activation of LMSE protection
  !      2022-04-13: J.M. Piriou: introduce Sun eclipses: PSOLO.
  !-----------------------------------------------------------------------
  
!$acc routine( RADHEAT_OPENACC ) seq
  
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  USE YOMCST, ONLY: TCST
  USE YOETHF, ONLY: TTHF
  USE YOERDI, ONLY: TERDI
  USE YOERAD, ONLY: TERAD
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  TYPE(TCST), INTENT(IN) :: YDCST
  TYPE(TTHF), INTENT(IN) :: YDTHF
  TYPE(TERAD), INTENT(IN) :: YDERAD
  TYPE(TERDI), INTENT(IN) :: YDERDI
  TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: YDML_PHY_MF
  INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
  INTEGER(KIND=JPIM), INTENT(IN) :: KLON
  INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
  REAL(KIND=JPRB), INTENT(IN) :: PAPHM1(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(IN) :: PEMIS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PEMTED(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(IN) :: PMU0(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PSOLO(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PQM1(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(INOUT) :: PTE(KLON, KLEV)
  REAL(KIND=JPRB), INTENT(IN) :: PTRSOL(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(IN) :: PTRSOD(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PTSM1M(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PTSPHY
  REAL(KIND=JPRB), INTENT(IN) :: PTRSODIR(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(IN) :: PTRSODIF(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(IN) :: PALBD(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(IN) :: PALBP(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSO(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRTH(KLON, KLEV + 1)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSODS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRTHDS(KLON)
  REAL(KIND=JPRB), INTENT(IN) :: PCEMTR(KLON, 2)
  REAL(KIND=JPRB), INTENT(IN) :: PCTRSO(KLON, 2)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSOC(KLON, 2)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRTHC(KLON, 2)
  REAL(KIND=JPRB), INTENT(IN) :: PSUDU(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSDUR(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PDSRP(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PSFSWDIR(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(OUT) :: PSFSWDIF(KLON, YDERAD%NSW)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSOPS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSOFS(KLON)
  REAL(KIND=JPRB), INTENT(OUT) :: PFRSOPT(KLON)
  
  !-----------------------------------------------------------------------
  
  REAL(KIND=JPRB) :: ZDTDT
  REAL(KIND=JPRB) :: ZDTDIV
  REAL(KIND=JPRB) :: ZFLB
  REAL(KIND=JPRB) :: ZFLT
  REAL(KIND=JPRB) :: ZFSO
  REAL(KIND=JPRB) :: ZFTE
  REAL(KIND=JPRB) :: ZI0
  REAL(KIND=JPRB) :: ZTH4
  
  INTEGER(KIND=JPIM) :: ILONS
  INTEGER(KIND=JPIM) :: JK
  INTEGER(KIND=JPIM) :: JL
  INTEGER(KIND=JPIM) :: JSW
  
  REAL(KIND=JPRB) :: ZBUD
  REAL(KIND=JPRB) :: ZCONS1
  REAL(KIND=JPRB) :: ZCONS3
  REAL(KIND=JPRB) :: ZRII0
  REAL(KIND=JPRB) :: ZTMST
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=    JPIM) :: JLON
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  JLON = KIDIA
  YLSTACK = YDSTACK
  
  !     ------------------------------------------------------------------
  
  !*    COMPUTATIONAL CONSTANTS.
  !     ------------- ----------
  
  ZTMST = PTSPHY
  ZCONS1 = YDERDI%RRAE*(YDERDI%RRAE + 2.0_JPRB)
  ZCONS3 = YDCST%RG / YDCST%RCPD
  ILONS = KFDIA - KIDIA + 1
  ZBUD = 1.0_JPRB
  ZRII0 = YDML_PHY_MF%YRPHY3%RII0
  
  !     ------------------------------------------------------------------
  
  !*         1.     SECURITIES.
  !                 -----------
  PFRSODS(JLON) = 0.0_JPRB
  PFRSOFS(JLON) = 0.0_JPRB
  PFRSOPS(JLON) = 0.0_JPRB
  
  !     ------------------------------------------------------------------
  
  !*         2.     INCIDENT SOLAR RADIATION
  !                 ------------------------
  
  IF (PMU0(JLON) >= 1.E-10_JPRB) THEN
    !!    ZI0(JL)=RRAE/(SQRT(PMU0(JL)**2+ZCONS1)-PMU0(JL)) * ZRII0
    ZI0 = PMU0(JLON)*ZRII0*(1._JPRB - PSOLO(JLON))
  ELSE
    ZI0 = 0.0_JPRB
  END IF
  !     ------------------------------------------------------------------
  
  !*         3.     TEMPERATURES AT LAYERS' BOUNDARIES.
  !                 -----------------------------------
  
  !     ------------------------------------------------------------------
  
  !*         4.     FLUXES AND THEIR DIVERGENCES.
  !                 ------ --- ----- ------------
  
  !*         4.1     TOP FLUX.
  
  ZFSO = ZI0*PTRSOL(JLON, 1)
  ZFTE = PEMTED(JLON, 1)
  
  PFRTH(JLON, 1) = ZFTE
  PFRSO(JLON, 1) = ZFSO
  
  PFRTHC(JLON, 1) = PCEMTR(JLON, 1)
  PFRSOC(JLON, 1) = ZI0*PCTRSO(JLON, 1)
  
  !*         4.2     VERTICAL LOOP, BOTTOM FLUX AND HEATING RATE.
  
  !***
  DO JK=1,KLEV
    !***
    ZFLT = ZFSO + ZFTE
    
    ZFSO = ZI0*PTRSOL(JLON, JK + 1)
    ! Set surface solar flux to minimum value for stability in vertical diffusion
    IF (JK == KLEV .and. ZFSO < 1.E-15_JPRB) THEN
      ZFSO = 1.E-15_JPRB
    END IF
    ZFTE = PEMTED(JLON, JK + 1)
    ZFLB = ZFSO + ZFTE
    ZDTDIV = 1.0_JPRB / ((PAPHM1(JLON, JK + 1) - PAPHM1(JLON, JK))*(1.0_JPRB + YDTHF%RVTMP2*PQM1(JLON, JK)))
    ZDTDT = -ZCONS3*(ZFLB - ZFLT)*ZDTDIV
    PTE(JLON, JK) = PTE(JLON, JK) + ZDTDT
    
    !*         4.4     FLUX SWAP, END OF THE LOOP AND SURFACE SOLAR FLUX.
    
    PFRTH(JLON, JK + 1) = ZFTE
    PFRSO(JLON, JK + 1) = ZFSO
    !***
  END DO
  !***
  
  PFRTHC(JLON, 2) = PCEMTR(JLON, 2)
  PFRSOC(JLON, 2) = ZI0*PCTRSO(JLON, 2)
  
  !*   4.5     SOLAR AND TERRESTRIAL DOWNWARD FLUXES AT SURFACE AND TOA
  
  
  PDSRP(JLON) = ZI0*PSUDU(JLON)
  IF (PDSRP(JLON) >= YDERDI%RSUNDUR) THEN
    PSDUR(JLON) = 1.0_JPRB
  ELSE
    PSDUR(JLON) = 0.0_JPRB
  END IF
  ZTH4 = YDCST%RSIGMA*PTSM1M(JLON)**4
  PFRTHDS(JLON) = (PEMTED(JLON, KLEV + 1) + PEMIS(JLON)*ZTH4) / PEMIS(JLON)
  !Total downward diag top
  PFRSOPT(JLON) = ZI0
  IF (YDML_PHY_MF%YRARPHY%LMSE .or. YDML_PHY_MF%YRPHY%LHLRADUPD) THEN
    DO JSW=1,YDERAD%NSW
      ! Direct net
      ZFSO = MAX(ZI0*PTRSODIR(JLON, JSW), 1.E-15_JPRB)
      ! Direct Down
      PSFSWDIR(JLON, JSW) = ZFSO / (1.0_JPRB - PALBP(JLON, JSW))
      ! Diffu net
      ZFSO = MAX(ZI0*PTRSODIF(JLON, JSW), 1.E-15_JPRB)
      ! Diffu Down
      PSFSWDIF(JLON, JSW) = ZFSO / (1.0_JPRB - PALBD(JLON, JSW))
      !Direct downward diag
      PFRSOPS(JLON) = PFRSOPS(JLON) + PSFSWDIR(JLON, JSW)
      !Diffuse downward diag
      PFRSOFS(JLON) = PFRSOFS(JLON) + PSFSWDIF(JLON, JSW)
      !Global radiation
      PFRSODS(JLON) = PFRSODS(JLON) + PSFSWDIF(JLON, JSW) + PSFSWDIR(JLON, JSW)
    END DO
  ELSE
    PFRSODS(JLON) = ZI0*PTRSOD(JLON)
  END IF
  !     ------------------------------------------------------------------
  
END SUBROUTINE RADHEAT_OPENACC
