INTERFACE
  SUBROUTINE PPWETPOINT_OPENACC (YDCST, YDPHY, KIDIA, KFDIA, KLON, PAPRS, PT, PQV, PQL, PQI, PWETPOINT, YDSTACK)
!$acc routine( PPWETPOINT_OPENACC ) seq
    
    USE PARKIND1, ONLY: JPIM, JPRB
    USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
    
    USE YOMPHY, ONLY: TPHY
    USE YOMCST, ONLY: TCST
    
    USE STACK_MOD
    
    IMPLICIT NONE
    
    TYPE(TCST), INTENT(IN) :: YDCST
    TYPE(TPHY), INTENT(IN) :: YDPHY
    INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
    INTEGER(KIND=JPIM), INTENT(IN) :: KLON
    REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON)
    REAL(KIND=JPRB), INTENT(IN) :: PT(KLON)
    REAL(KIND=JPRB), INTENT(IN) :: PQV(KLON)
    REAL(KIND=JPRB), INTENT(IN) :: PQL(KLON)
    REAL(KIND=JPRB), INTENT(IN) :: PQI(KLON)
    REAL(KIND=JPRB), INTENT(OUT) :: PWETPOINT(KLON)
    
    
    
    
    TYPE(STACK), INTENT(IN) :: YDSTACK
  END SUBROUTINE PPWETPOINT_OPENACC
END INTERFACE
